"""Endor Labs SDK.

A Python SDK for the Endor Labs platform.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

from .api_client import APIClient
from .client_surface import Client
from .core.exceptions import (
    AmbiguousError,
    ConflictError,
    EndorAPIError,
    MethodNotSupportedError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    ServerError,
    UnauthorizedError,
    ValidationError,
    map_status_code_to_exception,
)
from .core.filter import F, FilterExpression
from .core.types import ListParameters
from .resources import (
    dependency_metadata,
    finding,
    installation,
    linter_result,
    malware,
    metric,
    namespace,
    package_version,
    policy,
    project,
    repository,
    repository_version,
    vulnerability,
)

if TYPE_CHECKING:
    from .context.models import InitStatus
    from .discovery import SdkDiscovery

try:
    from endorlabs._version import __version__  # generated by hatch-vcs
except ImportError:  # editable install or no build
    __version__ = "0.0.0.dev0"


def agent_knowledge_dir() -> Path:
    """Return site-packages path to the shipped agent knowledge package."""
    from .agent_knowledge import agent_knowledge_dir as _agent_knowledge_dir

    return _agent_knowledge_dir()


def agent_knowledge_index_path() -> Path:
    """Return path to Tier-0 INDEX.md in the shipped agent knowledge package."""
    from .agent_knowledge import (
        agent_knowledge_index_path as _agent_knowledge_index_path,
    )

    return _agent_knowledge_index_path()


def agent_knowledge_manifest() -> dict[str, Any]:
    """Parse MANIFEST.json from the shipped agent knowledge package."""
    from .agent_knowledge import agent_knowledge_manifest as _agent_knowledge_manifest

    return _agent_knowledge_manifest()


def agent_knowledge_rule_ids() -> list[str]:
    """Return bootstrap rule ids from the shipped agent knowledge manifest."""
    from .agent_knowledge import agent_knowledge_rule_ids as _agent_knowledge_rule_ids

    return _agent_knowledge_rule_ids()


def agent_knowledge_bootstrap_paths() -> list[Path]:
    """Return INDEX.md and bootstrap rule paths for harness injection."""
    from .agent_knowledge import (
        agent_knowledge_bootstrap_paths as _agent_knowledge_bootstrap_paths,
    )

    return _agent_knowledge_bootstrap_paths()


def discover() -> SdkDiscovery:
    """Return wheel-shipped discovery paths (read before ``Client()``)."""
    from .discovery import discover as _discover

    return _discover()


# Re-export for type checkers and ``from endorlabs import SdkDiscovery``.
from .discovery import SdkDiscovery  # noqa: E402


def init(
    output_dir: str | Path = ".endorlabs-context",
    include_openapi: bool = False,
    include_user_docs: bool = False,
    include_agent_knowledge: bool = True,
    max_pages: int | None = None,
    force: bool = False,
    sync_skills: Literal["none", "cursor", "claude", "both"] = "none",
    client: APIClient | None = None,
) -> InitStatus:
    """Bootstrap Endor Labs context for agentic workflows.

    By default, ``init()`` materializes agent knowledge under ``sdk/``. Pass explicit
    flags to download platform context or mirror skills.

    Args:
        output_dir: Directory to save context files (default: .endorlabs-context).
        include_openapi: Download OpenAPI spec (default: False).
        include_user_docs: Download user documentation (default: False).
        include_agent_knowledge: Materialize agent knowledge to sdk/ (default: True).
        max_pages: Maximum number of user doc pages to download (default: all).
        force: Force re-download even if files exist (default: False).
        sync_skills: Mirror skills into runtime discovery directories.
        client: Optional APIClient instance for OpenAPI download.

    Returns:
        InitStatus with paths to materialized and downloaded files.

    Raises:
        UnauthorizedError: If OpenAPI authentication fails.
        ImportError: If context dependencies are not installed (for user docs).
            Install with: pip install endorlabs[docs]

    Example::

        >>> import endorlabs
        >>> status = endorlabs.init()
        >>> print(status.agent_knowledge_path)
        .endorlabs-context/sdk

    """
    from .context import _sync

    return _sync.init(
        output_dir=output_dir,
        include_openapi=include_openapi,
        include_user_docs=include_user_docs,
        include_agent_knowledge=include_agent_knowledge,
        max_pages=max_pages,
        force=force,
        sync_skills=sync_skills,
        client=client,
    )


def sync_agent_skills(
    *,
    repo_root: str | Path = ".",
    target: Literal["none", "cursor", "claude", "both"] = "none",
    source_dir: str | Path | None = None,
) -> dict[str, Path]:
    """Mirror ``endor-*`` skills into runtime discovery directories."""
    from .context import _sync

    return _sync.sync_agent_skills(
        repo_root=repo_root,
        target=target,
        source_dir=source_dir,
    )


__all__ = [
    "APIClient",
    "AmbiguousError",
    "Client",
    "ConflictError",
    "EndorAPIError",
    "F",
    "FilterExpression",
    "ListParameters",
    "MethodNotSupportedError",
    "NotFoundError",
    "PermissionDeniedError",
    "RateLimitError",
    "SdkDiscovery",
    "ServerError",
    "UnauthorizedError",
    "ValidationError",
    "agent_knowledge_bootstrap_paths",
    "agent_knowledge_dir",
    "agent_knowledge_index_path",
    "agent_knowledge_manifest",
    "agent_knowledge_rule_ids",
    "dependency_metadata",
    "discover",
    "finding",
    "init",
    "installation",
    "linter_result",
    "malware",
    "map_status_code_to_exception",
    "metric",
    "namespace",
    "package_version",
    "policy",
    "project",
    "repository",
    "repository_version",
    "sync_agent_skills",
    "vulnerability",
]
