"""Endor Labs SDK.

A Python SDK for the Endor Labs platform.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Literal

from .api_client import APIClient
from .client_surface import Client
from .core.exceptions import (
    AmbiguousError,
    ConflictError,
    EndorAPIError,
    MethodNotSupportedError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    ServerError,
    UnauthorizedError,
    ValidationError,
    map_status_code_to_exception,
)
from .core.filter import F, FilterExpression
from .resources import (
    dependency_metadata,
    finding,
    installation,
    linter_result,
    malware,
    metric,
    namespace,
    package_version,
    policy,
    project,
    query_malware,
    query_vulnerability,
    repository,
    repository_version,
    vulnerability,
)

if TYPE_CHECKING:
    from .context.models import InitStatus

try:
    from endorlabs._version import __version__  # generated by hatch-vcs
except ImportError:  # editable install or no build
    __version__ = "0.0.0.dev0"


def init(
    output_dir: str | Path = ".endorlabs-context",
    include_openapi: bool = True,
    include_user_docs: bool = True,
    max_pages: int | None = None,
    force: bool = False,
    sync_skills: Literal["none", "cursor", "claude", "both", "auto"] = "none",
    client: APIClient | None = None,
) -> InitStatus:
    """Bootstrap Endor Labs context for agentic workflows.

    Downloads API specification and user documentation to a local directory,
    and can optionally refresh runtime skill mirrors.

    Args:
        output_dir: Directory to save context files (default: .endorlabs-context).
        include_openapi: Download OpenAPI spec (default: True).
        include_user_docs: Download user documentation (default: True).
        max_pages: Maximum number of user doc pages to download (default: all).
        force: Force re-download even if files exist (default: False).
        sync_skills: Mirror `skills-src/` into runtime discovery directories.
            Use `none`, `cursor`, `claude`, `both`, or `auto`.
        client: Optional APIClient instance. If not provided, one is created
            when `include_openapi=True` (requires
            ENDOR_API_CREDENTIALS_KEY/SECRET or ENDOR_TOKEN env vars).

    Returns:
        InitStatus with paths to downloaded files and metadata.

    Raises:
        UnauthorizedError: If OpenAPI authentication fails.
        ImportError: If context dependencies are not installed (for user docs).
            Install with: pip install endorlabs-sdk[context]

    Example::

        >>> import endorlabs
        >>> status = endorlabs.init()
        >>> print(status.openapi_path)
        .endorlabs-context/openapiv2.swagger.json

    """
    from .context import _sync

    return _sync.init(
        output_dir=output_dir,
        include_openapi=include_openapi,
        include_user_docs=include_user_docs,
        max_pages=max_pages,
        force=force,
        sync_skills=sync_skills,
        client=client,
    )


def sync_agent_skills(
    *,
    repo_root: str | Path = ".",
    target: Literal["none", "cursor", "claude", "both", "auto"] = "none",
    source_dir: str | Path | None = None,
) -> dict[str, Path]:
    """Mirror repo skill sources into runtime discovery directories."""
    from .context import _sync

    return _sync.sync_agent_skills(
        repo_root=repo_root,
        target=target,
        source_dir=source_dir,
    )


__all__ = [
    "APIClient",
    "AmbiguousError",
    "Client",
    "ConflictError",
    "EndorAPIError",
    "F",
    "FilterExpression",
    "MethodNotSupportedError",
    "NotFoundError",
    "PermissionDeniedError",
    "RateLimitError",
    "ServerError",
    "UnauthorizedError",
    "ValidationError",
    "dependency_metadata",
    "finding",
    "init",
    "installation",
    "linter_result",
    "malware",
    "map_status_code_to_exception",
    "metric",
    "namespace",
    "package_version",
    "policy",
    "project",
    "query_malware",
    "query_vulnerability",
    "repository",
    "repository_version",
    "sync_agent_skills",
    "vulnerability",
]
