# Generated by scripts/generate_client_stub.py — do not edit by hand.
# Source of truth: endorlabs.registry.RESOURCE_REGISTRY and CUSTOM_FACADE_REGISTRY.

from typing import Any

from .api_client import APIClient
from .facade import (
    OssResourceFacade,
    ResourceFacade,
    ScanLogsFacade,
    SystemResourceFacade,
)
from .resources.api_key import APIKey
from .resources.audit_log import AuditLog
from .resources.authentication_log import AuthenticationLog
from .resources.authorization_policy import AuthorizationPolicy
from .resources.code_owners import CodeOwners
from .resources.dependency_metadata import DependencyMetadata
from .resources.endor_license import EndorLicense
from .resources.finding import Finding
from .resources.finding_log import FindingLog
from .resources.installation import Installation
from .resources.invitation import Invitation
from .resources.linter_result import LinterResult
from .resources.metric import Metric
from .resources.namespace import Namespace
from .resources.notification_target import NotificationTarget
from .resources.package_license import PackageLicense
from .resources.package_version import PackageVersion
from .resources.policy import Policy
from .resources.policy_template import PolicyTemplate
from .resources.project import Project
from .resources.repository import Repository
from .resources.repository_version import RepositoryVersion
from .resources.scan_log_request import ScanLogRequest
from .resources.scan_profile import ScanProfile
from .resources.scan_result import ScanResult
from .resources.scan_workflow import ScanWorkflow
from .resources.scan_workflow_result import ScanWorkflowResult
from .resources.semgrep_rule import SemgrepRule
from .resources.version_upgrade import VersionUpgrade

class Client:
    """Client with default namespace and resource facades."""

    namespace: ResourceFacade[Namespace]
    project: ResourceFacade[Project]
    finding: ResourceFacade[Finding]
    repository: ResourceFacade[Repository]
    repository_version: ResourceFacade[RepositoryVersion]
    policy: ResourceFacade[Policy]
    authorization_policy: ResourceFacade[AuthorizationPolicy]
    package_version: ResourceFacade[PackageVersion]
    installation: ResourceFacade[Installation]
    scan_profile: ResourceFacade[ScanProfile]
    scan_result: ResourceFacade[ScanResult]
    scan_log_request: ResourceFacade[ScanLogRequest]
    linter_result: ResourceFacade[LinterResult]
    metric: ResourceFacade[Metric]
    semgrep_rule: ResourceFacade[SemgrepRule]
    api_key: ResourceFacade[APIKey]
    audit_log: ResourceFacade[AuditLog]
    finding_log: ResourceFacade[FindingLog]
    notification_target: ResourceFacade[NotificationTarget]
    scan_workflow: ResourceFacade[ScanWorkflow]
    scan_workflow_result: ResourceFacade[ScanWorkflowResult]
    version_upgrade: ResourceFacade[VersionUpgrade]
    invitation: ResourceFacade[Invitation]
    code_owners: ResourceFacade[CodeOwners]
    package_license: OssResourceFacade[PackageLicense]
    dependency_metadata: OssResourceFacade[DependencyMetadata]
    authentication_log: SystemResourceFacade[AuthenticationLog]
    endor_license: SystemResourceFacade[EndorLicense]
    policy_template: SystemResourceFacade[PolicyTemplate]
    scan_logs: ScanLogsFacade

    _client: APIClient | None

    def __init__(
        self,
        api_client: APIClient | None = ...,
        tenant: str | None = ...,
        *,
        timeout: float = ...,
        content_type: str = ...,
        accept_encoding: str | None = ...,
        max_retries: int = ...,
        base_url: str | None = ...,
        **client_kwargs: Any,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> None: ...
    def wait_until(
        self,
        predicate: Any,
        timeout: float = ...,
        poll_interval_max: float = ...,
    ) -> bool: ...
