# Generated by devtools/generate_client_stub.py — do not edit by hand.
# pyright: reportImplicitOverride=false
# Source of truth: endorlabs.registry.RESOURCE_REGISTRY and CUSTOM_FACADE_REGISTRY.

from typing import Any

from .api_client import APIClient
from .facade import CallGraphDataFacade, ListableFacade, ResourceRuntimeFacade
from .resources.api_key import APIKey, CreateAPIKeyPayload
from .resources.audit_log import AuditLog, CreateAuditLogPayload
from .resources.authentication_log import AuthenticationLog
from .resources.authorization_policy import (
    AuthorizationPolicy,
    CreateAuthorizationPolicyPayload,
)
from .resources.code_owners import CodeOwners, CreateCodeOwnersPayload
from .resources.dependency_metadata import (
    CreateDependencyMetadataPayload,
    DependencyMetadata,
)
from .resources.endor_license import EndorLicense
from .resources.finding import CreateFindingPayload, Finding
from .resources.finding_log import CreateFindingLogPayload, FindingLog
from .resources.identity_provider import IdentityProvider
from .resources.installation import CreateInstallationPayload, Installation
from .resources.invitation import CreateInvitationPayload, Invitation
from .resources.linter_result import CreateLinterResultPayload, LinterResult
from .resources.malware import Malware
from .resources.metric import CreateMetricPayload, Metric
from .resources.namespace import CreateNamespacePayload, Namespace
from .resources.notification_target import (
    CreateNotificationTargetPayload,
    NotificationTarget,
)
from .resources.package_firewall_log import PackageFirewallLog
from .resources.package_license import CreatePackageLicensePayload, PackageLicense
from .resources.package_version import CreatePackageVersionPayload, PackageVersion
from .resources.policy import CreatePolicyPayload, Policy
from .resources.policy_template import PolicyTemplate
from .resources.pr_comment_config import CreatePRCommentConfigPayload, PRCommentConfig
from .resources.project import CreateProjectPayload, Project
from .resources.query import Query
from .resources.query_malware import CreateQueryMalwarePayload, QueryMalware
from .resources.query_similar_packages import QuerySimilarPackages
from .resources.query_vulnerability import (
    CreateQueryVulnerabilityPayload,
    QueryVulnerability,
)
from .resources.repository import CreateRepositoryPayload, Repository
from .resources.repository_version import (
    CreateRepositoryVersionPayload,
    RepositoryVersion,
)
from .resources.saved_query import SavedQuery
from .resources.scan_log_request import ScanLogRequest
from .resources.scan_profile import CreateScanProfilePayload, ScanProfile
from .resources.scan_result import CreateScanResultPayload, ScanResult
from .resources.scan_workflow import ScanWorkflow
from .resources.scan_workflow_result import ScanWorkflowResult
from .resources.semgrep_rule import CreateSemgrepRulePayload, SemgrepRule
from .resources.vector_store import VectorStore
from .resources.vector_store_query import (
    CreateVectorStoreQueryPayload,
    VectorStoreQuery,
)
from .resources.version_upgrade import VersionUpgrade
from .resources.vulnerability import Vulnerability

class _APIKeyFacade(ResourceRuntimeFacade[APIKey]):
    """API key for programmatic access.

    Create mode: both.
    """

    def create(
        self,
        payload: CreateAPIKeyPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        permissions: dict[str, Any],
        expiration_time: Any,
        **kwargs: Any,
    ) -> APIKey: ...

class _AuditLogFacade(ResourceRuntimeFacade[AuditLog]):
    """Audit trail of API operations.

    Create mode: both.
    """

    def create(
        self,
        payload: CreateAuditLogPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        operation: Any,
        message_uuid: Any | None = None,
        message_kind: Any | None = None,
        error: Any | None = None,
        claims: dict[str, Any] | None = None,
        remote_address: Any | None = None,
        **kwargs: Any,
    ) -> AuditLog: ...

class _AuthenticationLogFacade(ListableFacade[AuthenticationLog]):
    """Authentication event log."""

    def get(
        self,
        id_or_resource: str | AuthenticationLog,
        namespace: str | None = ...,
    ) -> AuthenticationLog: ...

class _AuthorizationPolicyFacade(ResourceRuntimeFacade[AuthorizationPolicy]):
    """Permission grant for an authenticated identity.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateAuthorizationPolicyPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        clause: Any,
        target_namespaces: Any,
        propagate: Any,
        permissions: dict[str, Any],
        expiration_time: Any | None = None,
        **kwargs: Any,
    ) -> AuthorizationPolicy: ...

class _CodeOwnersFacade(ResourceRuntimeFacade[CodeOwners]):
    """Code ownership assignments for a project.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateCodeOwnersPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        patterns: dict[str, Any] | None = None,
        version: Any | None = None,
        **kwargs: Any,
    ) -> CodeOwners: ...

class _DependencyMetadataFacade(ResourceRuntimeFacade[DependencyMetadata]):
    """Dependency relationship between packages.

    Create mode: both.
    Workflow flags: project-namespace-list.
    """

    def create(
        self,
        payload: CreateDependencyMetadataPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        data: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> DependencyMetadata: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _EndorLicenseFacade(ListableFacade[EndorLicense]):
    """Platform license assigned to a tenant."""

    def get(
        self,
        id_or_resource: str | EndorLicense,
        namespace: str | None = ...,
    ) -> EndorLicense: ...

class _FindingFacade(ResourceRuntimeFacade[Finding]):
    """Security or compliance finding from a scan.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    Workflow flags: project-namespace-list.
    """

    def create(
        self,
        payload: CreateFindingPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        project_uuid: Any,
        last_processed: Any,
        level: Any,
        summary: Any,
        finding_tags: Any,
        target_uuid: Any,
        extra_key: Any,
        dismiss: Any | None = None,
        remediation: Any | None = None,
        finding_metadata: Any | None = None,
        method: Any | None = None,
        target_dependency_package_name: Any | None = None,
        target_dependency_name: Any | None = None,
        target_dependency_version: Any | None = None,
        explanation: Any | None = None,
        remediation_action: Any | None = None,
        source_code_version: Any | None = None,
        reachable_paths: Any | None = None,
        ecosystem: Any | None = None,
        finding_categories: Any | None = None,
        relationship: Any | None = None,
        latest_version: Any | None = None,
        dependency_file_paths: Any | None = None,
        approximation: Any | None = None,
        proposed_version: Any | None = None,
        exceptions: Any | None = None,
        actions: Any | None = None,
        fixing_upgrades: Any | None = None,
        fixing_patch: Any | None = None,
        code_owners: Any | None = None,
        location_urls: Any | None = None,
        call_graph_analysis_type: Any | None = None,
        snooze: Any | None = None,
        ignore: Any | None = None,
        **kwargs: Any,
    ) -> Finding: ...
    def list_by_project(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_dependency_metadata(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _FindingLogFacade(ResourceRuntimeFacade[FindingLog]):
    """Historical snapshot of a finding state.

    Create mode: both.
    """

    def create(
        self,
        payload: CreateFindingLogPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        finding_uuid: Any,
        finding_parent_kind: Any,
        finding_parent_uuid: Any,
        operation: Any,
        introduced_at: Any,
        method: Any,
        level: Any,
        finding_tags: Any,
        finding_categories: Any,
        resolved_at: Any | None = None,
        days_unresolved: Any | None = None,
        ecosystem: Any | None = None,
        target_uuid: Any | None = None,
        target_dependency_package_name: Any | None = None,
        approximation: Any | None = None,
        finding_parent_name: Any | None = None,
        snooze: Any | None = None,
        location: Any | None = None,
        **kwargs: Any,
    ) -> FindingLog: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _IdentityProviderFacade(ListableFacade[IdentityProvider]):
    """Consumer facade model for IdentityProvider (generated wire shape)."""

    def get(
        self,
        id_or_resource: str | IdentityProvider,
        namespace: str | None = ...,
    ) -> IdentityProvider: ...

class _InstallationFacade(ResourceRuntimeFacade[Installation]):
    """SCM platform integration (GitHub, GitLab, Azure, Bitbucket).

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateInstallationPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        public: Any | None = None,
        external_id: Any | None = None,
        suspended: Any | None = None,
        project_uuids: Any | None = None,
        login: Any | None = None,
        invalid: Any | None = None,
        enabled_features: Any | None = None,
        platform_source: Any | None = None,
        platform_type: Any | None = None,
        github_config: Any | None = None,
        azure_config: Any | None = None,
        gitlab_config: Any | None = None,
        bitbucket_config: Any | None = None,
        huggingface_config: Any | None = None,
        include_archived_repos: Any | None = None,
        installation_error_message: Any | None = None,
        scm_app_uuid: Any | None = None,
        cleanup_stale_namespaces: Any | None = None,
        **kwargs: Any,
    ) -> Installation: ...

class _InvitationFacade(ResourceRuntimeFacade[Invitation]):
    """User invitation for platform access.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateInvitationPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        user_email: Any,
        **kwargs: Any,
    ) -> Invitation: ...

class _LinterResultFacade(ResourceRuntimeFacade[LinterResult]):
    """Linter analysis result for a package or repository version.

    Create mode: both.
    """

    def create(
        self,
        payload: CreateLinterResultPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        project_uuid: Any,
        origin: Any,
        level: Any,
        extra_key: Any,
        version: Any | None = None,
        sarif_result: Any | None = None,
        ai_result: Any | None = None,
        ecosystem: Any | None = None,
        semgrep: Any | None = None,
        secret: Any | None = None,
        aisast: Any | None = None,
        fingerprints: Any | None = None,
        fingerprint_count: Any | None = None,
        distribution_format: Any | None = None,
        ref: Any | None = None,
        storage_location: Any | None = None,
        suppressed: Any | None = None,
        linter_correctness_analyses: Any | None = None,
        endor_fingerprint: Any | None = None,
        **kwargs: Any,
    ) -> LinterResult: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _MalwareFacade(ListableFacade[Malware]):
    """Open-source malware records.

    Identity kwargs: name (-> meta.name).
    OSS-scoped (namespace fixed to 'oss').
    """

    def get(
        self,
        id_or_resource: str | Malware,
        namespace: str | None = ...,
    ) -> Malware: ...

class _MetricFacade(ResourceRuntimeFacade[Metric]):
    """Analytics output attached to packages or repositories.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateMetricPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        analytic: Any,
        project_uuid: Any,
        metric_values: dict[str, Any],
        raw: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> Metric: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _NamespaceFacade(ResourceRuntimeFacade[Namespace]):
    """Isolate and organize resources in a parent-child hierarchy.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateNamespacePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        managed: Any | None = None,
        **kwargs: Any,
    ) -> Namespace: ...

class _NotificationTargetFacade(ResourceRuntimeFacade[NotificationTarget]):
    """Integration endpoint for notification delivery.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateNotificationTargetPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        action: Any,
        custom_template: Any | None = None,
        **kwargs: Any,
    ) -> NotificationTarget: ...

class _PRCommentConfigFacade(ResourceRuntimeFacade[PRCommentConfig]):
    """Consumer facade model for PRCommentConfig (generated wire shape).

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreatePRCommentConfigPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        template: Any,
        platform_type: Any | None = None,
        **kwargs: Any,
    ) -> PRCommentConfig: ...

class _PackageFirewallLogFacade(ListableFacade[PackageFirewallLog]):
    """Package firewall audit event recording action and trigger reason."""

    def get(
        self,
        id_or_resource: str | PackageFirewallLog,
        namespace: str | None = ...,
    ) -> PackageFirewallLog: ...

class _PackageLicenseFacade(ResourceRuntimeFacade[PackageLicense]):
    """License information for a package.

    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreatePackageLicensePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        code_licenses: Any | None = None,
        package_manager_licenses: Any | None = None,
        copyrights: Any | None = None,
        declared_code_licenses: Any | None = None,
        license_text: Any | None = None,
        all_licenses: Any | None = None,
        project_uuid: Any | None = None,
        version: Any | None = None,
        **kwargs: Any,
    ) -> PackageLicense: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _PackageVersionFacade(ResourceRuntimeFacade[PackageVersion]):
    """Package version with dependency information.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    Workflow flags: project-namespace-list.
    """

    def create(
        self,
        payload: CreatePackageVersionPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        project_uuid: Any,
        source_code_reference: Any | None = None,
        release_timestamp: Any | None = None,
        unresolved_dependencies: Any | None = None,
        resolved_dependencies: Any | None = None,
        resolution_errors: Any | None = None,
        language: Any | None = None,
        relative_path: Any | None = None,
        container_metadata: Any | None = None,
        bazel_metadata: Any | None = None,
        code_owners: Any | None = None,
        call_graph_available: Any | None = None,
        precomputed_call_graph_state: Any | None = None,
        **kwargs: Any,
    ) -> PackageVersion: ...
    def list_by_project(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _PolicyFacade(ResourceRuntimeFacade[Policy]):
    """Rule controlling scan behavior, findings, and workflows.

    Identity kwargs: name (-> meta.name), policy_type (-> spec.policy_type).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreatePolicyPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        policy_type: Any,
        rule: Any | None = None,
        project_selector: dict[str, Any] | None = None,
        project_exceptions: dict[str, Any] | None = None,
        resource_kinds: Any | None = None,
        disable: Any | None = None,
        query_statements: dict[str, Any] | None = None,
        template_uuid: Any | None = None,
        template_values: dict[str, Any] | None = None,
        template_version: Any | None = None,
        template_parameters: dict[str, Any] | None = None,
        finding_level: Any | None = None,
        group_by_fields: Any | None = None,
        finding_categories: Any | None = None,
        admission: Any | None = None,
        finding: Any | None = None,
        notification: Any | None = None,
        exception: Any | None = None,
        **kwargs: Any,
    ) -> Policy: ...

class _PolicyTemplateFacade(ListableFacade[PolicyTemplate]):
    """Reusable template for creating policies."""

    def get(
        self,
        id_or_resource: str | PolicyTemplate,
        namespace: str | None = ...,
    ) -> PolicyTemplate: ...

class _ProjectFacade(ResourceRuntimeFacade[Project]):
    """Logical root for a repository and its scan results.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateProjectPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        platform_source: Any,
        git: Any | None = None,
        unsupported: Any | None = None,
        sbom: Any | None = None,
        model: Any | None = None,
        toolchain_profile_uuid: Any | None = None,
        scan_profile_uuid: Any | None = None,
        is_archived: Any | None = None,
        **kwargs: Any,
    ) -> Project: ...

class _QueryFacade(ResourceRuntimeFacade[Query]):
    """Consumer facade model for Query (generated wire shape).

    Create mode: payload-only.
    """

    pass

class _QueryMalwareFacade(ResourceRuntimeFacade[QueryMalware]):
    """Advanced malware query endpoint.

    OSS-scoped (namespace fixed to 'oss').
    Create mode: both.
    """

    def create(
        self,
        payload: CreateQueryMalwarePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        package_version_name: Any | None = None,
        package_version_names: Any | None = None,
        purls: Any | None = None,
        mask: Any | None = None,
        **kwargs: Any,
    ) -> QueryMalware: ...

class _QuerySimilarPackagesFacade(ResourceRuntimeFacade[QuerySimilarPackages]):
    """Consumer facade model for QuerySimilarPackages (generated wire shape).

    Create mode: payload-only.
    """

    pass

class _QueryVulnerabilityFacade(ResourceRuntimeFacade[QueryVulnerability]):
    """Advanced vulnerability query endpoint.

    OSS-scoped (namespace fixed to 'oss').
    Create mode: both.
    """

    def create(
        self,
        payload: CreateQueryVulnerabilityPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        package_version_name: Any | None = None,
        package_version_names: Any | None = None,
        vulnerability_name_query: Any | None = None,
        purls: Any | None = None,
        mask: Any | None = None,
        vulnerability_type: Any | None = None,
        **kwargs: Any,
    ) -> QueryVulnerability: ...

class _RepositoryFacade(ResourceRuntimeFacade[Repository]):
    """Source control repository metadata.

    Identity kwargs:
      git_url (-> spec.vcs_url)
      name (-> meta.name)
      vcs_url (-> spec.vcs_url)
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateRepositoryPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        platform_source: Any,
        http_clone_url: Any,
        default_branch: Any,
        external_id: Any | None = None,
        owner: Any | None = None,
        create_time: Any | None = None,
        update_time: Any | None = None,
        contributors: Any | None = None,
        commit_hashes: Any | None = None,
        languages: Any | None = None,
        tags: Any | None = None,
        branch_protections: Any | None = None,
        vulnerability_alerts_enabled: Any | None = None,
        org: Any | None = None,
        repository_license: Any | None = None,
        **kwargs: Any,
    ) -> Repository: ...

class _RepositoryVersionFacade(ResourceRuntimeFacade[RepositoryVersion]):
    """Versioned snapshot of a repository.

    Identity kwargs: name (-> meta.name).
    Supports list(parent=<project>).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateRepositoryVersionPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        version: Any | None = None,
        last_commit_date: Any | None = None,
        **kwargs: Any,
    ) -> RepositoryVersion: ...
    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _SavedQueryFacade(ListableFacade[SavedQuery]):
    """Consumer facade model for SavedQuery (generated wire shape)."""

    def get(
        self,
        id_or_resource: str | SavedQuery,
        namespace: str | None = ...,
    ) -> SavedQuery: ...

class _ScanLogRequestFacade(ResourceRuntimeFacade[ScanLogRequest]):
    """Request for scan log messages.

    Create mode: payload-only.
    Workflow flags: request-style-endpoint.
    """

    pass

class _ScanProfileFacade(ResourceRuntimeFacade[ScanProfile]):
    """Scan configuration applied across projects.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateScanProfilePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        toolchain_profile: Any | None = None,
        automated_scan_parameters: Any | None = None,
        remediation_parameters: Any | None = None,
        is_default: Any | None = None,
        security_review_scanner_parameters: Any | None = None,
        exporter_parameters: Any | None = None,
        ai_sast_analysis_parameters: Any | None = None,
        **kwargs: Any,
    ) -> ScanProfile: ...

class _ScanResultFacade(ResourceRuntimeFacade[ScanResult]):
    """Results from an endorctl scan.

    Identity kwargs: name (-> meta.name).
    Supports list(parent=<project>).
    Create mode: both.
    Update mode: update_mask required.
    Workflow flags: project-namespace-list.
    """

    def create(
        self,
        payload: CreateScanResultPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        status: Any,
        type: Any,
        errors: Any | None = None,
        warnings: Any | None = None,
        infos: Any | None = None,
        start_time: Any | None = None,
        end_time: Any | None = None,
        stats: Any | None = None,
        refs: Any | None = None,
        environment: Any | None = None,
        has_panic: Any | None = None,
        exit_code: Any | None = None,
        logs: Any | None = None,
        policies_triggered: Any | None = None,
        warning_findings: Any | None = None,
        blocking_findings: Any | None = None,
        runtimes: Any | None = None,
        all_findings: Any | None = None,
        deleted_findings: Any | None = None,
        languages_detected: Any | None = None,
        exception_findings: Any | None = None,
        findings: Any | None = None,
        provisioning_result_uuid: Any | None = None,
        versions: Any | None = None,
        ecosystem_pkg_counts: Any | None = None,
        ecosystem_dep_counts: Any | None = None,
        components_executed: Any | None = None,
        deleted_package_versions: Any | None = None,
        provisioning_result: Any | None = None,
        **kwargs: Any,
    ) -> ScanResult: ...
    def list_by_project(self, *args: Any, **kwargs: Any) -> Any: ...

class _ScanWorkflowFacade(ResourceRuntimeFacade[ScanWorkflow]):
    """Workflow orchestrating scan steps."""

    pass

class _ScanWorkflowResultFacade(ResourceRuntimeFacade[ScanWorkflowResult]):
    """Result from a scan workflow execution."""

    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _SemgrepRuleFacade(ResourceRuntimeFacade[SemgrepRule]):
    """Custom SAST rule in Semgrep/OpenGrep format.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def create(
        self,
        payload: CreateSemgrepRulePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        rule: Any | None = None,
        disabled: Any | None = None,
        yaml: Any | None = None,
        **kwargs: Any,
    ) -> SemgrepRule: ...

class _VectorStoreFacade(ListableFacade[VectorStore]):
    """Tenant vector store inventory (embeddings index metadata).

    Identity kwargs: name (-> meta.name).
    """

    def get(
        self,
        id_or_resource: str | VectorStore,
        namespace: str | None = ...,
    ) -> VectorStore: ...

class _VectorStoreQueryFacade(ResourceRuntimeFacade[VectorStoreQuery]):
    """Natural-language query against a vector store (create-only).

    Create mode: both.
    """

    def create(
        self,
        payload: CreateVectorStoreQueryPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        vector_store_uuid: Any,
        query: Any,
        metadata_filter: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> VectorStoreQuery: ...

class _VersionUpgradeFacade(ResourceRuntimeFacade[VersionUpgrade]):
    """Suggested dependency version upgrade."""

    def list_for_context(self, *args: Any, **kwargs: Any) -> Any: ...

class _VulnerabilityFacade(ListableFacade[Vulnerability]):
    """Open-source vulnerability records.

    Identity kwargs: name (-> meta.name).
    OSS-scoped (namespace fixed to 'oss').
    """

    def get(
        self,
        id_or_resource: str | Vulnerability,
        namespace: str | None = ...,
    ) -> Vulnerability: ...

class Client:
    """Resource-oriented client with typed facades.

    Resources:
    APIKey, AuditLog, AuthenticationLog, AuthorizationPolicy, CodeOwners,
    DependencyMetadata, EndorLicense, Finding, FindingLog, IdentityProvider,
    Installation, Invitation, LinterResult, Malware, Metric, Namespace,
    NotificationTarget, PRCommentConfig, PackageFirewallLog, PackageLicense,
    PackageVersion, Policy, PolicyTemplate, Project, Query, QueryMalware,
    QuerySimilarPackages, QueryVulnerability, Repository, RepositoryVersion,
    SavedQuery, ScanLogRequest, ScanProfile, ScanResult, ScanWorkflow,
    ScanWorkflowResult, SemgrepRule, VectorStore, VectorStoreQuery,
    VersionUpgrade, Vulnerability
    Custom: CallGraphData
    """

    APIKey: _APIKeyFacade
    """API key for programmatic access."""
    AuditLog: _AuditLogFacade
    """Audit trail of API operations."""
    AuthenticationLog: _AuthenticationLogFacade
    """Authentication event log."""
    AuthorizationPolicy: _AuthorizationPolicyFacade
    """Permission grant for an authenticated identity."""
    CodeOwners: _CodeOwnersFacade
    """Code ownership assignments for a project."""
    DependencyMetadata: _DependencyMetadataFacade
    """Dependency relationship between packages."""
    EndorLicense: _EndorLicenseFacade
    """Platform license assigned to a tenant."""
    Finding: _FindingFacade
    """Security or compliance finding from a scan."""
    FindingLog: _FindingLogFacade
    """Historical snapshot of a finding state."""
    IdentityProvider: _IdentityProviderFacade
    """Consumer facade model for IdentityProvider (generated wire shape)."""
    Installation: _InstallationFacade
    """SCM platform integration (GitHub, GitLab, Azure, Bitbucket)."""
    Invitation: _InvitationFacade
    """User invitation for platform access."""
    LinterResult: _LinterResultFacade
    """Linter analysis result for a package or repository version."""
    Malware: _MalwareFacade
    """Open-source malware records."""
    Metric: _MetricFacade
    """Analytics output attached to packages or repositories."""
    Namespace: _NamespaceFacade
    """Isolate and organize resources in a parent-child hierarchy."""
    NotificationTarget: _NotificationTargetFacade
    """Integration endpoint for notification delivery."""
    PRCommentConfig: _PRCommentConfigFacade
    """Consumer facade model for PRCommentConfig (generated wire shape)."""
    PackageFirewallLog: _PackageFirewallLogFacade
    """Package firewall audit event recording action and trigger reason."""
    PackageLicense: _PackageLicenseFacade
    """License information for a package."""
    PackageVersion: _PackageVersionFacade
    """Package version with dependency information."""
    Policy: _PolicyFacade
    """Rule controlling scan behavior, findings, and workflows."""
    PolicyTemplate: _PolicyTemplateFacade
    """Reusable template for creating policies."""
    Project: _ProjectFacade
    """Logical root for a repository and its scan results."""
    Query: _QueryFacade
    """Consumer facade model for Query (generated wire shape)."""
    QueryMalware: _QueryMalwareFacade
    """Advanced malware query endpoint."""
    QuerySimilarPackages: _QuerySimilarPackagesFacade
    """Consumer facade model for QuerySimilarPackages (generated wire shape)."""
    QueryVulnerability: _QueryVulnerabilityFacade
    """Advanced vulnerability query endpoint."""
    Repository: _RepositoryFacade
    """Source control repository metadata."""
    RepositoryVersion: _RepositoryVersionFacade
    """Versioned snapshot of a repository."""
    SavedQuery: _SavedQueryFacade
    """Consumer facade model for SavedQuery (generated wire shape)."""
    ScanLogRequest: _ScanLogRequestFacade
    """Request for scan log messages."""
    ScanProfile: _ScanProfileFacade
    """Scan configuration applied across projects."""
    ScanResult: _ScanResultFacade
    """Results from an endorctl scan."""
    ScanWorkflow: _ScanWorkflowFacade
    """Workflow orchestrating scan steps."""
    ScanWorkflowResult: _ScanWorkflowResultFacade
    """Result from a scan workflow execution."""
    SemgrepRule: _SemgrepRuleFacade
    """Custom SAST rule in Semgrep/OpenGrep format."""
    VectorStore: _VectorStoreFacade
    """Tenant vector store inventory (embeddings index metadata)."""
    VectorStoreQuery: _VectorStoreQueryFacade
    """Natural-language query against a vector store (create-only)."""
    VersionUpgrade: _VersionUpgradeFacade
    """Suggested dependency version upgrade."""
    Vulnerability: _VulnerabilityFacade
    """Open-source vulnerability records."""
    CallGraphData: CallGraphDataFacade
    """Call graph data facade. Use decode() or fetch() with a PackageVersion."""

    _client: APIClient | None

    def __init__(
        self,
        api_client: APIClient | None = ...,
        tenant: str | None = ...,
        *,
        timeout: float = ...,
        content_type: str = ...,
        accept_encoding: str | None = ...,
        max_retries: int = ...,
        base_url: str | None = ...,
        **client_kwargs: Any,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> None: ...
    def whoami(self) -> str | None:
        """Return the authenticated identity name, or None."""
        ...
    def wait_until(
        self,
        predicate: Any,
        timeout: float = ...,
        poll_interval_max: float = ...,
    ) -> bool: ...
