# Generated by devtools/codegen/generate_client_stub.py — do not edit by hand.
# pyright: reportImplicitOverride=false
# ruff: noqa: D205
# Source of truth: endorlabs.registry.RESOURCE_REGISTRY and CUSTOM_FACADE_REGISTRY.

from collections.abc import Callable
from typing import Any

from .api_client import APIClient
from .core.filter import FilterExpression
from .core.types import ListParameters
from .core.whoami import WhoamiResult
from .facade import (
    CallGraphDataFacade,
    ListableFacade,
    QueryFacade,
    ResourceRuntimeFacade,
)
from .facade.specialized import (
    AuthorizationPolicyFacade,
    FindingFacade,
    PackageVersionFacade,
    ProjectFacade,
    ScanResultFacade,
    VectorStoreFacade,
    VulnerabilityFacade,
)
from .operations.routes import RouteResult
from .resources.api_key import APIKey, CreateAPIKeyPayload
from .resources.audit_log import AuditLog
from .resources.authentication_log import AuthenticationLog
from .resources.authorization_policy import (
    AuthorizationPolicy,
    CreateAuthorizationPolicyPayload,
)
from .resources.code_owners import CodeOwners, CreateCodeOwnersPayload
from .resources.dependency_metadata import (
    CreateDependencyMetadataPayload,
    DependencyMetadata,
)
from .resources.endor_license import EndorLicense
from .resources.finding import Finding
from .resources.finding_log import FindingLog
from .resources.identity_provider import IdentityProvider
from .resources.installation import CreateInstallationPayload, Installation
from .resources.invitation import CreateInvitationPayload, Invitation
from .resources.linter_result import LinterResult
from .resources.malware import Malware
from .resources.malware_exposure import MalwareExposure
from .resources.malware_exposure_query import (
    CreateMalwareExposureQueryPayload,
    MalwareExposureQuery,
)
from .resources.metric import Metric
from .resources.namespace import CreateNamespacePayload, Namespace
from .resources.notification_target import (
    CreateNotificationTargetPayload,
    NotificationTarget,
)
from .resources.package_firewall_log import PackageFirewallLog
from .resources.package_license import CreatePackageLicensePayload, PackageLicense
from .resources.package_manager import CreatePackageManagerPayload, PackageManager
from .resources.package_version import PackageVersion
from .resources.policy import CreatePolicyPayload, Policy
from .resources.policy_template import PolicyTemplate
from .resources.pr_comment_config import CreatePRCommentConfigPayload, PRCommentConfig
from .resources.project import CreateProjectPayload, Project
from .resources.query_malware import CreateQueryMalwarePayload, QueryMalware
from .resources.query_similar_packages import QuerySimilarPackages
from .resources.query_vulnerability import (
    CreateQueryVulnerabilityPayload,
    QueryVulnerability,
)
from .resources.repository import Repository
from .resources.repository_version import RepositoryVersion
from .resources.saved_query import SavedQuery
from .resources.scan_log_request import ScanLogRequest
from .resources.scan_profile import CreateScanProfilePayload, ScanProfile
from .resources.scan_result import ScanResult
from .resources.scan_workflow import ScanWorkflow
from .resources.scan_workflow_result import ScanWorkflowResult
from .resources.semgrep_rule import CreateSemgrepRulePayload, SemgrepRule
from .resources.system_config import SystemConfig
from .resources.vector_store import VectorStore
from .resources.vector_store_query import (
    CreateVectorStoreQueryPayload,
    VectorStoreQuery,
)
from .resources.version_upgrade import VersionUpgrade
from .resources.vulnerability import Vulnerability

class _APIKeyFacade(ResourceRuntimeFacade[APIKey]):
    """API key for programmatic access.

    Create mode: both.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[APIKey] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateAPIKeyPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        permissions: dict[str, Any],
        expiration_time: Any,
        **kwargs: Any,
    ) -> APIKey: ...

class _AuditLogFacade(ListableFacade[AuditLog]):
    """Audit trail of API operations."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[AuditLog] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | AuditLog,
        namespace: str | None = ...,
    ) -> AuditLog: ...

class _AuthenticationLogFacade(ListableFacade[AuthenticationLog]):
    """Authentication event log."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[AuthenticationLog] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | AuthenticationLog,
        namespace: str | None = ...,
    ) -> AuthenticationLog: ...

class _AuthorizationPolicyFacade(AuthorizationPolicyFacade):
    """Permission grant for an authenticated identity.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[AuthorizationPolicy] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def search_by_claims(
        self,
        query: str,
        *,
        namespace: str | None = ...,
        traverse: bool = ...,
        warnings_out: list[str] | None = ...,
        **list_kwargs: Any,
    ) -> list[Any]:
        """Search policies by name, clause text, and target namespace fields."""
        ...

    def create(
        self,
        payload: CreateAuthorizationPolicyPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        clause: Any,
        target_namespaces: Any,
        propagate: Any,
        permissions: dict[str, Any],
        expiration_time: Any | None = None,
        **kwargs: Any,
    ) -> AuthorizationPolicy: ...

class _CodeOwnersFacade(ResourceRuntimeFacade[CodeOwners]):
    """Code ownership assignments for a project.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[CodeOwners] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateCodeOwnersPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        patterns: dict[str, Any] | None = None,
        version: Any | None = None,
        file_hash: Any | None = None,
        **kwargs: Any,
    ) -> CodeOwners: ...

class _DependencyMetadataFacade(ResourceRuntimeFacade[DependencyMetadata]):
    """Dependency relationship between packages.

    Create mode: both.
    Workflow flags: project-namespace-list.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[DependencyMetadata] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateDependencyMetadataPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        dependency_data: Any | None = None,
        importer_data: Any | None = None,
        **kwargs: Any,
    ) -> DependencyMetadata: ...

class _EndorLicenseFacade(ListableFacade[EndorLicense]):
    """Platform license assigned to a tenant."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[EndorLicense] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | EndorLicense,
        namespace: str | None = ...,
    ) -> EndorLicense: ...

class _FindingFacade(FindingFacade):
    """Security or compliance finding from a scan.

    Identity kwargs: name (-> meta.name).
    Update mode: update_mask required.
    Workflow flags: project-namespace-list.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Finding] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def list_by_project(
        self,
        project: Any,
        *,
        filter: str | FilterExpression | None = ...,
        **kwargs: Any,
    ) -> list[Any]:
        """List findings for a project (generated accessor ``project.findings``)."""
        ...

    def list_for_context(
        self,
        source: Any,
        *,
        filter: str | FilterExpression | None = ...,
        namespace: str | None = ...,
        **kwargs: Any,
    ) -> list[Any]:
        """List findings in the same scan plane as *source* (``scan.findings``)."""
        ...

    def to_dependency_metadata(
        self,
        finding: Any,
        **kwargs: Any,
    ) -> RouteResult[Any]:
        """Resolve DependencyMetadata for a finding (accessors with fallback)."""
        ...

class _FindingLogFacade(ListableFacade[FindingLog]):
    """Historical snapshot of a finding state."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[FindingLog] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | FindingLog,
        namespace: str | None = ...,
    ) -> FindingLog: ...

class _IdentityProviderFacade(ListableFacade[IdentityProvider]):
    """SSO identity provider configuration for the tenant."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[IdentityProvider] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | IdentityProvider,
        namespace: str | None = ...,
    ) -> IdentityProvider: ...

class _InstallationFacade(ResourceRuntimeFacade[Installation]):
    """SCM platform integration (GitHub, GitLab, Azure, Bitbucket).

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Installation] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateInstallationPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        public: Any | None = None,
        external_id: Any | None = None,
        suspended: Any | None = None,
        project_uuids: Any | None = None,
        login: Any | None = None,
        invalid: Any | None = None,
        enabled_features: Any | None = None,
        platform_source: Any | None = None,
        platform_type: Any | None = None,
        github_config: Any | None = None,
        azure_config: Any | None = None,
        gitlab_config: Any | None = None,
        bitbucket_config: Any | None = None,
        huggingface_config: Any | None = None,
        marked_for_deletion: Any | None = None,
        include_archived_repos: Any | None = None,
        installation_error_message: Any | None = None,
        scm_app_uuid: Any | None = None,
        cleanup_stale_namespaces: Any | None = None,
        exclude_project_regexes: Any | None = None,
        **kwargs: Any,
    ) -> Installation: ...

class _InvitationFacade(ResourceRuntimeFacade[Invitation]):
    """User invitation for platform access.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Invitation] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateInvitationPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        user_email: Any,
        **kwargs: Any,
    ) -> Invitation: ...

class _LinterResultFacade(ListableFacade[LinterResult]):
    """Linter analysis result for a package or repository version."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[LinterResult] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | LinterResult,
        namespace: str | None = ...,
    ) -> LinterResult: ...

class _MalwareFacade(ListableFacade[Malware]):
    """Open-source malware records.

    Identity kwargs: name (-> meta.name).
    OSS-scoped (namespace fixed to 'oss').
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Malware] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | Malware,
        namespace: str | None = ...,
    ) -> Malware: ...

class _MalwareExposureFacade(ListableFacade[MalwareExposure]):
    """Tenant-scoped malware blast-radius / exposure records."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[MalwareExposure] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | MalwareExposure,
        namespace: str | None = ...,
    ) -> MalwareExposure: ...

class _MalwareExposureQueryFacade(ResourceRuntimeFacade[MalwareExposureQuery]):
    """Query tenant malware exposure by malware UUID or filter.

    Create mode: both.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[MalwareExposureQuery] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateMalwareExposureQueryPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        malware_uuids: Any | None = None,
        filter: Any | None = None,
        traverse: Any | None = None,
        project_uuid: Any | None = None,
        **kwargs: Any,
    ) -> MalwareExposureQuery: ...

class _MetricFacade(ListableFacade[Metric]):
    """Analytics output attached to packages or repositories.

    Identity kwargs: name (-> meta.name).
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Metric] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | Metric,
        namespace: str | None = ...,
    ) -> Metric: ...

class _NamespaceFacade(ResourceRuntimeFacade[Namespace]):
    """Isolate and organize resources in a parent-child hierarchy.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Namespace] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateNamespacePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        managed: Any | None = None,
        **kwargs: Any,
    ) -> Namespace: ...

class _NotificationTargetFacade(ResourceRuntimeFacade[NotificationTarget]):
    """Integration endpoint for notification delivery.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[NotificationTarget] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateNotificationTargetPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        action: Any,
        custom_template: Any | None = None,
        **kwargs: Any,
    ) -> NotificationTarget: ...

class _PRCommentConfigFacade(ResourceRuntimeFacade[PRCommentConfig]):
    """Pull-request comment integration settings.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[PRCommentConfig] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreatePRCommentConfigPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        template: Any,
        platform_type: Any | None = None,
        **kwargs: Any,
    ) -> PRCommentConfig: ...

class _PackageFirewallLogFacade(ListableFacade[PackageFirewallLog]):
    """Package firewall audit event recording action and trigger reason."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[PackageFirewallLog] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | PackageFirewallLog,
        namespace: str | None = ...,
    ) -> PackageFirewallLog: ...

class _PackageLicenseFacade(ResourceRuntimeFacade[PackageLicense]):
    """License information for a package.

    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[PackageLicense] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreatePackageLicensePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        code_licenses: Any | None = None,
        package_manager_licenses: Any | None = None,
        copyrights: Any | None = None,
        declared_code_licenses: Any | None = None,
        license_text: Any | None = None,
        all_licenses: Any | None = None,
        project_uuid: Any | None = None,
        version: Any | None = None,
        **kwargs: Any,
    ) -> PackageLicense: ...

class _PackageManagerFacade(ResourceRuntimeFacade[PackageManager]):
    """Package manager integration and resolution settings.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[PackageManager] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreatePackageManagerPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        auth_provider: Any | None = None,
        npm: Any | None = None,
        mvn: Any | None = None,
        cargo: Any | None = None,
        pypi: Any | None = None,
        gem: Any | None = None,
        nuget: Any | None = None,
        packagist: Any | None = None,
        gradle: Any | None = None,
        cocoapod: Any | None = None,
        swift: Any | None = None,
        conan: Any | None = None,
        package_manager_status: Any | None = None,
        **kwargs: Any,
    ) -> PackageManager: ...

class _PackageVersionFacade(PackageVersionFacade):
    """Package version with dependency information.

    Identity kwargs: name (-> meta.name).
    Update mode: update_mask required.
    Workflow flags: project-namespace-list.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[PackageVersion] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def list_by_project(
        self,
        project: Any,
        *,
        filter: str | FilterExpression | None = ...,
        **kwargs: Any,
    ) -> list[Any]:
        """List package versions for a project (``project.package_versions``)."""
        ...

    def list_for_context(
        self,
        source: Any,
        *,
        filter: str | FilterExpression | None = ...,
        namespace: str | None = ...,
        **kwargs: Any,
    ) -> list[Any]:
        """List package versions in the same scan plane as *source*."""
        ...

class _PolicyFacade(ResourceRuntimeFacade[Policy]):
    """Rule controlling scan behavior, findings, and workflows.

    Identity kwargs: name (-> meta.name), policy_type (-> spec.policy_type).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Policy] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreatePolicyPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        policy_type: Any,
        rule: Any | None = None,
        project_selector: dict[str, Any] | None = None,
        project_exceptions: dict[str, Any] | None = None,
        resource_kinds: Any | None = None,
        disable: Any | None = None,
        query_statements: dict[str, Any] | None = None,
        template_uuid: Any | None = None,
        template_values: dict[str, Any] | None = None,
        template_version: Any | None = None,
        template_parameters: dict[str, Any] | None = None,
        finding_level: Any | None = None,
        group_by_fields: Any | None = None,
        finding_categories: Any | None = None,
        admission: Any | None = None,
        finding: Any | None = None,
        notification: Any | None = None,
        exception: Any | None = None,
        **kwargs: Any,
    ) -> Policy: ...

class _PolicyTemplateFacade(ListableFacade[PolicyTemplate]):
    """Reusable template for creating policies."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[PolicyTemplate] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | PolicyTemplate,
        namespace: str | None = ...,
    ) -> PolicyTemplate: ...

class _ProjectFacade(ProjectFacade):
    """Logical root for a repository and its scan results.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Project] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def is_app(
        self,
        project: Any,
    ) -> bool:
        """Return whether *project* was registered via an SCM app installation."""
        ...

    def is_cli(
        self,
        project: Any,
    ) -> bool:
        """Return whether *project* was registered for CLI scanning (no app id)."""
        ...

    def is_sbom(
        self,
        project: Any,
    ) -> bool:
        """Return whether *project* is an SBOM import row (``spec.sbom`` set)."""
        ...

    def search_by_name(
        self,
        query: str,
        *,
        namespace: str | None = ...,
        traverse: bool = ...,
        warnings_out: list[str] | None = ...,
        **list_kwargs: Any,
    ) -> list[Any]:
        """Search projects by case-insensitive substring on ``meta.name`` or UUID."""
        ...

    def create(
        self,
        payload: CreateProjectPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        platform_source: Any,
        git: Any | None = None,
        unsupported: Any | None = None,
        sbom: Any | None = None,
        model: Any | None = None,
        toolchain_profile_uuid: Any | None = None,
        scan_profile_uuid: Any | None = None,
        is_archived: Any | None = None,
        **kwargs: Any,
    ) -> Project: ...

class _QueryMalwareFacade(ResourceRuntimeFacade[QueryMalware]):
    """Advanced malware query endpoint.

    OSS-scoped (namespace fixed to 'oss').
    Create mode: both.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[QueryMalware] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateQueryMalwarePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        package_version_name: Any | None = None,
        package_version_names: Any | None = None,
        package_names: Any | None = None,
        purls: Any | None = None,
        mask: Any | None = None,
        **kwargs: Any,
    ) -> QueryMalware: ...

class _QuerySimilarPackagesFacade(ResourceRuntimeFacade[QuerySimilarPackages]):
    """Similar-package query (create-only).

    Create mode: payload-only.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[QuerySimilarPackages] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _QueryVulnerabilityFacade(ResourceRuntimeFacade[QueryVulnerability]):
    """Advanced vulnerability query endpoint.

    OSS-scoped (namespace fixed to 'oss').
    Create mode: both.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[QueryVulnerability] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateQueryVulnerabilityPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        package_version_name: Any | None = None,
        package_version_names: Any | None = None,
        vulnerability_name_query: Any | None = None,
        purls: Any | None = None,
        mask: Any | None = None,
        vulnerability_type: Any | None = None,
        **kwargs: Any,
    ) -> QueryVulnerability: ...

class _RepositoryFacade(ResourceRuntimeFacade[Repository]):
    """Source control repository metadata.

    Identity kwargs:
      git_url (-> spec.vcs_url)
      name (-> meta.name)
      vcs_url (-> spec.vcs_url)
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Repository] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _RepositoryVersionFacade(ResourceRuntimeFacade[RepositoryVersion]):
    """Versioned snapshot of a repository.

    Identity kwargs: name (-> meta.name).
    Supports list(parent=<project>).
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[RepositoryVersion] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _SavedQueryFacade(ListableFacade[SavedQuery]):
    """Saved query definition for reuse in the product UI."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[SavedQuery] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get(
        self,
        id_or_resource: str | SavedQuery,
        namespace: str | None = ...,
    ) -> SavedQuery: ...

class _ScanLogRequestFacade(ResourceRuntimeFacade[ScanLogRequest]):
    """Request for scan log messages.

    Create mode: payload-only.
    Workflow flags: request-style-endpoint.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[ScanLogRequest] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _ScanProfileFacade(ResourceRuntimeFacade[ScanProfile]):
    """Scan configuration applied across projects.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[ScanProfile] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateScanProfilePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        toolchain_profile: Any | None = None,
        automated_scan_parameters: Any | None = None,
        remediation_parameters: Any | None = None,
        is_default: Any | None = None,
        security_review_scanner_parameters: Any | None = None,
        exporter_parameters: Any | None = None,
        ai_sast_analysis_parameters: Any | None = None,
        **kwargs: Any,
    ) -> ScanProfile: ...

class _ScanResultFacade(ScanResultFacade):
    """Results from an endorctl scan.

    Identity kwargs: name (-> meta.name).
    Supports list(parent=<project>).
    Update mode: update_mask required.
    Workflow flags: project-namespace-list.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[ScanResult] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def get_logs(
        self,
        scan_result: Any,
        *,
        namespace: str | None = ...,
        max_entries: int = ...,
        log_levels: list[Any] | None = ...,
        start_time: str | None = ...,
        end_time: str | None = ...,
        newest_first: bool | None = ...,
    ) -> list[Any]:
        """Fetch log messages for a scan (ScanLogRequest API under the hood)."""
        ...

    def list_by_project(
        self,
        project: Any,
        *,
        namespace: str | None = ...,
        limit: int = ...,
        status_filter: str | None = ...,
        **kwargs: Any,
    ) -> list[Any]:
        """List scan results for a project (accessor ``project.scan_results``)."""
        ...

class _ScanWorkflowFacade(ResourceRuntimeFacade[ScanWorkflow]):
    """Workflow orchestrating scan steps."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[ScanWorkflow] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _ScanWorkflowResultFacade(ResourceRuntimeFacade[ScanWorkflowResult]):
    """Result from a scan workflow execution."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[ScanWorkflowResult] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _SemgrepRuleFacade(ResourceRuntimeFacade[SemgrepRule]):
    """Custom SAST rule in Semgrep/OpenGrep format.

    Identity kwargs: name (-> meta.name).
    Create mode: both.
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[SemgrepRule] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateSemgrepRulePayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        rule: Any | None = None,
        disabled: Any | None = None,
        yaml: Any | None = None,
        **kwargs: Any,
    ) -> SemgrepRule: ...

class _SystemConfigFacade(ResourceRuntimeFacade[SystemConfig]):
    """Tenant-wide system settings singleton (list/update; onboard-seeded).

    Identity kwargs: name (-> meta.name).
    Update mode: update_mask required.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[SystemConfig] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _VectorStoreFacade(VectorStoreFacade):
    """Tenant vector store inventory (embeddings index metadata).

    Identity kwargs: name (-> meta.name).
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[VectorStore] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def search_by_name(
        self,
        query: str,
        *,
        namespace: str | None = ...,
        traverse: bool = ...,
        warnings_out: list[str] | None = ...,
        **list_kwargs: Any,
    ) -> list[Any]:
        """Search vector stores by case-insensitive substring on ``meta.name``."""
        ...

class _VectorStoreQueryFacade(ResourceRuntimeFacade[VectorStoreQuery]):
    """Natural-language query against a vector store (create-only).

    Create mode: both.
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[VectorStoreQuery] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def create(
        self,
        payload: CreateVectorStoreQueryPayload | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        namespace_uuid: str | None = None,
        namespace: str | None = None,
        vector_store_uuid: Any,
        query: Any,
        metadata_filter: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> VectorStoreQuery: ...

class _VersionUpgradeFacade(ResourceRuntimeFacade[VersionUpgrade]):
    """Suggested dependency version upgrade."""

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[VersionUpgrade] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

class _VulnerabilityFacade(VulnerabilityFacade):
    """Open-source vulnerability records.

    Identity kwargs: name (-> meta.name).
    OSS-scoped (namespace fixed to 'oss').
    """

    def list(
        self,
        traverse: bool = ...,
        concurrent: bool = ...,
        max_workers: int = ...,
        namespace: str | None = ...,
        list_params: ListParameters | None = ...,
        max_pages: int | None = ...,
        parent: Any = ...,
        filter: str | FilterExpression | None = ...,
        mask: str | None = ...,
        page_size: int | None = ...,
        page_token: str | None = ...,
        page_id: str | None = ...,
        sort_by: str | None = ...,
        desc: bool | None = ...,
        count: bool | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        archive: bool | None = ...,
        pr_uuid: str | None = ...,
        ci_run_uuid: str | None = ...,
        **kwargs: Any,
    ) -> list[Vulnerability] | list[dict[str, Any]]:
        """List resources with full pagination and optional concurrent mode."""
        ...

    def search_by_vuln_alias(
        self,
        query: str,
        *,
        namespace: str | None = ...,
        traverse: bool = ...,
        warnings_out: list[str] | None = ...,
        **list_kwargs: Any,
    ) -> list[Any]:
        """Search OSS vulnerabilities by alias or name substring."""
        ...

class Client:
    """Resource-oriented client with typed facades.

    Resources:
    APIKey, AuditLog, AuthenticationLog, AuthorizationPolicy, CodeOwners,
    DependencyMetadata, EndorLicense, Finding, FindingLog, IdentityProvider,
    Installation, Invitation, LinterResult, Malware, MalwareExposure,
    MalwareExposureQuery, Metric, Namespace, NotificationTarget,
    PRCommentConfig, PackageFirewallLog, PackageLicense, PackageManager,
    PackageVersion, Policy, PolicyTemplate, Project, Query, QueryMalware,
    QuerySimilarPackages, QueryVulnerability, Repository, RepositoryVersion,
    SavedQuery, ScanLogRequest, ScanProfile, ScanResult, ScanWorkflow,
    ScanWorkflowResult, SemgrepRule, SystemConfig, VectorStore,
    VectorStoreQuery, VersionUpgrade, Vulnerability
    Custom: CallGraphData, Query
    """

    APIKey: _APIKeyFacade
    AuditLog: _AuditLogFacade
    AuthenticationLog: _AuthenticationLogFacade
    AuthorizationPolicy: _AuthorizationPolicyFacade
    CodeOwners: _CodeOwnersFacade
    DependencyMetadata: _DependencyMetadataFacade
    EndorLicense: _EndorLicenseFacade
    Finding: _FindingFacade
    FindingLog: _FindingLogFacade
    IdentityProvider: _IdentityProviderFacade
    Installation: _InstallationFacade
    Invitation: _InvitationFacade
    LinterResult: _LinterResultFacade
    Malware: _MalwareFacade
    MalwareExposure: _MalwareExposureFacade
    MalwareExposureQuery: _MalwareExposureQueryFacade
    Metric: _MetricFacade
    Namespace: _NamespaceFacade
    NotificationTarget: _NotificationTargetFacade
    PRCommentConfig: _PRCommentConfigFacade
    PackageFirewallLog: _PackageFirewallLogFacade
    PackageLicense: _PackageLicenseFacade
    PackageManager: _PackageManagerFacade
    PackageVersion: _PackageVersionFacade
    Policy: _PolicyFacade
    PolicyTemplate: _PolicyTemplateFacade
    Project: _ProjectFacade
    QueryMalware: _QueryMalwareFacade
    QuerySimilarPackages: _QuerySimilarPackagesFacade
    QueryVulnerability: _QueryVulnerabilityFacade
    Repository: _RepositoryFacade
    RepositoryVersion: _RepositoryVersionFacade
    SavedQuery: _SavedQueryFacade
    ScanLogRequest: _ScanLogRequestFacade
    ScanProfile: _ScanProfileFacade
    ScanResult: _ScanResultFacade
    ScanWorkflow: _ScanWorkflowFacade
    ScanWorkflowResult: _ScanWorkflowResultFacade
    SemgrepRule: _SemgrepRuleFacade
    SystemConfig: _SystemConfigFacade
    VectorStore: _VectorStoreFacade
    VectorStoreQuery: _VectorStoreQueryFacade
    VersionUpgrade: _VersionUpgradeFacade
    Vulnerability: _VulnerabilityFacade
    CallGraphData: CallGraphDataFacade
    Query: QueryFacade

    _client: APIClient | None

    def __init__(
        self,
        api_client: APIClient | None = ...,
        tenant: str | None = ...,
        *,
        timeout: float | None = ...,
        content_type: str = ...,
        accept_encoding: str | None = ...,
        max_retries: int | None = ...,
        base_url: str | None = ...,
        **client_kwargs: Any,
    ) -> None:
        """Resource-oriented client; holds default namespace and exposes resource
        facades.
        """
        ...
    def close(self) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> None: ...
    def whoami(self) -> WhoamiResult:
        """Return identity and optional bearer session metadata."""
        ...
    def wait_until(
        self,
        predicate: Callable[[], bool],
        timeout: float = ...,
        poll_interval_max: float = ...,
    ) -> bool:
        """Block until predicate returns True or timeout is exceeded."""
        ...
