"""Shared HTML chrome for executive report packet pages."""

from __future__ import annotations

import html
from importlib import resources


def tokens_css() -> str:
    """Return the shared design-token stylesheet."""
    root = resources.files("endorlabs.workflows.reports.export.html.shell")
    return (root / "tokens.css").read_text(encoding="utf-8")


def nav(
    active: str,
    *,
    include_sast: bool = True,
    include_patches: bool = True,
) -> str:
    """Packet page navigation strip; *active* is one of on/vs/sca/sast/pat.

    Omit SAST / Endor Patches links when those slices were not pulled
    (license entitlement or opt-in skip).
    """

    def cls(key: str) -> str:
        return ' class="active"' if key == active else ""

    sast = (
        f'\n  <a{cls("sast")} href="04-sast-burndown.html">SAST burndown</a>'
        if include_sast
        else ""
    )
    patches = (
        f'\n  <a{cls("pat")} href="05-endor-patches.html">Endor Patches</a>'
        if include_patches
        else ""
    )
    return f"""<div class="nav">
  <a{cls("on")} href="01-onboarding.html">Onboarding</a>
  <a{cls("vs")} href="02-version-sprawl.html">Version sprawl</a>
  <a{cls("sca")} href="03-sca-burndown.html">SCA burndown</a>{sast}{patches}
</div>"""


def header(
    *,
    title: str,
    purpose: str,
    tenant: str,
    pulled_at: str,
    nav_html: str,
    meta_extra: str | None = None,
) -> str:
    """Brand header → nav → h1 → purpose → meta."""
    pulled = (pulled_at or "")[:10]
    safe_tenant = html.escape(str(tenant))
    safe_title = html.escape(str(title))
    safe_purpose = html.escape(str(purpose))
    meta = f"Namespace <strong>{safe_tenant}</strong> · Data as of {pulled}"
    if meta_extra:
        meta = f"{meta} · {meta_extra}"
    return f"""<header class="site-header">
  <img class="brand-wordmark" src="assets/endor-wordmark.png" alt="Endor Labs"/>
  <span class="brand-tag">Executive report</span>
</header>
{nav_html}
<h1>{safe_title}</h1>
<p class="purpose">{safe_purpose}</p>
<p class="meta">{meta}</p>
"""


def footer() -> str:
    """Standard site footer (no schema echo)."""
    return """<footer class="site-footer">
  <img class="footer-mark" src="assets/endor-logo.png" alt="" width="28" height="28"/>
  <p class="footer-copy">Generated by the Endor Labs SDK · not the live product UI</p>
</footer>"""


def page(
    body: str,
    *,
    title: str,
    include_chart_js: bool = True,
    extra_css: str = "",
) -> str:
    """Wrap *body* in the shared HTML document shell.

    *body* should include the header/nav block and page content (not the footer).
    """
    chart = (
        '<script src="assets/chart.umd.min.js"></script>\n' if include_chart_js else ""
    )
    style = tokens_css()
    if extra_css:
        style = f"{style}\n{extra_css}"
    safe_title = html.escape(str(title))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{safe_title}</title>
{chart}<style>{style}</style>
</head>
<body>
<div class="wrap">
{body}
{footer()}
</div>
</body>
</html>
"""
