"""Executive-facing UI copy for report packet HTML (portable, generic)."""

from __future__ import annotations

H1_ONBOARDING = "Organization onboarding"
H1_VERSION_SPRAWL = "Dependency version sprawl"
H1_FINDINGS_BURNDOWN = "Vulnerability findings trend"

PURPOSE_ONBOARDING = (
    "How repositories were registered over time and across the namespace hierarchy."
)
PURPOSE_VERSION_SPRAWL = "How many distinct package versions are in use, and where version sprawl concentrates."
PURPOSE_FINDINGS_BURNDOWN = (
    "Weekly new versus resolved Critical/High reachable vulnerability events "
    "(FindingLog CREATE/DELETE), with main-context scan activity for context."
)

STAT_WINDOW_NET = "Window net (CREATE−DELETE)"
PENDING_TAG_CAPTION = "Trend charts not loaded for this tag yet; project and scan counts below still apply."
MAIN_THROUGHPUT_LABEL = "Main-context scans (activity proxy)"
TAG_HELP = "Project tags from Project.meta.tags"

GLOSSARY_HTML = """
<div class="glossary">
  <div class="glossary-title">How to read these metrics</div>
  <ul>
    <li><strong>Window net (CREATE−DELETE)</strong> is cumulative FindingLog creates
      minus deletes inside the lookback window only. It can be negative when older
      findings are resolved in-window. It is not an open Finding inventory count.</li>
    <li><strong>Project tags</strong> come from <code>Project.meta.tags</code>
      (organization labels). They are separate from finding reachability tags.</li>
    <li><strong>Main-context scans</strong> count ScanResult events with
      <code>CONTEXT_TYPE_MAIN</code> — a cadence proxy, not the number of main branches.</li>
  </ul>
</div>
"""

README_TEXT = """Endor Labs executive report packet
=================================

Open the HTML files in a browser (no Endor App login required for viewing).

Reports
-------
01-onboarding.html         Organization onboarding over time
02-version-sprawl.html     Dependency version sprawl
03-findings-burndown.html  Vulnerability findings trend (FindingLog)

Filters
-------
Namespace and Project tag controls appear at the top of each interactive report.
Project tags are discovered from Project.meta.tags for this tenant.

Metric notes
------------
- Window net (CREATE−DELETE): cumulative new minus resolved FindingLog events
  inside the lookback window. May be negative. Not open Finding inventory.
- Main-context scans: ScanResult events with CONTEXT_TYPE_MAIN (activity proxy).
- Tags marked "series pending" have project/scan counts but no FindingLog trend
  yet (cost-controlled pull; raise min-projects or wait for a fuller pull).

Generated by the Endor Labs SDK. This packet is not the live product UI.
"""
