"""Render executive report packet HTML from a cube dict."""

from __future__ import annotations

import json
import shutil
from collections.abc import Generator
from contextlib import contextmanager
from importlib import resources
from pathlib import Path
from typing import Any

from endorlabs.context.paths import sanitize_path_segment
from endorlabs.utils.path_safety import safe_write_text
from endorlabs.workflows.reports.schemas.packet_v0 import (
    REPORT_PACKET_SCHEMA,
    RUN_BUCKET,
)

from . import copy as copy_mod

_SHELL_ASSETS = (
    "endor-logo.png",
    "endor-wordmark.png",
    "chart.umd.min.js",
)


def _tokens_css() -> str:
    root = resources.files("endorlabs.workflows.reports.export.html.shell")
    return (root / "tokens.css").read_text(encoding="utf-8")


@contextmanager
def _shell_asset_path(name: str) -> Generator[Path]:
    root = resources.files("endorlabs.workflows.reports.export.html.shell")
    with resources.as_file(root / "assets" / name) as path:
        yield Path(path)


def _copy_shell_assets(out: Path) -> list[Path]:
    assets_dir = out / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name in _SHELL_ASSETS:
        dest = assets_dir / name
        with _shell_asset_path(name) as src:
            shutil.copyfile(src, dest)
        written.append(dest)
    return written


def _chart_helpers_js() -> str:
    return """function brandVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}
function chartTheme() {
  const muted = brandVar("--endor-muted");
  const grid = brandVar("--endor-border");
  return {
    muted,
    grid,
    accent: brandVar("--endor-accent"),
    ok: brandVar("--endor-ok"),
    warn: brandVar("--endor-warn"),
    danger: brandVar("--endor-danger"),
    neutral: brandVar("--endor-chart-neutral"),
    secondary: brandVar("--endor-chart-secondary"),
  };
}
function chartScales(theme) {
  return {
    x: { ticks: { color: theme.muted }, grid: { color: theme.grid } },
    y: { ticks: { color: theme.muted }, grid: { color: theme.grid } },
  };
}
"""


def _nav(active: str) -> str:
    def cls(key: str) -> str:
        return ' class="active"' if key == active else ""

    return f"""<div class="nav">
  <a{cls("on")} href="01-onboarding.html">Onboarding</a>
  <a{cls("vs")} href="02-version-sprawl.html">Version sprawl</a>
  <a{cls("fb")} href="03-findings-burndown.html">Findings trend</a>
</div>"""


def _header(
    *,
    title: str,
    purpose: str,
    tenant: str,
    pulled_at: str,
) -> str:
    pulled = (pulled_at or "")[:10]
    return f"""<header class="site-header">
  <img class="brand-wordmark" src="assets/endor-wordmark.png" alt="Endor Labs"/>
  <span class="brand-tag">Executive report</span>
</header>
<h1>{title}</h1>
<p class="purpose">{purpose}</p>
<p class="meta">Namespace <strong>{tenant}</strong> · Data as of {pulled} · Schema {REPORT_PACKET_SCHEMA}</p>
"""


def _footer() -> str:
    return f"""<footer class="site-footer">
  <img class="footer-mark" src="assets/endor-logo.png" alt="" width="28" height="28"/>
  <p class="footer-copy">Generated by the Endor Labs SDK · not the live product UI · {REPORT_PACKET_SCHEMA}</p>
</footer>"""


def _page(body: str, *, title: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title}</title>
<script src="assets/chart.umd.min.js"></script>
<style>{_tokens_css()}</style>
</head>
<body>
<div class="wrap">
{body}
{_footer()}
</div>
</body>
</html>
"""


def _render_onboarding(cube: dict[str, Any]) -> str:
    tenant = cube.get("tenant") or ""
    pulled = cube.get("pulledAt") or ""
    report = (cube.get("reports") or {}).get("onboarding") or {}
    payload = json.dumps(report, separators=(",", ":"))
    return _page(
        f"""{_nav("on")}
{_header(title=copy_mod.H1_ONBOARDING, purpose=copy_mod.PURPOSE_ONBOARDING, tenant=tenant, pulled_at=pulled)}
{copy_mod.GLOSSARY_HTML}
<div class="toggles">
  <label class="toggle"><input type="checkbox" id="once"/> Count each repository only once (earliest registration wins)</label>
  <span class="pill" id="modePill"></span>
</div>
<div class="stats" id="stats"></div>
<div class="card">
  <div class="card-h">Onboarding progress · cumulative</div>
  <p class="caption">Cumulative project registrations by ISO week (Monday UTC). Source: Project.meta.create_time.</p>
  <div class="chart-box"><canvas id="cumChart"></canvas></div>
</div>
<div class="card">
  <div class="card-h">New registrations per week</div>
  <p class="caption">Weekly new registrations under the active count mode.</p>
  <div class="chart-box sm"><canvas id="weekChart"></canvas></div>
</div>
<h2>Inclusive namespace hierarchy</h2>
<p class="caption">Each path includes projects in that namespace and its children.</p>
<table class="data" id="hierTable"><thead><tr><th>Namespace</th><th class="num">Count</th></tr></thead><tbody></tbody></table>
<script>
{_chart_helpers_js()}
const R = {payload};
let cumChart, weekChart;
function render() {{
  const theme = chartTheme();
  const once = document.getElementById("once").checked;
  document.getElementById("modePill").textContent = once
    ? "Distinct repositories" : "All registrations";
  document.getElementById("modePill").className = "pill " + (once ? "info" : "");
  document.getElementById("stats").innerHTML = `
    <div class="stat"><b>${{(R.allRegistrations||0).toLocaleString()}}</b><span>All project registrations</span></div>
    <div class="stat info"><b>${{(R.distinctRepositories||0).toLocaleString()}}</b><span>Distinct repositories</span></div>
    <div class="stat warn"><b>${{(R.duplicateRegistrations||0).toLocaleString()}}</b><span>Duplicate registrations</span></div>`;
  const seriesAll = R.weeklyAll || [];
  const seriesDistinct = R.weeklyDistinct || [];
  const cats = seriesAll.map(r => (r.w||"").slice(5));
  const distinctByWeek = new Map(seriesDistinct.map(r => [r.w, r]));
  let lastD = 0;
  const merged = seriesAll.map(r => {{
    const d = distinctByWeek.get(r.w);
    if (d) lastD = d.c;
    return {{ allCum: r.c, allNew: r.n, distinctCum: lastD, distinctNew: d ? d.n : 0 }};
  }});
  const opts = {{
    responsive: true, maintainAspectRatio: false,
    plugins: {{ legend: {{ labels: {{ color: theme.muted }} }} }},
    scales: chartScales(theme)
  }};
  if (cumChart) cumChart.destroy();
  if (weekChart) weekChart.destroy();
  cumChart = new Chart(document.getElementById("cumChart"), {{
    type: "line",
    data: {{
      labels: cats,
      datasets: [
        {{ label: "All registrations", data: merged.map(r => r.allCum), borderColor: theme.neutral, tension: 0.15 }},
        {{ label: "Distinct repositories", data: merged.map(r => r.distinctCum), borderColor: theme.accent, tension: 0.15 }},
      ]
    }},
    options: opts
  }});
  weekChart = new Chart(document.getElementById("weekChart"), {{
    type: "bar",
    data: {{
      labels: cats,
      datasets: [{{
        label: once ? "Distinct new" : "All new",
        data: merged.map(r => once ? r.distinctNew : r.allNew),
        backgroundColor: once ? theme.accent + "99" : theme.neutral + "99"
      }}]
    }},
    options: opts
  }});
  const hier = once ? (R.hierarchyDistinct||[]) : (R.hierarchyAll||[]);
  document.querySelector("#hierTable tbody").innerHTML = hier.map(h =>
    `<tr><td>${{h.namespace}}</td><td class="num">${{h.count.toLocaleString()}}</td></tr>`
  ).join("");
}}
document.getElementById("once").addEventListener("change", render);
render();
</script>
""",
        title=f"{copy_mod.H1_ONBOARDING} — {tenant}",
    )


def _render_version_sprawl(cube: dict[str, Any]) -> str:
    tenant = cube.get("tenant") or ""
    pulled = cube.get("pulledAt") or ""
    report = (cube.get("reports") or {}).get("versionSprawl") or {}
    slim = {
        "tenant": tenant,
        "pulledAt": pulled,
        "histKeys": report.get("histKeys") or [],
        "ecosystems": report.get("ecosystems") or [],
        "pathOptions": cube.get("pathOptions") or ["all"],
        "tags": [
            {"tag": t["tag"], "projectCount": t["projectCount"]}
            for t in (cube.get("tagCatalog") or [])
        ],
        "estate": report.get("estate") or {},
        "perPath": report.get("perPath") or {},
        "perTag": report.get("perTag") or {},
    }
    payload = json.dumps(slim, separators=(",", ":"))
    return _page(
        f"""{_nav("vs")}
{_header(title=copy_mod.H1_VERSION_SPRAWL, purpose=copy_mod.PURPOSE_VERSION_SPRAWL, tenant=tenant, pulled_at=pulled)}
{copy_mod.GLOSSARY_HTML}
<div class="card">
  <div class="card-h">Filters</div>
  <div class="filters">
    <label class="field">Namespace<select id="ns"></select></label>
    <label class="field">Project tag<select id="tag"></select></label>
    <label class="field">Ecosystem<select id="eco"></select></label>
  </div>
  <p class="muted" style="margin:10px 0 0">{copy_mod.TAG_HELP}. Selecting a tag scopes to namespaces that contain projects with that tag.</p>
  <div class="toggles"><span class="pill info" id="scope"></span></div>
</div>
<div class="stats" id="stats"></div>
<div class="callout" id="callout"></div>
<div class="card">
  <div class="card-h">Where version inventory sits</div>
  <p class="caption">Packages grouped by how many distinct versions are in use. Source: DependencyMetadata list_groups (package name × resolved version).</p>
  <div class="chart-box"><canvas id="histChart"></canvas></div>
</div>
<h2>Packages with the most versions in use</h2>
<p class="caption">Top packages by distinct versions under the active filters.</p>
<table class="data" id="topTable"><thead><tr><th>Package</th><th class="num">Versions in use</th></tr></thead><tbody></tbody></table>
<script>
{_chart_helpers_js()}
const CUBE = {payload};
const HIST_LABELS = {{"1":"1 version","2-3":"2–3 versions","4-5":"4–5 versions","6-10":"6–10 versions","11-25":"11–25 versions","26+":"26+ versions"}};
function emptyCell() {{ return {{p:0,v:0,max:0,avg:0,h:[0,0,0,0,0,0],hv:[0,0,0,0,0,0],t:[]}}; }}
function resolveCell(eco, ns, tag) {{
  eco = eco || "all";
  if (tag && tag !== "all") return (CUBE.perTag[tag]||{{}})[eco]?.all ?? emptyCell();
  if (ns && ns !== "all") return (CUBE.perPath[ns]||{{}})[eco]?.all ?? emptyCell();
  return (CUBE.estate[eco]||{{}})?.all ?? emptyCell();
}}
function fillSelect(el, options) {{
  el.innerHTML = options.map(o => `<option value="${{o.v}}">${{o.l}}</option>`).join("");
}}
let histChart;
function render() {{
  const theme = chartTheme();
  const eco = document.getElementById("eco").value;
  const ns = document.getElementById("ns").value;
  const tag = document.getElementById("tag").value;
  const cell = resolveCell(eco, ns, tag);
  const bits = [];
  if (ns !== "all") bits.push(ns);
  if (tag !== "all") bits.push("tag:" + tag);
  if (eco !== "all") bits.push(eco);
  document.getElementById("scope").textContent = bits.length ? bits.join(" · ") : "Entire organization";
  document.getElementById("stats").innerHTML = `
    <div class="stat info"><b>${{cell.p.toLocaleString()}}</b><span>Distinct packages</span></div>
    <div class="stat"><b>${{cell.v.toLocaleString()}}</b><span>Distinct package versions</span></div>
    <div class="stat"><b>${{cell.avg}}</b><span>Avg versions per package</span></div>
    <div class="stat${{cell.max>=50?" warn":""}}"><b>${{cell.max}}</b><span>Most versions for one package</span></div>`;
  document.getElementById("callout").textContent =
    `${{cell.p.toLocaleString()}} packages · ${{cell.v.toLocaleString()}} versions in scope.`;
  const labels = (CUBE.histKeys||[]).map(k => HIST_LABELS[k]||k);
  if (histChart) histChart.destroy();
  histChart = new Chart(document.getElementById("histChart"), {{
    type: "bar",
    data: {{
      labels,
      datasets: [
        {{ label: "Versions in those packages", data: cell.hv||cell.h, backgroundColor: theme.accent + "99" }},
        {{ label: "Packages in band", data: cell.h, backgroundColor: theme.secondary + "99" }},
      ]
    }},
    options: {{
      responsive: true, maintainAspectRatio: false,
      plugins: {{ legend: {{ labels: {{ color: theme.muted }} }} }},
      scales: chartScales(theme)
    }}
  }});
  const top = cell.t || [];
  document.querySelector("#topTable tbody").innerHTML = top.length
    ? top.map(([n,v]) => `<tr><td>${{n}}</td><td class="num"><b>${{v}}</b></td></tr>`).join("")
    : `<tr><td colspan="2" class="muted">No top list for this slice</td></tr>`;
}}
fillSelect(document.getElementById("ns"), [
  {{v:"all", l:"All namespaces"}},
  ...(CUBE.pathOptions||[]).filter(p => p!=="all").map(p => ({{v:p,l:p}}))
]);
fillSelect(document.getElementById("tag"), [
  {{v:"all", l:"All project tags"}},
  ...(CUBE.tags||[]).map(t => ({{v:t.tag, l:`${{t.tag}} (${{t.projectCount}} projects)`}}))
]);
fillSelect(document.getElementById("eco"), [
  {{v:"all", l:"All ecosystems"}},
  ...(CUBE.ecosystems||[]).map(e => ({{v:e,l:e}}))
]);
["ns","tag","eco"].forEach(id => document.getElementById(id).addEventListener("change", render));
render();
</script>
""",
        title=f"{copy_mod.H1_VERSION_SPRAWL} — {tenant}",
    )


def _render_findings_burndown(cube: dict[str, Any]) -> str:
    tenant = cube.get("tenant") or ""
    pulled = cube.get("pulledAt") or ""
    report = (cube.get("reports") or {}).get("findingsBurndown") or {}
    # Slim throughput topProjects to names only for size
    tp = report.get("throughput") or {}
    per_tag = {}
    for tag, scope in (tp.get("perTag") or {}).items():
        per_tag[tag] = {
            "projectCount": scope.get("projectCount"),
            "mainScans91d": scope.get("mainScans91d"),
            "ciRunScans21d": scope.get("ciRunScans21d"),
            "avgMainPerWeek": scope.get("avgMainPerWeek"),
            "topProjects": [
                {
                    "name": p.get("name"),
                    "namespace": p.get("namespace"),
                    "mainScans91d": p.get("mainScans91d"),
                    "ciRunScans21d": p.get("ciRunScans21d"),
                }
                for p in (scope.get("topProjects") or [])[:8]
            ],
        }
    slim = {
        "tenant": tenant,
        "pulledAt": pulled,
        "findingCriteria": report.get("findingCriteria"),
        "lookback": report.get("lookback"),
        "pathOptions": cube.get("pathOptions") or ["all"],
        "tagCatalog": [
            {"tag": t["tag"], "projectCount": t["projectCount"]}
            for t in (cube.get("tagCatalog") or [])
        ],
        "tagSeriesMeta": cube.get("tagSeriesMeta") or report.get("tagSeriesMeta"),
        "seriesFilters": report.get("seriesFilters"),
        "tagSeries": report.get("tagSeries"),
        "throughput": {
            "windows": tp.get("windows"),
            "perPath": {
                k: {
                    "projectCount": v.get("projectCount"),
                    "mainScans91d": v.get("mainScans91d"),
                    "ciRunScans21d": v.get("ciRunScans21d"),
                    "avgMainPerWeek": v.get("avgMainPerWeek"),
                }
                for k, v in (tp.get("perPath") or {}).items()
            },
            "perTag": per_tag,
        },
    }
    payload = json.dumps(slim, separators=(",", ":"))
    pending_caption = copy_mod.PENDING_TAG_CAPTION
    window_net = copy_mod.STAT_WINDOW_NET
    main_label = copy_mod.MAIN_THROUGHPUT_LABEL
    tag_help = copy_mod.TAG_HELP
    return _page(
        f"""{_nav("fb")}
{_header(title=copy_mod.H1_FINDINGS_BURNDOWN, purpose=copy_mod.PURPOSE_FINDINGS_BURNDOWN, tenant=tenant, pulled_at=pulled)}
{copy_mod.GLOSSARY_HTML}
<div class="card">
  <div class="card-h">Filters</div>
  <div class="filters">
    <label class="field">Namespace<select id="ns"></select></label>
    <label class="field">Project tag<select id="tag"></select></label>
    <label class="field">Severity<select id="sev"></select></label>
    <label class="field">Reachability<select id="reach"></select></label>
  </div>
  <div class="toggles" id="pills"></div>
  <p class="muted" style="margin:10px 0 0">{tag_help}. Tag selection scopes to projects that carry that tag.</p>
</div>
<div id="body"></div>
<script>
{_chart_helpers_js()}
const CUBE = {payload};
const PENDING_CAPTION = {json.dumps(pending_caption)};
const WINDOW_NET = {json.dumps(window_net)};
const MAIN_LABEL = {json.dumps(main_label)};
function pathKey(ns) {{ return ns && ns !== "all" ? ns : "all"; }}
function resolveSeries(ns, sev, reach, tag) {{
  if (tag && tag !== "all" && CUBE.tagSeries?.perTag?.[tag]) {{
    return CUBE.tagSeries.perTag[tag][pathKey(ns)]?.[sev]?.[reach] ?? null;
  }}
  return CUBE.seriesFilters?.perPath?.[pathKey(ns)]?.[sev]?.[reach] ?? null;
}}
function resolveTp(ns, tag) {{
  if (tag && tag !== "all") return CUBE.throughput?.perTag?.[tag] ?? null;
  return CUBE.throughput?.perPath?.[pathKey(ns)] ?? null;
}}
function fillSelect(el, options) {{
  el.innerHTML = options.map(o => `<option value="${{o.v}}">${{o.l}}</option>`).join("");
}}
function tagLabel(t) {{
  if (t === "all") return "All project tags";
  const cat = (CUBE.tagCatalog||[]).find(r => r.tag === t);
  const pc = cat?.projectCount;
  const ready = !!(CUBE.tagSeries?.perTag?.[t]);
  const base = pc != null ? `${{t}} (${{pc}} projects)` : t;
  return ready ? base : `${{base}} — series pending`;
}}
let gapChart, weekChart;
function destroyCharts() {{
  if (gapChart) {{ gapChart.destroy(); gapChart = null; }}
  if (weekChart) {{ weekChart.destroy(); weekChart = null; }}
}}
function render() {{
  const theme = chartTheme();
  const ns = document.getElementById("ns").value;
  const tag = document.getElementById("tag").value;
  const sev = document.getElementById("sev").value;
  const reach = document.getElementById("reach").value;
  const cell = resolveSeries(ns, sev, reach, tag);
  const tp = resolveTp(ns, tag);
  const bits = [];
  if (ns === "all") bits.push("Entire organization"); else bits.push(ns);
  if (tag !== "all") bits.push("tag:" + tag);
  if (sev !== "all") bits.push(sev);
  if (reach !== "all") bits.push(reach === "prf" ? "PRF" : "reachable");
  document.getElementById("pills").innerHTML = `<span class="pill info">${{bits.join(" · ")}}</span>`;
  destroyCharts();
  const body = document.getElementById("body");
  const pending = tag !== "all" && !CUBE.tagSeries?.perTag?.[tag];
  if (pending) {{
    body.innerHTML = `<div class="callout warn">${{PENDING_CAPTION}}</div>` +
      (tp ? `<div class="stats">
        <div class="stat"><b>${{(tp.projectCount||0).toLocaleString()}}</b><span>Projects with tag</span></div>
        <div class="stat"><b>${{(tp.mainScans91d||0).toLocaleString()}}</b><span>${{MAIN_LABEL}}</span></div>
        <div class="stat"><b>${{(tp.ciRunScans21d||0).toLocaleString()}}</b><span>CI / PR scans (21d)</span></div>
      </div>` : "");
    return;
  }}
  if (!cell) {{
    body.innerHTML = `<div class="callout warn">No trend series for this filter combination.</div>`;
    return;
  }}
  const lastNew = cell.weeklyNew.at(-1) || 0;
  const lastRes = cell.weeklyResolved.at(-1) || 0;
  const mainDays = CUBE.throughput?.windows?.mainDays ?? 91;
  body.innerHTML = `<div class="stats">
    <div class="stat ${{cell.gapEnd>0?"warn":"ok"}}"><b>${{cell.gapEnd.toLocaleString()}}</b><span>${{WINDOW_NET}}</span></div>
    <div class="stat"><b>${{lastNew.toLocaleString()}}</b><span>New (last week)</span></div>
    <div class="stat info"><b>${{lastRes.toLocaleString()}}</b><span>Resolved (last week)</span></div>
    <div class="stat"><b>${{cell.gapTrend}}</b><span>Gap trend</span></div>
  </div>
  ${{tp ? `<div class="stats">
    <div class="stat"><b>${{(tp.projectCount||0).toLocaleString()}}</b><span>Projects in scope</span></div>
    <div class="stat"><b>${{(tp.mainScans91d||0).toLocaleString()}}</b><span>${{MAIN_LABEL}} (${{mainDays}}d)</span></div>
    <div class="stat"><b>${{(tp.ciRunScans21d||0).toLocaleString()}}</b><span>CI / PR scans (21d)</span></div>
  </div>` : ""}}
  <div class="card"><div class="card-h">Cumulative new vs resolved · window net</div>
    <p class="caption">Source: FindingLog CREATE/DELETE · ${{CUBE.findingCriteria||""}} · ${{cell.periodCaption||""}} · filters: ${{bits.join(" · ")}}</p>
    <div class="chart-box"><canvas id="gapChart"></canvas></div></div>
  <div class="card"><div class="card-h">Weekly new vs resolved</div>
    <p class="caption">Weekly FindingLog event counts under the same filters.</p>
    <div class="chart-box sm"><canvas id="weekChart"></canvas></div></div>`;
  const cats = (cell.categories||[]).map(c => String(c).slice(0,12));
  const opts = {{
    responsive: true, maintainAspectRatio: false,
    plugins: {{ legend: {{ labels: {{ color: theme.muted }} }} }},
    scales: chartScales(theme)
  }};
  gapChart = new Chart(document.getElementById("gapChart"), {{
    type: "line",
    data: {{
      labels: cats,
      datasets: [
        {{ label: "Cumulative new", data: cell.cumulativeNew, borderColor: theme.danger, tension: 0.2 }},
        {{ label: "Cumulative resolved", data: cell.cumulativeResolved, borderColor: theme.ok, tension: 0.2 }},
        {{ label: "Window net", data: cell.gaps, borderColor: theme.warn, borderDash: [4,4], tension: 0.2 }},
      ]
    }},
    options: opts
  }});
  weekChart = new Chart(document.getElementById("weekChart"), {{
    type: "bar",
    data: {{
      labels: cats,
      datasets: [
        {{ label: "New", data: cell.weeklyNew, backgroundColor: theme.danger + "99" }},
        {{ label: "Resolved", data: cell.weeklyResolved, backgroundColor: theme.ok + "99" }},
      ]
    }},
    options: opts
  }});
}}
fillSelect(document.getElementById("ns"), [
  {{v:"all", l:"All namespaces"}},
  ...(CUBE.pathOptions||[]).filter(p => p!=="all").map(p => ({{v:p,l:p}}))
]);
fillSelect(document.getElementById("tag"), [
  {{v:"all", l:"All project tags"}},
  ...(CUBE.tagCatalog||[]).map(t => ({{v:t.tag, l: tagLabel(t.tag)}}))
]);
fillSelect(document.getElementById("sev"), [
  {{v:"all", l:"All severities (Critical + High)"}},
  {{v:"critical", l:"Critical only"}},
  {{v:"high", l:"High only"}},
]);
fillSelect(document.getElementById("reach"), [
  {{v:"all", l:"All reachability (RF + PRF)"}},
  {{v:"reachable", l:"Reachable function only"}},
  {{v:"prf", l:"Potentially reachable only"}},
]);
["ns","tag","sev","reach"].forEach(id => document.getElementById(id).addEventListener("change", render));
render();
</script>
""",
        title=f"{copy_mod.H1_FINDINGS_BURNDOWN} — {tenant}",
    )


def render_report_packet(
    cube: dict[str, Any],
    out_dir: str | Path,
) -> list[Path]:
    """Write HTML packet + cube JSON + README under *out_dir*.

    Returns paths written (relative order: onboarding, sprawl, burndown, cube, README).
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    data_dir = out / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    files = [
        (out / "01-onboarding.html", _render_onboarding(cube)),
        (out / "02-version-sprawl.html", _render_version_sprawl(cube)),
        (out / "03-findings-burndown.html", _render_findings_burndown(cube)),
        (data_dir / "packet.cube.json", json.dumps(cube, indent=2) + "\n"),
        (out / "README.txt", copy_mod.README_TEXT),
    ]
    written: list[Path] = list(_copy_shell_assets(out))
    for path, content in files:
        safe_write_text(out, path, content)
        written.append(path)
    return written


def default_packet_output_dir(namespace: str) -> Path:
    """Default ``runs/executive-report-packet/<tenant>-executive-packet`` path."""
    from endorlabs.context.paths import default_runs_dir

    slug = sanitize_path_segment(namespace)
    return default_runs_dir(RUN_BUCKET) / f"{slug}-executive-packet"
