"""
Finding resource module for Endor Labs API.

This module provides CRUD operations for Finding resources following the established
patterns from the Project resource implementation.

API OPERATIONS SUPPORTED:
- GET: List findings, Get finding by UUID
- PATCH: Update finding tags and metadata

API LIMITATIONS:
- CREATE: Not supported by API (findings are generated by security scans)
- DELETE: Not supported by API (findings are immutable for audit purposes)

Note: Findings are automatically generated by Endor Labs security scans and cannot
be manually created or deleted. Only metadata updates (tags, dismissal status) allowed.
"""

import logging
from datetime import datetime
from typing import Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator

from ..api_client import APIClient
from ..models.base import (
    BaseMeta,
    BaseResource,
    BaseResourceOperations,
    BaseSpec,
    FlexibleEnum,
)
from ..types import ListParameters

logger = logging.getLogger(__name__)


class FindingCategory(FlexibleEnum):
    """Finding category enumeration."""

    UNSPECIFIED = "FINDING_CATEGORY_UNSPECIFIED"
    VULNERABILITY = "FINDING_CATEGORY_VULNERABILITY"
    SUPPLY_CHAIN = "FINDING_CATEGORY_SUPPLY_CHAIN"
    LICENSE_RISK = "FINDING_CATEGORY_LICENSE_RISK"
    SCPM = "FINDING_CATEGORY_SCPM"
    SECURITY = "FINDING_CATEGORY_SECURITY"
    OPERATIONAL = "FINDING_CATEGORY_OPERATIONAL"
    SECRETS = "FINDING_CATEGORY_SECRETS"
    MALWARE = "FINDING_CATEGORY_MALWARE"
    CICD = "FINDING_CATEGORY_CICD"
    TOOLS = "FINDING_CATEGORY_TOOLS"
    GHACTIONS = "FINDING_CATEGORY_GHACTIONS"
    CONTAINER = "FINDING_CATEGORY_CONTAINER"
    SAST = "FINDING_CATEGORY_SAST"
    AI_MODELS = "FINDING_CATEGORY_AI_MODELS"


class FindingLevel(FlexibleEnum):
    """Finding severity level enumeration."""

    UNSPECIFIED = "FINDING_LEVEL_UNSPECIFIED"
    CRITICAL = "FINDING_LEVEL_CRITICAL"
    HIGH = "FINDING_LEVEL_HIGH"
    MEDIUM = "FINDING_LEVEL_MEDIUM"
    LOW = "FINDING_LEVEL_LOW"
    INFO = "FINDING_LEVEL_INFO"


class FindingStatus(FlexibleEnum):
    """Finding status enumeration."""

    UNSPECIFIED = "FINDING_STATUS_UNSPECIFIED"
    OPEN = "FINDING_STATUS_OPEN"
    RESOLVED = "FINDING_STATUS_RESOLVED"
    IGNORED = "FINDING_STATUS_IGNORED"
    FALSE_POSITIVE = "FINDING_STATUS_FALSE_POSITIVE"


class AnalysisMethod(FlexibleEnum):
    """Analysis method enumeration."""

    UNSPECIFIED = "SYSTEM_EVALUATION_METHOD_UNSPECIFIED"
    DEFINITION_VULNERABILITIES = "SYSTEM_EVALUATION_METHOD_DEFINITION_VULNERABILITIES"
    DEFINITION_POLICIES = "SYSTEM_EVALUATION_METHOD_DEFINITION_POLICIES"
    SAST = "SYSTEM_EVALUATION_METHOD_SAST"
    SCA = "SYSTEM_EVALUATION_METHOD_SCA"
    SECRETS = "SYSTEM_EVALUATION_METHOD_SECRETS"
    CONTAINER = "SYSTEM_EVALUATION_METHOD_CONTAINER"
    INFRASTRUCTURE = "SYSTEM_EVALUATION_METHOD_INFRASTRUCTURE"


class CallGraphAnalysisType(FlexibleEnum):
    """Call graph analysis type enumeration."""

    UNSPECIFIED = "CALL_GRAPH_ANALYSIS_TYPE_UNSPECIFIED"
    FULL = "CALL_GRAPH_ANALYSIS_TYPE_FULL"


class Ecosystem(FlexibleEnum):
    """Package ecosystem enumeration."""

    UNSPECIFIED = "ECOSYSTEM_UNSPECIFIED"
    NPM = "ECOSYSTEM_NPM"
    PYPI = "ECOSYSTEM_PYPI"
    MAVEN = "ECOSYSTEM_MAVEN"
    NUGET = "ECOSYSTEM_NUGET"
    RUBYGEMS = "ECOSYSTEM_RUBYGEMS"
    GO = "ECOSYSTEM_GO"
    RUST = "ECOSYSTEM_RUST"
    CARGO = "ECOSYSTEM_CARGO"
    COMPOSER = "ECOSYSTEM_COMPOSER"
    HEX = "ECOSYSTEM_HEX"
    COCOAPODS = "ECOSYSTEM_COCOAPODS"
    SWIFT = "ECOSYSTEM_SWIFT"
    CONAN = "ECOSYSTEM_CONAN"
    CRAN = "ECOSYSTEM_CRAN"
    PUB = "ECOSYSTEM_PUB"
    PACKAGIST = "ECOSYSTEM_PACKAGIST"
    DEBIAN = "ECOSYSTEM_DEBIAN"
    UBUNTU = "ECOSYSTEM_UBUNTU"
    ALPINE = "ECOSYSTEM_ALPINE"
    RHEL = "ECOSYSTEM_RHEL"
    AMAZON = "ECOSYSTEM_AMAZON"
    SUSE = "ECOSYSTEM_SUSE"
    ARCH = "ECOSYSTEM_ARCH"
    GENTOO = "ECOSYSTEM_GENTOO"
    FEDORA = "ECOSYSTEM_FEDORA"
    PHARONIX = "ECOSYSTEM_PHARONIX"
    DOCKER = "ECOSYSTEM_DOCKER"
    GITHUB = "ECOSYSTEM_GITHUB"
    GITLAB = "ECOSYSTEM_GITLAB"
    BITBUCKET = "ECOSYSTEM_BITBUCKET"
    AZURE_DEVOPS = "ECOSYSTEM_AZURE_DEVOPS"
    JENKINS = "ECOSYSTEM_JENKINS"
    CIRCLECI = "ECOSYSTEM_CIRCLECI"
    TRAVIS_CI = "ECOSYSTEM_TRAVIS_CI"
    GITHUB_ACTIONS = "ECOSYSTEM_GITHUB_ACTIONS"
    GITLAB_CI = "ECOSYSTEM_GITLAB_CI"
    AZURE_PIPELINES = "ECOSYSTEM_AZURE_PIPELINES"
    BAMBOO = "ECOSYSTEM_BAMBOO"
    TEAMCITY = "ECOSYSTEM_TEAMCITY"
    BUILDKITE = "ECOSYSTEM_BUILDKITE"
    CODESHIP = "ECOSYSTEM_CODESHIP"
    DRONE = "ECOSYSTEM_DRONE"
    SEMAPHORE = "ECOSYSTEM_SEMAPHORE"
    APPVEYOR = "ECOSYSTEM_APPVEYOR"
    WERCKER = "ECOSYSTEM_WERCKER"
    SHIPPABLE = "ECOSYSTEM_SHIPPABLE"
    MAGNUM = "ECOSYSTEM_MAGNUM"
    SOLANO = "ECOSYSTEM_SOLANO"
    BUDDY = "ECOSYSTEM_BUDDY"
    CODEFRESH = "ECOSYSTEM_CODEFRESH"
    CODEFRESH_PIPELINES = "ECOSYSTEM_CODEFRESH_PIPELINES"
    CODEFRESH_RUNTIME = "ECOSYSTEM_CODEFRESH_RUNTIME"
    CODEFRESH_RUNTIME_IMAGES = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES"
    CODEFRESH_RUNTIME_IMAGES_UBUNTU = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_UBUNTU"
    CODEFRESH_RUNTIME_IMAGES_ALPINE = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_ALPINE"
    CODEFRESH_RUNTIME_IMAGES_DEBIAN = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_DEBIAN"
    CODEFRESH_RUNTIME_IMAGES_CENTOS = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_CENTOS"
    CODEFRESH_RUNTIME_IMAGES_RHEL = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_RHEL"
    CODEFRESH_RUNTIME_IMAGES_AMAZON = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_AMAZON"
    CODEFRESH_RUNTIME_IMAGES_SUSE = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_SUSE"
    CODEFRESH_RUNTIME_IMAGES_ARCH = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_ARCH"
    CODEFRESH_RUNTIME_IMAGES_GENTOO = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_GENTOO"
    CODEFRESH_RUNTIME_IMAGES_FEDORA = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_FEDORA"
    CODEFRESH_RUNTIME_IMAGES_PHARONIX = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_PHARONIX"
    CODEFRESH_RUNTIME_IMAGES_DOCKER = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_DOCKER"
    CODEFRESH_RUNTIME_IMAGES_GITHUB = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_GITHUB"
    CODEFRESH_RUNTIME_IMAGES_GITLAB = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_GITLAB"
    CODEFRESH_RUNTIME_IMAGES_BITBUCKET = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_BITBUCKET"
    CODEFRESH_RUNTIME_IMAGES_AZURE_DEVOPS = (
        "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_AZURE_DEVOPS"
    )
    CODEFRESH_RUNTIME_IMAGES_JENKINS = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_JENKINS"
    CODEFRESH_RUNTIME_IMAGES_CIRCLECI = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_CIRCLECI"
    CODEFRESH_RUNTIME_IMAGES_TRAVIS_CI = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_TRAVIS_CI"
    CODEFRESH_RUNTIME_IMAGES_GITHUB_ACTIONS = (
        "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_GITHUB_ACTIONS"
    )
    CODEFRESH_RUNTIME_IMAGES_GITLAB_CI = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_GITLAB_CI"
    CODEFRESH_RUNTIME_IMAGES_AZURE_PIPELINES = (
        "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_AZURE_PIPELINES"
    )
    CODEFRESH_RUNTIME_IMAGES_BAMBOO = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_BAMBOO"
    CODEFRESH_RUNTIME_IMAGES_TEAMCITY = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_TEAMCITY"
    CODEFRESH_RUNTIME_IMAGES_BUILDKITE = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_BUILDKITE"
    CODEFRESH_RUNTIME_IMAGES_CODESHIP = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_CODESHIP"
    CODEFRESH_RUNTIME_IMAGES_DRONE = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_DRONE"
    CODEFRESH_RUNTIME_IMAGES_SEMAPHORE = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_SEMAPHORE"
    CODEFRESH_RUNTIME_IMAGES_APPVEYOR = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_APPVEYOR"
    CODEFRESH_RUNTIME_IMAGES_WERCKER = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_WERCKER"
    CODEFRESH_RUNTIME_IMAGES_SHIPPABLE = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_SHIPPABLE"
    CODEFRESH_RUNTIME_IMAGES_MAGNUM = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_MAGNUM"
    CODEFRESH_RUNTIME_IMAGES_SOLANO = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_SOLANO"
    CODEFRESH_RUNTIME_IMAGES_BUDDY = "ECOSYSTEM_CODEFRESH_RUNTIME_IMAGES_BUDDY"


class CvssVersion(FlexibleEnum):
    """CVSS version enumeration."""

    UNSPECIFIED = "CVSS_VERSION_UNSPECIFIED"
    V3 = "CVSS_VERSION_V3"
    V4 = "CVSS_VERSION_V4"


class CvssSeverityLevel(FlexibleEnum):
    """CVSS severity level enumeration."""

    UNSPECIFIED = "CVSS_SEVERITY_LEVEL_UNSPECIFIED"
    NONE = "CVSS_SEVERITY_LEVEL_NONE"
    LOW = "CVSS_SEVERITY_LEVEL_LOW"
    MEDIUM = "CVSS_SEVERITY_LEVEL_MEDIUM"
    HIGH = "CVSS_SEVERITY_LEVEL_HIGH"
    CRITICAL = "CVSS_SEVERITY_LEVEL_CRITICAL"


class FindingTags(FlexibleEnum):
    """Finding tags enumeration."""

    UNSPECIFIED = "FINDING_TAGS_UNSPECIFIED"
    NORMAL = "FINDING_TAGS_NORMAL"
    POLICY = "FINDING_TAGS_POLICY"
    EXCEPTION = "FINDING_TAGS_EXCEPTION"
    TEST = "FINDING_TAGS_TEST"


class RangeType(FlexibleEnum):
    """Range type enumeration."""

    UNSPECIFIED = "RANGE_TYPE_UNSPECIFIED"
    ECOSYSTEM = "RANGE_TYPE_ECOSYSTEM"
    GIT = "RANGE_TYPE_GIT"
    SEMVER = "RANGE_TYPE_SEMVER"
    UNKNOWN = "RANGE_TYPE_UNKNOWN"


class FindingRemediation(FlexibleEnum):
    """Finding remediation action enumeration."""

    UNSPECIFIED = "FINDING_REMEDIATION_UNSPECIFIED"
    UPGRADE = "FINDING_REMEDIATION_UPGRADE"
    DOWNGRADE = "FINDING_REMEDIATION_DOWNGRADE"
    REPLACE = "FINDING_REMEDIATION_REPLACE"
    REMOVE = "FINDING_REMEDIATION_REMOVE"
    VENDOR = "FINDING_REMEDIATION_VENDOR"
    IMPROVE = "FINDING_REMEDIATION_IMPROVE"
    REIMPLEMENT = "FINDING_REMEDIATION_REIMPLEMENT"
    REVIEW = "FINDING_REMEDIATION_REVIEW"
    NOTIFICATION = "FINDING_REMEDIATION_NOTIFICATION"
    PIN = "FINDING_REMEDIATION_PIN"


class FindingMeta(BaseMeta):
    """Finding metadata extending BaseMeta."""

    # Finding-specific fields (universal fields inherited from BaseMeta)
    pass  # No additional fields needed, all were universal


class Actions(BaseModel):
    """Actions metadata added by admission or notification policy scanner."""

    policy_uuids: Optional[List[str]] = Field(
        None, description="List of action policies triggered by this finding"
    )


class FixingPatch(BaseModel):
    """Patch that can fix the finding."""

    endor_patch_available: Optional[bool] = Field(
        None, description="Whether an Endor patch is available"
    )


class SourceCodeVersion(BaseModel):
    """Source code version information."""

    sha: Optional[str] = Field(
        None,
        description=(
            "SHA of the source control version. "
            "Because the SHA might not be possible to resolve, this field is optional."
        ),
    )
    ref: Optional[str] = Field(
        None,
        description=(
            "Resolved ref of the source control version. "
            "Can be a tag, a branch or a SHA."
        ),
    )
    metadata: Optional[Dict[str, str]] = Field(
        None, description="Version metadata as key-value pairs"
    )


class FindingMetadata(BaseModel):
    """Finding metadata details.

    This model extends the basic finding metadata with all fields from the OpenAPI spec.
    Many fields are optional and only present for specific finding types.
    """

    title: Optional[str] = None
    description: Optional[str] = None
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    code_snippet: Optional[str] = None
    category: Optional[FindingCategory] = None

    # Extended fields from OpenAPI spec v1FindingMetadata
    root_package_score_card: Optional[dict] = Field(
        None, description="The package scorecard for findings about low scores"
    )
    dependency_score_card: Optional[dict] = Field(
        None, description="The dependency scorecard for findings about low scores"
    )
    root_package_score_factor_list: Optional[dict] = Field(
        None,
        description=(
            "A list of (relevant) score factors, for the root package, "
            "for findings about low scores"
        ),
    )
    dependency_score_factor_list: Optional[dict] = Field(
        None,
        description=(
            "A list of (relevant) score factors, for the dependency, "
            "for findings about low scores"
        ),
    )
    vulnerability: Optional[dict] = Field(
        None, description="Vulnerability data for vulnerability related findings"
    )
    root_package_resolved_dependencies: Optional[dict] = Field(
        None, description="The resolved dependencies of the root package"
    )
    source_policy_info: Optional[dict] = Field(
        None, description="Details about the policy that created the finding"
    )
    ci_blocking_policy_info: Optional[dict] = Field(
        None,
        description=(
            "This field is always empty. See spec.actions instead."
        ),
    )
    root_package_version_metadata: Optional[dict] = Field(
        None, description="Package metadata for the root package"
    )
    dependency_package_version_metadata: Optional[dict] = Field(
        None, description="Package metadata for the dependency"
    )
    typosquatted_dependency_version_metadata: Optional[dict] = Field(
        None,
        description=(
            "Package metadata for the typosquatted package, "
            "for findings about typosquatting"
        ),
    )
    container_data: Optional[dict] = Field(
        None, description="Container image data of finding"
    )
    custom: Optional[dict] = Field(None, description="Custom finding metadata")
    security_review_data: Optional[dict] = Field(
        None, description="Security review data for security review findings"
    )
    malware: Optional[dict] = Field(
        None, description="Malware data for malware related findings"
    )
    cvss_version: Optional[CvssVersion] = Field(
        None, description="CVSS version of the vulnerability"
    )


class FindingSpec(BaseSpec):
    """Finding specification extending BaseSpec.

    Field Mutability Guide:
    ======================

    FIELD MUTABILITY (per OpenAPI spec):
    =====================================
    Note: v1FindingSpec has NO fields marked as readOnly: true in the API spec.
    This means all FindingSpec fields are technically mutable via the Update endpoint.

    However, many fields are analysis-determined and updated by the scan service.
    Common fields updated by users:
    - dismiss: Dismissal status
    - remediation: Remediation guidance
    - summary: Finding summary
    - finding_tags: Finding-specific tags
    - extra_key: User-defined extra information
    """

    project_uuid: Optional[str] = Field(
        None,
        description="UUID of the project this finding belongs to",  # IMMUTABLE
    )
    last_processed: Optional[datetime] = Field(
        None,
        description="Last processed timestamp",  # IMMUTABLE: System-managed
    )
    level: Optional[FindingLevel] = Field(
        None, description="Severity level of the finding"
    )  # IMMUTABLE: Analysis-determined
    dismiss: Optional[bool] = Field(
        None,
        description="Whether the finding is dismissed",  # MUTABLE: User can update
    )
    remediation: Optional[str] = Field(
        None, description="Remediation guidance"
    )  # MUTABLE: User can update
    finding_metadata: Optional[FindingMetadata] = Field(
        None,
        description="Complex nested structure with finding-specific metadata",  # IMMUTABLE: System-generated
    )
    summary: Optional[str] = Field(
        None, description="Finding summary"
    )  # MUTABLE: User can update
    finding_tags: Optional[List[str]] = Field(
        None,
        description="Tags associated with the finding",  # MUTABLE: User can update
    )
    target_uuid: Optional[str] = Field(
        None, description="Target resource UUID"
    )  # IMMUTABLE: Set at creation
    extra_key: Optional[str] = Field(
        None, description="Extra key information"
    )  # MUTABLE: User can update
    method: Optional[AnalysisMethod] = Field(
        None, description="Analysis method used"
    )  # IMMUTABLE: Analysis-determined

    @field_validator("level", mode="before")
    @classmethod
    def validate_level(cls, v):
        """Handle unknown level values gracefully."""
        if isinstance(v, str):
            try:
                return FindingLevel(v)
            except ValueError:
                logger.warning(f"Unknown FindingLevel value: {v}. Using as-is.")
                return v
        return v

    @field_validator("method", mode="before")
    @classmethod
    def validate_method(cls, v):
        """Handle unknown method values gracefully."""
        if isinstance(v, str):
            try:
                return AnalysisMethod(v)
            except ValueError:
                logger.warning(f"Unknown AnalysisMethod value: {v}. Using as-is.")
                return v
        return v

    @field_validator("ecosystem", mode="before")
    @classmethod
    def validate_ecosystem(cls, v):
        """Handle unknown ecosystem values gracefully."""
        if isinstance(v, str):
            try:
                return Ecosystem(v)
            except ValueError:
                logger.warning(f"Unknown Ecosystem value: {v}. Using as-is.")
                return v
        return v

    @field_validator("finding_tags")
    @classmethod
    def validate_finding_tags(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        """Validate finding tags are not empty strings."""
        if v:
            return [tag.strip() for tag in v if tag.strip()]
        return v

    @field_validator("remediation")
    @classmethod
    def validate_remediation(cls, v: Optional[str]) -> Optional[str]:
        """Validate remediation is not just whitespace."""
        if v and not v.strip():
            raise ValueError("remediation cannot be empty or whitespace")
        return v.strip() if v else v

    @field_validator("remediation_action", mode="before")
    @classmethod
    def validate_remediation_action(cls, v):
        """Handle unknown remediation action values gracefully."""
        if isinstance(v, str):
            try:
                return FindingRemediation(v)
            except ValueError:
                logger.warning(f"Unknown FindingRemediation value: {v}. Using as-is.")
                return v
        return v

    @field_validator("finding_categories", mode="before")
    @classmethod
    def validate_finding_categories(cls, v):
        """Handle finding categories validation."""
        if isinstance(v, list):
            validated_categories = []
            for category in v:
                if isinstance(category, str):
                    try:
                        validated_categories.append(FindingCategory(category))
                    except ValueError:
                        logger.warning(
                            f"Unknown FindingCategory value: {category}. Using as-is."
                        )
                        validated_categories.append(category)
                else:
                    validated_categories.append(category)
            return validated_categories
        return v

    @field_validator("call_graph_analysis_type", mode="before")
    @classmethod
    def validate_call_graph_analysis_type(cls, v):
        """Handle unknown call graph analysis type values gracefully."""
        if isinstance(v, str):
            try:
                return CallGraphAnalysisType(v)
            except ValueError:
                logger.warning(
                    f"Unknown CallGraphAnalysisType value: {v}. Using as-is."
                )
                return v
        return v

    target_dependency_package_name: Optional[str] = Field(
        None,
        description="Fully qualified name of the dependency, e.g. eco://package@version",
    )  # IMMUTABLE: Analysis-determined
    target_dependency_name: Optional[str] = Field(
        None,
        description="Dependency package name, if applicable. This is just the name.",
    )  # IMMUTABLE: Analysis-determined
    target_dependency_version: Optional[str] = Field(
        None,
        description="Dependency version, if applicable. This is just the version.",
    )  # IMMUTABLE: Analysis-determined
    explanation: Optional[str] = Field(
        None, description="Information about why this finding is considered noteworthy"
    )  # IMMUTABLE: Analysis-determined
    remediation_action: Optional[FindingRemediation] = Field(
        None, description="Recommended action to resolve the finding"
    )  # IMMUTABLE: Analysis-determined
    source_code_version: Optional[SourceCodeVersion] = Field(
        None,
        description="Ref of the source code repository for root package version",
    )  # IMMUTABLE: Analysis-determined
    reachable_paths: Optional[List[dict]] = Field(
        None,
        description="Function paths to vulnerable method. Only for vulnerabilities.",
    )  # IMMUTABLE: Analysis-determined
    ecosystem: Optional[Ecosystem] = Field(
        None, description="Ecosystem where the finding was detected"
    )  # IMMUTABLE: Analysis-determined
    finding_categories: Optional[List[FindingCategory]] = Field(
        None,
        description="List of categories that capture the use case the finding fits in.",
    )  # IMMUTABLE: Analysis-determined
    relationship: Optional[str] = Field(
        None, description="Relationship information"
    )  # IMMUTABLE: Analysis-determined
    latest_version: Optional[str] = Field(
        None, description="Latest version of the dependency"
    )  # IMMUTABLE: Analysis-determined
    dependency_file_paths: Optional[List[str]] = Field(
        None, description="Paths to dependency files"
    )  # IMMUTABLE: Analysis-determined
    approximation: Optional[bool] = Field(
        None, description="Whether this is an approximation"
    )  # IMMUTABLE: Analysis-determined
    proposed_version: Optional[str] = Field(
        None, description="Proposed version for remediation"
    )  # IMMUTABLE: Analysis-determined
    exceptions: Optional[Union[List[str], dict]] = Field(
        None, description="Exception information"
    )  # IMMUTABLE: Analysis-determined
    actions: Optional[Actions] = Field(
        None, description="Tags and other fields set by action policies"
    )  # IMMUTABLE: Analysis-determined
    fixing_upgrades: Optional[Union[List[Union[str, dict]], dict]] = Field(
        None,
        description=(
            "Fixing upgrade information. Can be: "
            "list of strings, list of dicts, or dict with upgrade_list key"
        ),
    )  # IMMUTABLE: Analysis-determined
    fixing_patch: Optional[FixingPatch] = Field(
        None, description="Patch that can fix the finding"
    )  # IMMUTABLE: Analysis-determined

    @field_validator("finding_metadata", mode="before")
    @classmethod
    def validate_finding_metadata(cls, v):
        """Handle finding_metadata as dict or FindingMetadata model."""
        if v is None:
            return None
        if isinstance(v, FindingMetadata):
            return v
        if isinstance(v, dict):
            return FindingMetadata(**v)
        return v

    @field_validator("actions", mode="before")
    @classmethod
    def validate_actions(cls, v):
        """Handle actions as dict, list, or Actions model."""
        if v is None:
            return None
        if isinstance(v, Actions):
            return v
        if isinstance(v, dict):
            return Actions(**v)
        # If it's a list (legacy format), return None as Actions expects dict
        if isinstance(v, list):
            return None
        return v

    @field_validator("fixing_patch", mode="before")
    @classmethod
    def validate_fixing_patch(cls, v):
        """Handle fixing_patch as dict, list, or FixingPatch model."""
        if v is None:
            return None
        if isinstance(v, FixingPatch):
            return v
        if isinstance(v, dict):
            return FixingPatch(**v)
        # If it's a list (legacy format), return None as FixingPatch expects dict
        if isinstance(v, list):
            return None
        return v

    @field_validator("source_code_version", mode="before")
    @classmethod
    def validate_source_code_version(cls, v):
        """Handle source_code_version as dict or SourceCodeVersion model."""
        if v is None:
            return None
        if isinstance(v, SourceCodeVersion):
            return v
        if isinstance(v, dict):
            return SourceCodeVersion(**v)
        return v

    @field_validator("location_urls", mode="before")
    @classmethod
    def validate_location_urls(cls, v):
        """Handle location_urls as dict, list, or Dict[str, str]."""
        if v is None:
            return None
        if isinstance(v, dict):
            # Ensure all values are strings
            return {k: str(v) for k, v in v.items()}
        if isinstance(v, list):
            # Legacy format - convert to empty dict
            return {}
        return v

    @field_validator("fixing_upgrades", mode="before")
    @classmethod
    def validate_fixing_upgrades(cls, v):
        """Normalize fixing_upgrades from dict with upgrade_list to list."""
        if isinstance(v, dict) and "upgrade_list" in v:
            return v["upgrade_list"]
        # If it's already a list (of strings or dicts), return as-is
        return v
    code_owners: Optional[Union[List[str], dict]] = Field(
        None, description="Code owners information (list or dict with owners/labels)"
    )  # IMMUTABLE: Analysis-determined
    location_urls: Optional[Dict[str, str]] = Field(
        None,
        description=(
            "The URLs that correspond to the paths contained in dependency_file_paths. "
            "Keys are file paths, values are URLs."
        ),
    )  # IMMUTABLE: Analysis-determined
    call_graph_analysis_type: Optional[CallGraphAnalysisType] = Field(
        None, description="Call graph analysis type"
    )  # IMMUTABLE: Analysis-determined

    @field_validator("*", mode="before")
    @classmethod
    def detect_schema_drift(cls, v, info):
        """Override BaseSpec drift detection to skip typed nested model fields."""
        # Skip drift detection for typed nested models (they handle their own validation)
        typed_model_fields = {
            "finding_metadata",  # FindingMetadata
            "actions",  # Actions
            "fixing_patch",  # FixingPatch
            "source_code_version",  # SourceCodeVersion
            "location_urls",  # Dict[str, str] - typed
        }
        if (
            info.field_name
            and isinstance(v, dict)
            and info.field_name not in typed_model_fields
        ):
            # Call parent validator for non-typed-model fields
            return super().detect_schema_drift(v, info)
        return v


class Context(BaseModel):
    """Context information for findings."""

    id: Optional[str] = None
    type: Optional[str] = None
    scan_uuid: Optional[str] = None
    scan_type: Optional[str] = None
    scan_time: Optional[datetime] = None
    will_be_deleted_at: Optional[str] = None
    tags: Optional[List[str]] = None


class TenantMeta(BaseModel):
    """Tenant metadata."""

    namespace: str


class Finding(BaseResource):
    """
    An Endor Labs finding entity extending BaseResource.

    Finding-specific fields (universal fields inherited from BaseResource).

    OPERATION SUPPORT:
    ==================
    ✅ GET: List findings, Get by UUID
    ✅ PATCH: Update tags and metadata
    ❌ CREATE: Not supported (findings generated by scans)
    ❌ DELETE: Not supported (findings are immutable)

    FIELD MUTABILITY:
    =================
    IMMUTABLE FIELDS (read-only, system-generated):
    - uuid: Unique identifier
    - meta.name: Finding name (set by scan)
    - spec.level: Severity level (set by scan)
    - spec.category: Finding category (set by scan)
    - spec.project_uuid: Associated project (set at creation)
    - spec.finding_metadata: Scan-discovered metadata
    - tenant_meta.namespace: Namespace assignment

    MUTABLE FIELDS (can be updated via PATCH):
    - meta.tags: General resource tags
    - spec.finding_tags: Finding-specific tags
    - spec.dismiss: Dismissal status
    - spec.remediation: Remediation guidance
    - context.tags: Contextual tags
    """

    # Finding-specific fields (universal fields inherited from BaseResource)
    spec: FindingSpec = Field(..., description="Finding specification")  # type: ignore
    finding_context: Context = Field(
        ..., description="Context information for the finding", alias="context"
    )

    model_config = ConfigDict(extra="ignore")

    def __init__(self, **data):
        # Convert spec to FindingSpec if it's a dict
        if "spec" in data and isinstance(data["spec"], dict):
            data["spec"] = FindingSpec(**data["spec"])
        super().__init__(**data)

    @field_validator("*", mode="before")
    @classmethod
    def detect_schema_drift(cls, v, info):
        """Detect and log schema drift for unknown fields."""
        if info.field_name == "spec" and isinstance(v, dict):
            # Log unknown fields for schema drift detection in spec
            known_fields = {
                "project_uuid",
                "last_processed",
                "level",
                "dismiss",
                "remediation",
                "finding_metadata",
                "summary",
                "finding_tags",
                "target_uuid",
                "extra_key",
                "method",
                "target_dependency_package_name",
                "target_dependency_name",
                "target_dependency_version",
                "explanation",
                "remediation_action",
                "source_code_version",
                "reachable_paths",
                "ecosystem",
                "finding_categories",
                "relationship",
                "latest_version",
                "dependency_file_paths",
                "approximation",
                "proposed_version",
                "exceptions",
                "actions",
                "fixing_upgrades",
                "fixing_patch",
                "code_owners",
                "location_urls",
                "call_graph_analysis_type",
            }
            unknown_fields = set(v.keys()) - known_fields
            if unknown_fields:
                logger.warning(
                    f"Schema drift detected in {info.field_name}: "
                    f"unknown fields {unknown_fields}"
                )
        return v


class CreateFindingPayload(BaseModel):
    """Payload for creating a new finding."""

    meta: FindingMeta
    spec: FindingSpec
    context: Context


class UpdateFindingPayload(BaseModel):
    """
    Payload for updating an Endor Labs finding.

    MUTABLE FIELDS (can be updated via PATCH):
    - meta.tags: General resource tags
    - spec.finding_tags: Finding-specific tags
    - spec.dismiss: Dismissal status
    - spec.remediation: Remediation guidance
    - context.tags: Contextual tags

    IMMUTABLE FIELDS (read-only, managed by API):
    - uuid: Unique identifier
    - meta.name: Finding name
    - spec.level: Severity level (set by scan)
    - spec.category: Finding category (set by scan)
    - spec.project_uuid: Associated project (set at creation)
    - spec.finding_metadata: Scan-discovered metadata
    - tenant_meta.namespace: Namespace assignment

    Example:
        >>> payload = UpdateFindingPayload(
        ...     spec=FindingSpec(
        ...         dismiss=True,
        ...         finding_tags=["reviewed", "false-positive"]
        ...     )
        ... )
        >>> finding = update_finding(
        ...     client, namespace, uuid, payload, "spec.dismiss,spec.finding_tags"
        ... )
    """

    meta: Optional[FindingMeta] = Field(None, description="Updated finding metadata")
    spec: Optional[FindingSpec] = Field(
        None, description="Updated finding specification"
    )
    context: Optional[Context] = Field(None, description="Updated finding context")


def _get_finding_ops(client: APIClient) -> BaseResourceOperations:
    """Get BaseResourceOperations instance for findings."""
    return BaseResourceOperations(client, "findings", Finding)


def list_findings(
    client: APIClient,
    tenant_meta_namespace: str,
    list_params: Optional[ListParameters] = None,
) -> List[Finding]:
    """
    List findings in a namespace.

    Args:
        client: APIClient instance
        tenant_meta_namespace: Canonical namespace name (e.g., 'tenant.namespace')
        list_params: Optional list parameters for filtering, pagination, etc.

    Returns:
        List of Finding objects
    """
    ops = _get_finding_ops(client)
    results = ops.list(tenant_meta_namespace, list_params)
    return [Finding(**item.model_dump()) for item in results]  # type: ignore


def get_finding(
    client: APIClient, tenant_meta_namespace: str, finding_uuid: str
) -> Optional[Finding]:
    """
    Get a specific finding by UUID.

    Args:
        client: APIClient instance
        tenant_meta_namespace: Canonical namespace name
        finding_uuid: UUID of the finding to retrieve

    Returns:
        Finding object if found, None otherwise
    """
    ops = _get_finding_ops(client)
    result = ops.get(tenant_meta_namespace, finding_uuid)
    if result:
        return Finding(**result.model_dump())  # type: ignore
    return None


def create_finding(
    client: APIClient, tenant_meta_namespace: str, payload: CreateFindingPayload
) -> Optional[Finding]:
    """
    Create a new finding.

    Args:
        client: APIClient instance
        tenant_meta_namespace: Canonical namespace name
        payload: Finding creation payload

    Returns:
        Created Finding object if successful, None otherwise
    """
    url = f"v1/namespaces/{tenant_meta_namespace}/findings"

    try:
        response = client.post(url, json=payload.model_dump())
        if response:
            data = response.json()
            return Finding(**data)
        return None
    except Exception as e:
        print(f"Error creating finding: {e}")
        return None


def update_finding(
    client: APIClient,
    tenant_meta_namespace: str,
    finding_uuid: str,
    payload: UpdateFindingPayload,
    update_mask: Optional[str] = None,
) -> Optional[Finding]:
    """
    Update an existing finding using partial updates.

    This function supports updating only specific fields using the update_mask
    parameter, which enables efficient partial updates without overwriting
    unchanged fields.

    MUTABLE FIELDS:
    - meta.tags: General resource tags
    - spec.finding_tags: Finding-specific tags
    - spec.dismiss: Dismissal status
    - spec.remediation: Remediation guidance
    - context.tags: Contextual tags

    FIELD MUTABILITY (per OpenAPI spec):
    =====================================
    IMMUTABLE FIELDS (readOnly: true in API spec):
    - uuid: Unique identifier (readOnly: true in UpdateFinding request body)
    - meta.create_time, meta.update_time, meta.upsert_time: Timestamps
      (readOnly: true in v1Meta)
    - meta.kind, meta.version: Resource metadata (readOnly: true in v1Meta)
    - meta.created_by, meta.updated_by: Audit fields (readOnly: true in v1Meta)
    - meta.references, meta.index_data: System-managed fields (readOnly: true in v1Meta)
    - tenant_meta.namespace: Namespace assignment

    MUTABLE FIELDS (NOT readOnly in API spec):
    - meta.name, meta.description, meta.tags: Metadata
    - spec.*: All FindingSpec fields (no readOnly fields in v1FindingSpec)
    - context.tags: Contextual tags

    Args:
        client: APIClient instance
        tenant_meta_namespace: Canonical namespace name
        finding_uuid: UUID of the finding to update
        payload: Finding update payload
        update_mask: Optional comma-separated list of fields to update
            (e.g., "spec.dismiss,spec.finding_tags"). If provided, only these
            fields will be updated. If omitted, all non-None fields in
            payload will be updated.

    Returns:
        Updated Finding object if successful, None otherwise

    Raises:
        requests.exceptions.HTTPError: For API-level errors (403, 404, etc.)
        pydantic.ValidationError: If response data doesn't match expected schema

    Example:
        >>> # Dismiss a finding
        >>> payload = UpdateFindingPayload(
        ...     spec=FindingSpec(dismiss=True)
        ... )
        >>> finding = update_finding(client, namespace, uuid, payload, "spec.dismiss")

        >>> # Add finding tags
        >>> payload = UpdateFindingPayload(
        ...     spec=FindingSpec(finding_tags=["reviewed", "false-positive"])
        ... )
        >>> finding = update_finding(
        ...     client, namespace, uuid, payload, "spec.finding_tags"
        ... )

    Note:
        Tags persist correctly when using update_mask. Without update_mask,
        the API may not persist tag changes reliably.
    """
    try:
        # Get the current finding to include required fields
        current_finding = get_finding(client, tenant_meta_namespace, finding_uuid)
        if not current_finding:
            logger.error(f"Finding {finding_uuid} not found")
            return None

        # Build request data with correct structure
        request_data = {
            "object": {
                "uuid": finding_uuid,
                "tenant_meta": current_finding.tenant_meta.model_dump(),
                "meta": {
                    "name": current_finding.meta.name,  # Required field
                    **(
                        payload.meta.model_dump(exclude_none=True)
                        if payload.meta
                        else {}
                    ),
                },
                "spec": {
                    **current_finding.spec.model_dump(),  # Include all
                    # existing spec fields
                    **(
                        payload.spec.model_dump(exclude_none=True)
                        if payload.spec
                        else {}
                    ),
                },
                "context": (
                    current_finding.context.model_dump()
                    if current_finding.context
                    else {}
                ),
            }
        }

        # Add update_mask if provided for partial updates
        if update_mask:
            request_data["request"] = {"update_mask": update_mask}

        logger.info(f"Updating finding {finding_uuid} with mask: {update_mask}")

        res = client.patch(
            f"v1/namespaces/{tenant_meta_namespace}/findings",
            json=request_data,
            headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
            },
        )

        if res.status_code == 200:
            data = res.json()
            return Finding(**data)
        else:
            logger.error(
                f"Failed to update finding {finding_uuid}: "
                f"{res.status_code} - {res.text}"
            )
            return None
    except Exception as e:
        logger.error(f"Error updating finding {finding_uuid}: {e}", exc_info=True)
        return None


def delete_finding(
    client: APIClient, tenant_meta_namespace: str, finding_uuid: str
) -> bool:
    """
    Delete a finding.

    Args:
        client: APIClient instance
        tenant_meta_namespace: Canonical namespace name
        finding_uuid: UUID of the finding to delete

    Returns:
        True if successful, False otherwise
    """
    url = f"v1/namespaces/{tenant_meta_namespace}/findings/{finding_uuid}"

    try:
        response = client.delete(url)
        return response is not None
    except Exception as e:
        print(f"Error deleting finding {finding_uuid}: {e}")
        return False
