"""
Test cases for Metric resource operations.

Tests GET and LIST operations for Metric resources.
Metrics are typically auto-generated by analytics and are read-only.
"""

import os
import sys

import pytest

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from endor_cockpit.api_client import APIClient
from endor_cockpit.resources import metric
from endor_cockpit.types import ListParameters


@pytest.mark.integration
class TestMetric:
    """Test cases for Metric resource operations."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Set up test environment."""
        self.client = APIClient()
        self.namespace = os.getenv("ENDOR_NAMESPACE", "")

        # Validate namespace is set
        if not self.namespace:
            pytest.skip("ENDOR_NAMESPACE environment variable must be set")

        # Get test data - use parent namespace to access child resources
        parts = self.namespace.split(".")
        self.parent_namespace = parts[0] if len(parts) > 1 else self.namespace

        # List metrics from parent namespace to get available data
        import conftest

        self.metrics = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(
                page_size=conftest.TEST_PAGE_SIZE,
                traverse=True,
            ),
        )
        if not self.metrics:
            pytest.skip("No metrics available for testing")

    def test_metric_list(self):
        """Test LIST metrics operation."""
        print("\n=== TESTING LIST METRICS ===")

        # Test list_metrics with traverse
        metrics_list = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(traverse=True),
        )
        assert isinstance(metrics_list, list), "Should return a list of metrics"
        assert len(metrics_list) > 0, "Should have at least one metric"

        print(f"Found {len(metrics_list)} metrics")

        # Display first few metrics
        for _i, metric_item in enumerate(metrics_list[:5]):
            print(
                f"Metric {metric_item.uuid}: "
                f"{metric_item.meta.name if metric_item.meta else 'N/A'}"
            )
            if metric_item.spec:
                print(f"  Analytic: {metric_item.spec.analytic}")
                if metric_item.spec.metric_values:
                    print(
                        f"  Metric values count: {len(metric_item.spec.metric_values)}"
                    )

    def test_metric_get_by_uuid(self):
        """Test GET metric by UUID operation."""
        print("\n=== TESTING GET METRIC BY UUID ===")

        metric_item = self.metrics[0]
        retrieved_metric = metric.get_metric(
            self.client, self.parent_namespace, metric_item.uuid
        )

        assert retrieved_metric is not None, (
            "Should successfully retrieve metric by UUID"
        )
        assert retrieved_metric.uuid == metric_item.uuid, (
            "Retrieved metric should match original"
        )
        if retrieved_metric.meta and metric_item.meta:
            assert retrieved_metric.meta.name == metric_item.meta.name, (
                "Metric name should match"
            )

        print(f"Successfully retrieved metric: {retrieved_metric.uuid}")
        if retrieved_metric.meta:
            print(f"Metric name: {retrieved_metric.meta.name}")
        if retrieved_metric.spec:
            print(f"Analytic: {retrieved_metric.spec.analytic}")
            if retrieved_metric.spec.metric_values:
                print(
                    f"Metric values: {list(retrieved_metric.spec.metric_values.keys())}"
                )

    def test_metric_filter_by_project(self):
        """Test filtering metrics by project UUID."""
        print("\n=== TESTING FILTER METRICS BY PROJECT ===")

        # Get first metric to extract project UUID
        if not self.metrics:
            pytest.skip("No metrics available for filtering test")

        first_metric = self.metrics[0]
        if not first_metric.spec or not first_metric.spec.project_uuid:
            pytest.skip("Metric has no project_uuid")

        project_uuid = first_metric.spec.project_uuid

        # Filter metrics by project
        list_params = ListParameters(
            filter=f'spec.project_uuid=="{project_uuid}"',
            traverse=True,
        )

        filtered_results = metric.list_metrics(
            self.client, self.parent_namespace, list_params
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        assert len(filtered_results) > 0, (
            "Should have at least one metric for the project"
        )

        # Verify all results belong to the project
        for result in filtered_results:
            assert result.spec.project_uuid == project_uuid, (
                "All filtered results should belong to the project"
            )

        print(f"Found {len(filtered_results)} metrics for project {project_uuid}")

    def test_metric_filter_by_analytic(self):
        """Test filtering metrics by analytic name."""
        print("\n=== TESTING FILTER METRICS BY ANALYTIC ===")

        # Get first metric to extract analytic name
        if not self.metrics:
            pytest.skip("No metrics available for filtering test")

        first_metric = self.metrics[0]
        if not first_metric.spec or not first_metric.spec.analytic:
            pytest.skip("Metric has no analytic")

        analytic_name = first_metric.spec.analytic

        # Filter metrics by analytic
        list_params = ListParameters(
            filter=f'spec.analytic=="{analytic_name}"',
            traverse=True,
        )

        filtered_results = metric.list_metrics(
            self.client, self.parent_namespace, list_params
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        assert len(filtered_results) > 0, (
            "Should have at least one metric for the analytic"
        )

        # Verify all results have the same analytic
        for result in filtered_results:
            assert result.spec.analytic == analytic_name, (
                "All filtered results should have the same analytic"
            )

        print(f"Found {len(filtered_results)} metrics for analytic {analytic_name}")

    def test_metric_with_traverse(self):
        """Test listing metrics with traverse (child namespaces)."""
        print("\n=== TESTING LIST METRICS WITH TRAVERSE ===")

        # List with traverse enabled
        list_params = ListParameters(
            traverse=True,
        )

        metrics_list = metric.list_metrics(
            self.client, self.parent_namespace, list_params
        )

        assert isinstance(metrics_list, list), "Should return a list of metrics"
        print(f"Found {len(metrics_list)} metrics (with traverse)")

    def test_metric_field_validation(self):
        """Test field validation and required fields."""
        metric_item = self.metrics[0]

        # Verify required fields are present
        assert metric_item.uuid is not None
        assert metric_item.meta is not None
        assert metric_item.meta.name is not None
        assert metric_item.spec is not None
        assert metric_item.spec.analytic is not None
        assert metric_item.spec.project_uuid is not None
        assert metric_item.spec.metric_values is not None
        assert len(metric_item.spec.metric_values) > 0

    def test_metric_pagination(self):
        """Test pagination capabilities."""
        # Test with page size
        paginated_results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(
                page_size=5, traverse=True
            ),
        )
        assert isinstance(paginated_results, list)
        assert len(paginated_results) > 0

    def test_metric_error_handling(self):
        """Test error handling for invalid UUID."""
        # Test with invalid UUID
        invalid_metric = metric.get_metric(
            self.client, self.parent_namespace, "invalid-uuid"
        )
        assert invalid_metric is None

    def test_metric_analytic_distribution(self):
        """Test and analyze metric analytic distribution."""
        metrics_list = metric.list_metrics(self.client, self.parent_namespace)

        analytic_counts = {}

        for m in metrics_list:
            if m.spec:
                analytic = str(m.spec.analytic) if m.spec.analytic else "Unknown"
                analytic_counts[analytic] = analytic_counts.get(analytic, 0) + 1

        print("\n=== Metric Analytic Distribution ===")
        print("Analytic distribution:")
        for analytic, count in analytic_counts.items():
            print(f"  {analytic}: {count}")

        assert len(metrics_list) > 0

