"""Test cases for Metric resource operations.

Tests GET and LIST operations for Metric resources.
Metrics are typically auto-generated by analytics and are read-only.
"""

import os
import sys

import pytest

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from endor_cockpit.api_client import APIClient
from endor_cockpit.resources import metric
from endor_cockpit.types import ListParameters


@pytest.mark.integration
class TestMetric:
    """Test cases for Metric resource operations."""

    @pytest.fixture(autouse=True)
    def setup_fast(self) -> None:
        """Fast setup: client and namespace only (runs before each test)."""
        self.client = APIClient(auth_method="api-key")
        import conftest

        self.namespace = os.getenv("ENDOR_NAMESPACE", conftest.TEST_NAMESPACE_DEFAULT)

        # Validate namespace is set
        if not self.namespace:
            pytest.skip("ENDOR_NAMESPACE environment variable must be set")

        # Get test data - use parent namespace to access child resources
        parts = self.namespace.split(".")
        self.parent_namespace = parts[0] if len(parts) > 1 else self.namespace

    @pytest.fixture
    def sample_metric(self):
        """Fetch minimal sample data (1 item) for UUID operations.

        Function-scoped but only fetches when explicitly requested by tests.
        Uses traverse=True to search across all namespaces, matching the
        pattern used in test_metric_list.
        """
        # Fetch 1 item with traverse to find metrics across namespaces
        results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(traverse=True, page_size=1),
            max_pages=1,
        )
        if not results:
            pytest.skip("No metrics available for testing")
        return results[0]  # Return single item, not list

    def test_metric_list(self) -> None:
        """Test LIST metrics operation."""
        print("\n=== TESTING LIST METRICS ===")

        # Test list_metrics with traverse
        import conftest

        metrics_list = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(
                traverse=True,
                page_size=conftest.TEST_TRAVERSE_PAGE_SIZE,
            ),
            max_pages=conftest.TEST_MAX_PAGES_TRAVERSE,
        )
        assert isinstance(metrics_list, list), "Should return a list of metrics"
        assert len(metrics_list) > 0, "Should have at least one metric"

        print(f"Found {len(metrics_list)} metrics")

        # Display first few metrics
        for _i, metric_item in enumerate(metrics_list[:5]):
            print(
                f"Metric {metric_item.uuid}: "
                f"{metric_item.meta.name if metric_item.meta else 'N/A'}"
            )
            if metric_item.spec:
                print(f"  Analytic: {metric_item.spec.analytic}")
                if metric_item.spec.metric_values:
                    print(
                        f"  Metric values count: {len(metric_item.spec.metric_values)}"
                    )

    def test_metric_get_by_uuid(self, sample_metric) -> None:
        """Test GET metric by UUID operation."""
        print("\n=== TESTING GET METRIC BY UUID ===")

        metric_item = sample_metric
        # Use the metric's actual namespace
        # (may be in child namespace when traverse=True)
        metric_namespace = (
            metric_item.tenant_meta.namespace
            if metric_item.tenant_meta
            else self.parent_namespace
        )
        retrieved_metric = metric.get_metric(
            self.client, metric_namespace, metric_item.uuid
        )

        assert retrieved_metric is not None, (
            "Should successfully retrieve metric by UUID"
        )
        assert retrieved_metric.uuid == metric_item.uuid, (
            "Retrieved metric should match original"
        )
        if retrieved_metric.meta and metric_item.meta:
            assert retrieved_metric.meta.name == metric_item.meta.name, (
                "Metric name should match"
            )

        print(f"Successfully retrieved metric: {retrieved_metric.uuid}")
        if retrieved_metric.meta:
            print(f"Metric name: {retrieved_metric.meta.name}")
        if retrieved_metric.spec:
            print(f"Analytic: {retrieved_metric.spec.analytic}")
            if retrieved_metric.spec.metric_values:
                print(
                    f"Metric values: {list(retrieved_metric.spec.metric_values.keys())}"
                )

    def test_metric_filter_by_project(self, sample_metric) -> None:
        """Test filtering metrics by project UUID."""
        print("\n=== TESTING FILTER METRICS BY PROJECT ===")

        # Get first metric to extract project UUID
        first_metric = sample_metric
        if not first_metric.spec or not first_metric.spec.project_uuid:
            pytest.skip("Metric has no project_uuid")

        project_uuid = first_metric.spec.project_uuid

        # Filter metrics by project
        import conftest

        list_params = ListParameters(
            filter=f'spec.project_uuid=="{project_uuid}"',
            traverse=True,
            page_size=conftest.TEST_TRAVERSE_PAGE_SIZE,
        )

        filtered_results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params,
            max_pages=conftest.TEST_MAX_PAGES_TRAVERSE,
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        assert len(filtered_results) > 0, (
            "Should have at least one metric for the project"
        )

        # Verify all results belong to the project
        for result in filtered_results:
            assert result.spec.project_uuid == project_uuid, (
                "All filtered results should belong to the project"
            )

        print(f"Found {len(filtered_results)} metrics for project {project_uuid}")

    def test_metric_filter_by_analytic(self, sample_metric) -> None:
        """Test filtering metrics by analytic name."""
        print("\n=== TESTING FILTER METRICS BY ANALYTIC ===")

        # Get first metric to extract analytic name
        first_metric = sample_metric
        if not first_metric.spec or not first_metric.spec.analytic:
            pytest.skip("Metric has no analytic")

        analytic_name = first_metric.spec.analytic

        # Filter metrics by analytic
        import conftest

        list_params = ListParameters(
            filter=f'spec.analytic=="{analytic_name}"',
            traverse=True,
            page_size=conftest.TEST_TRAVERSE_PAGE_SIZE,
        )

        filtered_results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params,
            max_pages=conftest.TEST_MAX_PAGES_TRAVERSE,
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        assert len(filtered_results) > 0, (
            "Should have at least one metric for the analytic"
        )

        # Verify all results have the same analytic
        for result in filtered_results:
            assert result.spec.analytic == analytic_name, (
                "All filtered results should have the same analytic"
            )

        print(f"Found {len(filtered_results)} metrics for analytic {analytic_name}")

    def test_metric_with_traverse(self) -> None:
        """Test listing metrics with traverse (child namespaces)."""
        print("\n=== TESTING LIST METRICS WITH TRAVERSE ===")

        # List with traverse enabled
        import conftest

        list_params = ListParameters(
            traverse=True,
            page_size=conftest.TEST_TRAVERSE_PAGE_SIZE,
        )

        metrics_list = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params,
            max_pages=conftest.TEST_MAX_PAGES_TRAVERSE,
        )

        assert isinstance(metrics_list, list), "Should return a list of metrics"
        print(f"Found {len(metrics_list)} metrics (with traverse)")

    def test_metric_pagination(self) -> None:
        """Test pagination capabilities."""
        # Test with page size
        import conftest

        paginated_results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(page_size=5, traverse=True),
            max_pages=conftest.TEST_MAX_PAGES_TRAVERSE,
        )
        assert isinstance(paginated_results, list)
        assert len(paginated_results) > 0

    def test_metric_error_handling(self) -> None:
        """Test error handling for invalid UUID."""
        # Test with invalid UUID format - should raise ValidationError
        # (server returns HTTP 400 with gRPC code 3 INVALID_ARGUMENT)
        from endor_cockpit.exceptions import ValidationError

        with pytest.raises(ValidationError) as exc_info:
            metric.get_metric(self.client, self.parent_namespace, "invalid-uuid")
        assert exc_info.value.resource_uuid == "invalid-uuid"
        assert exc_info.value.operation == "get"
        assert exc_info.value.status_code == 400
