"""Authentication workflow helpers for login counts, auth RCA, and session setup.

See :mod:`endorlabs.workflows.auth.authentication_log`,
:mod:`endorlabs.workflows.auth.authorization_policy`,
:mod:`endorlabs.workflows.auth.authorization_policy_form`,
:mod:`endorlabs.workflows.auth.credential_expiry`, and
:mod:`endorlabs.workflows.auth.session` module docstrings for composition layers
and tenant-scoping callouts. Skill playbooks: ``endor-auth-setup``,
``endor-auth-login-count``, ``endor-auth-credential-expiry``,
``endor-audit-authorization-policies``, ``endor-troubleshoot-authlog``,
``endor-sso-integration-validation-troubleshooting``.
"""

from __future__ import annotations

from .authentication_log import (
    API_KEY_URI_FRAGMENTS,
    AUTHENTICATION_LOG_INVESTIGATION_MASK,
    AUTHENTICATION_LOG_LIST_MASK,
    INTERACTIVE_URI_REGEX,
    SSO_URI_FRAGMENTS,
    LoginActivityRow,
    auth_log_filter,
    auth_log_snapshot,
    count_logins_from_groups,
    count_logins_from_rows,
    create_time_lower_bound_filter,
    extract_user_identifiers,
    fetch_last_logins_for_identities,
    filter_auth_logs_by_email,
    interactive_uri_filter,
    is_api_key_noise,
    is_sso_login_uri,
    list_auth_logs,
    normalize_auth_log,
    parse_claims_from_group_bucket,
    parse_create_time,
    primary_identity,
    probe_auth_logs,
)
from .authorization_policy import (
    AuthorizationPolicyRecord,
    ClaimNamespaceReport,
    ClaimScopeEntry,
    NamespaceScope,
    OverlapReport,
    build_claim_namespace_map,
    expand_namespace_scope,
    list_authorization_policies,
    normalize_authorization_policy,
)
from .authorization_policy_form import (
    FormFinding,
    audit_authorization_policy_forms,
    audit_clause,
    audit_policy_record,
    audit_target_namespaces,
)
from .credential_expiry import (
    CredentialExpiryRow,
    audit_api_key_expiry,
    build_credential_expiry_row,
    classify_expiration,
    expiry_upper_bound_filter,
    list_api_keys,
    parse_expiration_time,
)
from .dotenv import read_dotenv_value, read_env_or_dotenv, upsert_dotenv_key
from .env_resolution import resolve_sso_tenant, sso_tenant_from_namespace
from .session import (
    AuthEnvironmentScan,
    AuthVerification,
    BrowserAuthMethod,
    EndorctlProbe,
    TokenRefreshResult,
    build_browser_auth_kwargs,
    probe_endorctl,
    refresh_token_to_dotenv,
    resolve_api_environment,
    scan_auth_env,
    verify_auth,
)

__all__ = [
    "API_KEY_URI_FRAGMENTS",
    "AUTHENTICATION_LOG_INVESTIGATION_MASK",
    "AUTHENTICATION_LOG_LIST_MASK",
    "INTERACTIVE_URI_REGEX",
    "SSO_URI_FRAGMENTS",
    "AuthEnvironmentScan",
    "AuthVerification",
    "AuthorizationPolicyRecord",
    "BrowserAuthMethod",
    "ClaimNamespaceReport",
    "ClaimScopeEntry",
    "CredentialExpiryRow",
    "EndorctlProbe",
    "FormFinding",
    "LoginActivityRow",
    "NamespaceScope",
    "OverlapReport",
    "TokenRefreshResult",
    "audit_api_key_expiry",
    "audit_authorization_policy_forms",
    "audit_clause",
    "audit_policy_record",
    "audit_target_namespaces",
    "auth_log_filter",
    "auth_log_snapshot",
    "build_browser_auth_kwargs",
    "build_claim_namespace_map",
    "build_credential_expiry_row",
    "classify_expiration",
    "count_logins_from_groups",
    "count_logins_from_rows",
    "create_time_lower_bound_filter",
    "expand_namespace_scope",
    "expiry_upper_bound_filter",
    "extract_user_identifiers",
    "fetch_last_logins_for_identities",
    "filter_auth_logs_by_email",
    "interactive_uri_filter",
    "is_api_key_noise",
    "is_sso_login_uri",
    "list_api_keys",
    "list_auth_logs",
    "list_authorization_policies",
    "normalize_auth_log",
    "normalize_authorization_policy",
    "parse_claims_from_group_bucket",
    "parse_create_time",
    "parse_expiration_time",
    "primary_identity",
    "probe_auth_logs",
    "probe_endorctl",
    "read_dotenv_value",
    "read_env_or_dotenv",
    "refresh_token_to_dotenv",
    "resolve_api_environment",
    "resolve_sso_tenant",
    "scan_auth_env",
    "sso_tenant_from_namespace",
    "upsert_dotenv_key",
    "verify_auth",
]
