"""Generate src/endorlabs/generated/route_contract.py from overlay YAML."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from sync.path_safety import find_repo_root

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]


def _load_overlay(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        payload = yaml.safe_load(text)
    else:
        raise RuntimeError("PyYAML required: uv sync --group dev")
    if not isinstance(payload, dict):
        raise ValueError(f"Expected mapping in {path}")
    return payload


def _edge_list(contract: dict[str, Any]) -> list[dict[str, Any]]:
    edges = contract.get("edges")
    if not isinstance(edges, list):
        raise ValueError("overlay must contain edges list")
    return [e for e in edges if isinstance(e, dict)]


def _build_route_table(edges: list[dict[str, Any]]) -> dict[str, tuple[str, ...]]:
    table: dict[str, list[str]] = {}
    for edge in edges:
        public = edge.get("public_method")
        if not isinstance(public, str) or "." not in public:
            continue
        attr, _ = public.split(".", 1)
        table.setdefault(attr, []).append(str(edge["id"]))
    return {k: tuple(v) for k, v in sorted(table.items())}


def _build_relationship_map(
    edges: list[dict[str, Any]],
) -> list[tuple[str, str, str, str, str]]:
    """(from_kind, to_kind, public_method, edge_id, edge_kind) rows."""
    rows: list[tuple[str, str, str, str, str]] = []
    for edge in edges:
        public = edge.get("public_method")
        if not isinstance(public, str):
            continue
        rows.append(
            (
                str(edge.get("from_kind", "")),
                str(edge.get("to_kind", "")),
                public,
                str(edge.get("id", "")),
                str(edge.get("edge", "")),
            )
        )
    return sorted(rows, key=lambda r: (r[2], r[3]))


def render_module(contract: dict[str, Any]) -> str:
    edges = _edge_list(contract)
    json_text = json.dumps({"edges": edges}, indent=2)
    table = _build_route_table(edges)
    rel_map = _build_relationship_map(edges)
    return f'''# Auto-generated by devtools/generate_route_contract.py — do not edit by hand.
"""Generated route contract for CRUD+ facade wiring."""

from __future__ import annotations

import json

from endorlabs.operations.route_contract import RouteContract

ROUTE_CONTRACT_JSON = {json_text!r}

ROUTE_CONTRACT: RouteContract = RouteContract.from_dict(json.loads(ROUTE_CONTRACT_JSON))

ROUTE_TABLE_BY_ATTR: dict[str, tuple[str, ...]] = {repr(table)}

ROUTE_RELATIONSHIP_MAP: tuple[tuple[str, str, str, str, str], ...] = {repr(tuple(rel_map))}
'''


def render_markdown(contract: dict[str, Any]) -> str:
    edges = _edge_list(contract)
    lines = [
        "# Resource route map (generated)",
        "",
        "Contract-driven **CRUD+** edges between first-class facades. "
        "Regenerate with `uv run python devtools/generate_route_contract.py`.",
        "",
        "Source overlay: `devtools/model_sync_profiles/route_contract_overlay.yaml`.",
        "",
        "## Relationship table",
        "",
        "| From | To | Public method | Edge id | Wire kind | Tier |",
        "|------|-----|---------------|---------|-----------|------|",
    ]
    for edge in edges:
        public = edge.get("public_method", "")
        lines.append(
            f"| {edge.get('from_kind', '')} | {edge.get('to_kind', '')} | "
            f"`{public}` | `{edge.get('id', '')}` | `{edge.get('edge', '')}` | "
            f"{edge.get('tier', 'B')} |"
        )
    lines.extend(
        [
            "",
            "## Usage",
            "",
            "Route methods return `RouteResult` with `.values` (list routes) or "
            "`.value` (GET/stitch). Namespace is taken from the source resource unless "
            "`namespace=` is passed.",
            "",
            "```python",
            "project = client.Project.lookup(name='my-repo', namespace=ns)",
            "findings = client.Finding.list_by_project(project, max_pages=1)",
            "scans = client.ScanResult.list_by_project(project, max_pages=1)",
            "if scans.values:",
            "    by_scan = client.Finding.list_by_scan(scans.values[0], max_pages=1)",
            "dm = client.Finding.to_dependency_metadata(finding_row)",
            "```",
            "",
            "See [facade-helpers.md](../guides/facade-helpers.md) and "
            "[contracts.md](../contracts.md#resource-routes-crud).",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    repo = find_repo_root(start=Path(__file__).resolve().parent)
    overlay = repo / "devtools" / "model_sync_profiles" / "route_contract_overlay.yaml"
    contract = _load_overlay(overlay)
    py_out = repo / "src" / "endorlabs" / "generated" / "route_contract.py"
    md_out = repo / "docs" / "generated-reference" / "resource-routes.md"
    py_out.write_text(render_module(contract), encoding="utf-8")
    md_out.write_text(render_markdown(contract), encoding="utf-8")
    print(f"Wrote {py_out.relative_to(repo)}")
    print(f"Wrote {md_out.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
