"""Unit tests for skill mirror sync helpers."""

from __future__ import annotations

import json
from pathlib import Path

from endorlabs.context import _sync


def test_resolve_skill_sync_targets_supports_explicit_targets() -> None:
    """Explicit targets should resolve without repository heuristics."""
    assert _sync._resolve_skill_sync_targets(target="cursor") == ("cursor",)
    assert _sync._resolve_skill_sync_targets(target="both") == (
        "cursor",
        "claude",
    )


def test_sync_agent_skills_mirrors_tree_and_prunes_stale(tmp_path: Path) -> None:
    """Skill sync should mirror current endor-* files and delete removed ones."""
    source_dir = tmp_path / "agent-knowledge" / "skills"
    repo_root = tmp_path / "repo"
    target_dir = repo_root / ".cursor" / "skills"
    source_file = source_dir / "endor-demo-skill" / "SKILL.md"
    nested_file = source_dir / "endor-demo-skill" / "guide.md"

    source_file.parent.mkdir(parents=True, exist_ok=True)
    repo_root.mkdir()
    source_file.write_text("# Demo\n", encoding="utf-8")
    nested_file.write_text("details\n", encoding="utf-8")

    stale_file = target_dir / "endor-obsolete" / "old.md"
    stale_file.parent.mkdir(parents=True, exist_ok=True)
    stale_file.write_text("stale\n", encoding="utf-8")

    synced = _sync.sync_agent_skills(
        repo_root=repo_root,
        target="cursor",
        source_dir=source_dir,
    )

    assert synced == {"cursor": target_dir}
    assert (target_dir / "endor-demo-skill" / "SKILL.md").read_text(
        encoding="utf-8"
    ) == ("# Demo\n")
    assert (target_dir / "endor-demo-skill" / "guide.md").read_text(
        encoding="utf-8"
    ) == ("details\n")
    assert not stale_file.exists()


def test_sync_agent_skills_preserves_non_endor_skills(tmp_path: Path) -> None:
    """Non-endor runtime skills must not be deleted during mirror sync."""
    source_dir = tmp_path / "sdk" / "skills"
    repo_root = tmp_path / "repo"
    target_dir = repo_root / ".cursor" / "skills"
    endor_skill = source_dir / "endor-demo-skill" / "SKILL.md"
    endor_skill.parent.mkdir(parents=True, exist_ok=True)
    repo_root.mkdir()
    endor_skill.write_text("# Endor\n", encoding="utf-8")

    foreign_skill = target_dir / "create-hook" / "SKILL.md"
    foreign_skill.parent.mkdir(parents=True, exist_ok=True)
    foreign_skill.write_text("# Foreign\n", encoding="utf-8")

    stale_endor_skill = target_dir / "endor-retired" / "SKILL.md"
    stale_endor_skill.parent.mkdir(parents=True, exist_ok=True)
    stale_endor_skill.write_text("# Retired\n", encoding="utf-8")

    _sync.sync_agent_skills(
        repo_root=repo_root,
        target="cursor",
        source_dir=source_dir,
    )

    assert foreign_skill.read_text(encoding="utf-8") == "# Foreign\n"
    assert not stale_endor_skill.exists()
    assert (target_dir / "endor-demo-skill" / "SKILL.md").exists()


def test_skill_target_dir_returns_none_for_claude(tmp_path: Path) -> None:
    """Claude target does not use a skills directory mirror."""
    assert _sync._skill_target_dir(tmp_path, "claude") is None
    assert (
        _sync._skill_target_dir(tmp_path, "cursor") == tmp_path / ".cursor" / "skills"
    )


def test_strip_yaml_frontmatter_removes_header() -> None:
    """Frontmatter stripping should return body only."""
    content = "---\nid: demo\n---\n\n# Body\n"
    assert _sync._strip_yaml_frontmatter(content) == "# Body\n"
    assert _sync._strip_yaml_frontmatter("# No frontmatter\n") == "# No frontmatter\n"


def test_sync_agent_skills_claude_generates_claude_md(tmp_path: Path) -> None:
    """Claude sync should generate CLAUDE.md and slash commands, not .claude/skills/."""
    sdk_root = tmp_path / "sdk"
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    rule_path = sdk_root / "rules" / "endor-demo-rule.md"
    rule_path.parent.mkdir(parents=True)
    rule_path.write_text(
        "---\nid: endor-demo-rule\n---\n\n## Demo rule body\n",
        encoding="utf-8",
    )

    skill_dir = sdk_root / "skills" / "endor-demo-skill"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("# Skill\n", encoding="utf-8")

    manifest = {
        "bootstrap": {"rule_ids": ["endor-demo-rule"]},
        "skills": [
            {
                "id": "endor-demo-skill",
                "name": "endor-demo-skill",
                "description": "Demo skill for Claude sync tests.",
            }
        ],
    }
    (sdk_root / "MANIFEST.json").write_text(json.dumps(manifest), encoding="utf-8")
    (sdk_root / "INDEX.md").write_text("# Index\n", encoding="utf-8")

    synced = _sync.sync_agent_skills(
        repo_root=repo_root,
        target="claude",
        source_dir=sdk_root / "skills",
    )

    claude_md = repo_root / "CLAUDE.md"
    assert synced == {"claude": claude_md}
    assert claude_md.exists()
    assert "Auto-generated by `endorlabs.init" in claude_md.read_text(encoding="utf-8")
    assert "### endor-demo-rule" in claude_md.read_text(encoding="utf-8")
    assert "| endor-demo-skill |" in claude_md.read_text(encoding="utf-8")
    assert not (repo_root / ".claude" / "skills").exists()

    command_path = repo_root / ".claude" / "commands" / "endor-demo-skill.md"
    assert command_path.exists()
    assert "Demo skill for Claude sync tests." in command_path.read_text(
        encoding="utf-8"
    )


def test_sync_agent_skills_claude_skips_user_managed_claude_md(tmp_path: Path) -> None:
    """User-managed CLAUDE.md must not be overwritten."""
    sdk_root = tmp_path / "sdk"
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    sdk_root.mkdir()

    (sdk_root / "MANIFEST.json").write_text(
        json.dumps({"bootstrap": {"rule_ids": []}, "skills": []}),
        encoding="utf-8",
    )
    (sdk_root / "INDEX.md").write_text("# Index\n", encoding="utf-8")

    claude_md = repo_root / "CLAUDE.md"
    user_content = "# My custom Claude instructions\n"
    claude_md.write_text(user_content, encoding="utf-8")

    synced = _sync.sync_agent_skills(
        repo_root=repo_root,
        target="claude",
        source_dir=sdk_root,
    )

    assert synced == {"claude": claude_md}
    assert claude_md.read_text(encoding="utf-8") == user_content


def test_sync_agent_skills_both_cursor_and_claude(tmp_path: Path) -> None:
    """Both target should mirror cursor skills and generate CLAUDE.md."""
    sdk_root = tmp_path / "sdk"
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    skill_dir = sdk_root / "skills" / "endor-demo-skill"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("# Skill\n", encoding="utf-8")

    (sdk_root / "MANIFEST.json").write_text(
        json.dumps({"bootstrap": {"rule_ids": []}, "skills": []}),
        encoding="utf-8",
    )
    (sdk_root / "INDEX.md").write_text("# Index\n", encoding="utf-8")

    synced = _sync.sync_agent_skills(
        repo_root=repo_root,
        target="both",
        source_dir=sdk_root / "skills",
    )

    assert synced["cursor"] == repo_root / ".cursor" / "skills"
    assert synced["claude"] == repo_root / "CLAUDE.md"
    assert (synced["cursor"] / "endor-demo-skill" / "SKILL.md").exists()
    assert synced["claude"].exists()
