"""Core sync logic for context bootstrap.

Downloads OpenAPI for local contract work and materializes agent knowledge.
Product user documentation is served via the Docs MCP server (not scraped).
"""

from __future__ import annotations

import json
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Literal, cast

if TYPE_CHECKING:
    from endorlabs.api_client import APIClient

from endorlabs.utils.logging_config import get_resource_logger
from endorlabs.utils.path_safety import safe_write_text

from ._project_context import warn_agent_defer_gitignore_to_user
from .models import InitStatus
from .paths import (
    DEFAULT_CONTEXT_DIR,
    SDK_DIRNAME,
    context_json_path,
    platform_openapi_path,
    sdk_dir,
)

logger = get_resource_logger(__name__)

OPENAPI_PATH = "/download/openapiv2.swagger.json"
DEFAULT_OPENAPI_FILENAME = "openapiv2.swagger.json"
SKILLS_TARGETS: tuple[str, ...] = ("cursor", "claude")
MANAGED_SKILL_PREFIX = "endor-"
CLAUDE_MD_AUTO_GENERATED_MARKER = "Auto-generated by `endorlabs.init"
SkillSyncMode = Literal["none", "cursor", "claude", "both"]
CONTEXT_JSON_SCHEMA_VERSION = 1


def _normalize_skill_sync_mode(target: str) -> SkillSyncMode:
    """Validate and normalize a skill sync mode string."""
    normalized = target.strip().lower()
    valid_targets = {"none", "cursor", "claude", "both"}
    if normalized not in valid_targets:
        raise ValueError(
            f"Unsupported sync_skills value {target!r}. "
            "Expected one of: none, cursor, claude, both."
        )
    return cast("SkillSyncMode", normalized)


def _skill_target_dir(repo_root: Path, target: str) -> Path | None:
    """Return the runtime skills directory for a target host, or None if different."""
    if target == "cursor":
        return repo_root / ".cursor" / "skills"
    if target == "claude":
        return None  # Claude uses CLAUDE.md, not a skills directory
    return None


def _resolve_agent_knowledge_root(source_dir: Path) -> Path:
    """Return agent-knowledge root (MANIFEST, rules/) from skills or sdk path."""
    if source_dir.name == "skills":
        return source_dir.parent
    return source_dir


def _strip_yaml_frontmatter(content: str) -> str:
    """Remove YAML frontmatter from markdown content."""
    if not content.startswith("---"):
        return content
    parts = content.split("---", 2)
    if len(parts) >= 3:
        return parts[2].lstrip("\n")
    return content


def _render_claude_md_template(
    *,
    embedded_rules: list[str],
    skill_table: str,
    sdk_index_path: Path,
) -> str:
    """Render CLAUDE.md content from components."""
    _ = sdk_index_path
    rules_section = "\n\n".join(embedded_rules)

    return f"""# Endor Labs SDK

> Auto-generated by `endorlabs.init(sync_skills="claude")`. Do not edit manually.

## Critical Rules

{rules_section}

## Available Skills

{skill_table}

For detailed skill playbooks, see `.endorlabs-context/sdk/skills/<id>/SKILL.md`
or call `endorlabs.agent_knowledge_index_path()`.

## Quick Reference

- **Client:** `client = endorlabs.Client(tenant="namespace")`
- **List:** `client.Project.list(traverse=True, max_pages=1)`
- **Discovery:** `client.Project.search_by_name("github.com/org/repo", traverse=True)`
- **Findings:** `client.Finding.list_by_project(project, filter=...)`

## See Also

- [AGENTS.md](AGENTS.md) — full integration guide
- [docs/contracts.md](docs/contracts.md) — normative SDK behavior
"""


def _sync_claude_context(
    *,
    repo_root: Path,
    source_dir: Path,
) -> Path:
    """Generate CLAUDE.md with embedded rules and skill index for Claude Code."""
    output_path = repo_root / "CLAUDE.md"

    if output_path.exists():
        content = output_path.read_text(encoding="utf-8")
        if CLAUDE_MD_AUTO_GENERATED_MARKER not in content:
            logger.warning(
                "CLAUDE.md exists but appears user-managed. "
                "Skipping generation. Delete or add marker to allow overwrite."
            )
            return output_path

    manifest_path = source_dir / "MANIFEST.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    bootstrap_rule_ids = manifest.get("bootstrap", {}).get("rule_ids", [])
    embedded_rules: list[str] = []
    for rule_id in bootstrap_rule_ids:
        rule_path = source_dir / "rules" / f"{rule_id}.md"
        if rule_path.exists():
            rule_content = _strip_yaml_frontmatter(
                rule_path.read_text(encoding="utf-8")
            )
            embedded_rules.append(f"### {rule_id}\n\n{rule_content}")

    skills = manifest.get("skills", [])
    skill_rows = [
        f"| {skill['id']} | {skill.get('description', '')[:80]} |" for skill in skills
    ]
    skill_table = "| Skill | Description |\n|-------|-------------|\n" + "\n".join(
        skill_rows
    )

    claude_md = _render_claude_md_template(
        embedded_rules=embedded_rules,
        skill_table=skill_table,
        sdk_index_path=source_dir / "INDEX.md",
    )

    _ = safe_write_text(repo_root, output_path, claude_md)
    logger.info("Generated CLAUDE.md at %s", output_path)

    commands_dir = repo_root / ".claude" / "commands"
    _ = commands_dir.mkdir(parents=True, exist_ok=True)
    for skill in skills:
        command_path = commands_dir / f"{skill['id']}.md"
        command_content = (
            f"# {skill['name']}\n\n"
            f"{skill['description']}\n\n"
            f"See: .endorlabs-context/sdk/skills/{skill['id']}/SKILL.md"
        )
        _ = safe_write_text(repo_root, command_path, command_content)

    return output_path


def _resolve_skill_sync_targets(
    *,
    target: SkillSyncMode,
) -> tuple[str, ...]:
    """Resolve a sync mode to concrete runtime target names."""
    if target == "none":
        return ()
    if target == "both":
        return SKILLS_TARGETS
    if target in SKILLS_TARGETS:
        return (target,)
    return ()


def _managed_skill_rel_path(rel_path: Path) -> bool:
    """Return True when *rel_path* is under an Endor-managed skill directory."""
    top = rel_path.parts[0] if rel_path.parts else ""
    return top.startswith(MANAGED_SKILL_PREFIX)


def _prune_stale_skill_files(
    *,
    target_dir: Path,
    expected_rel_paths: set[str],
) -> None:
    """Remove stale Endor-managed skill files no longer present in the source tree."""
    if not target_dir.exists():
        return
    base_resolved = target_dir.resolve()
    stale_files = [
        path
        for path in target_dir.rglob("*")
        if path.is_file()
        and _managed_skill_rel_path(path.relative_to(target_dir))
        and path.relative_to(target_dir).as_posix() not in expected_rel_paths
    ]
    for path in stale_files:
        resolved = path.resolve()
        if not resolved.is_relative_to(base_resolved):
            continue
        resolved.unlink()
        parent = resolved.parent
        while parent != base_resolved and parent.exists():
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent


def _mirror_skill_tree(source_dir: Path, target_dir: Path) -> int:
    """Mirror Endor-managed (``endor-*``) skills into a runtime directory."""
    if not source_dir.exists():
        raise FileNotFoundError(f"Skills source directory does not exist: {source_dir}")
    target_dir.mkdir(parents=True, exist_ok=True)
    base_resolved = target_dir.resolve()
    expected_rel_paths: set[str] = set()
    mirrored_files = 0

    for skill_dir in sorted(source_dir.iterdir()):
        if not skill_dir.is_dir():
            continue
        if not skill_dir.name.startswith(MANAGED_SKILL_PREFIX):
            logger.debug(
                "Skipping non-managed skill directory during mirror: %s",
                skill_dir.name,
            )
            continue
        for source_path in skill_dir.rglob("*"):
            if not source_path.is_file():
                continue
            rel_path = source_path.relative_to(source_dir)
            expected_rel_paths.add(rel_path.as_posix())
            dest_path = target_dir / rel_path
            resolved_dest = dest_path.resolve()
            if not resolved_dest.is_relative_to(base_resolved):
                raise ValueError(
                    "Skill mirror target "
                    f"{resolved_dest} escapes base directory {base_resolved}"
                )
            resolved_dest.parent.mkdir(parents=True, exist_ok=True)
            _ = shutil.copy2(source_path, resolved_dest)
            mirrored_files += 1

    _prune_stale_skill_files(
        target_dir=target_dir,
        expected_rel_paths=expected_rel_paths,
    )
    return mirrored_files


def sync_agent_skills(
    *,
    repo_root: str | Path = ".",
    target: SkillSyncMode = "none",
    source_dir: str | Path | None = None,
) -> dict[str, Path]:
    """Sync agent knowledge into runtime discovery paths.

    - cursor: mirrors endor-* skills to .cursor/skills/
    - claude: generates CLAUDE.md with embedded rules + skill index
    """
    repo_root_path = Path(repo_root)
    normalized_target = _normalize_skill_sync_mode(target)
    resolved_targets = _resolve_skill_sync_targets(
        target=normalized_target,
    )
    if not resolved_targets:
        logger.info(
            "Skill sync skipped for target=%s (no runtime target resolved).", target
        )
        return {}

    source_root = (
        Path(source_dir)
        if source_dir is not None
        else _resolve_skill_source_root(repo_root_path)
    )
    if not source_root.is_absolute():
        source_root = repo_root_path / source_root

    agent_knowledge_root = _resolve_agent_knowledge_root(source_root)

    synced_paths: dict[str, Path] = {}
    for resolved_target in resolved_targets:
        if resolved_target == "cursor":
            target_dir = _skill_target_dir(repo_root_path, resolved_target)
            assert target_dir is not None
            mirrored_files = _mirror_skill_tree(source_root, target_dir)
            logger.info(
                "Synced %d skill files to %s runtime path %s",
                mirrored_files,
                resolved_target,
                target_dir,
            )
            synced_paths[resolved_target] = target_dir

        elif resolved_target == "claude":
            claude_md_path = _sync_claude_context(
                repo_root=repo_root_path,
                source_dir=agent_knowledge_root,
            )
            synced_paths[resolved_target] = claude_md_path

    return synced_paths


def _resolve_skill_source_root(repo_root_path: Path) -> Path:
    """Resolve skill mirror source from materialized sdk/skills or wheel bundle."""
    materialized = repo_root_path / DEFAULT_CONTEXT_DIR / SDK_DIRNAME / "skills"
    if materialized.is_dir():
        return materialized
    from endorlabs.agent_knowledge import agent_knowledge_dir

    return agent_knowledge_dir() / "skills"


def materialize_agent_knowledge(
    output_dir: str | Path,
    *,
    force: bool = False,
) -> Path:
    """Copy the wheel-shipped agent knowledge package into context sdk/."""
    from endorlabs.agent_knowledge import agent_knowledge_dir

    output_path = Path(output_dir)
    dest = sdk_dir(output_path)
    source = agent_knowledge_dir()
    if dest.exists() and not force:
        logger.info(
            "Agent knowledge already materialized: %s (use force=True to refresh)",
            dest,
        )
        return dest
    if dest.exists():
        shutil.rmtree(dest)
    _ = shutil.copytree(source, dest)
    logger.info("Materialized agent knowledge to %s", dest)
    return dest


def write_context_json(
    *,
    output_dir: Path,
    sdk_version: str,
    agent_knowledge_path: Path | None,
    platform_openapi: Path | None,
    include_openapi: bool,
    sync_skills: SkillSyncMode,
) -> Path:
    """Write or update context.json init manifest."""
    manifest_path = context_json_path(output_dir)
    payload = {
        "schema_version": CONTEXT_JSON_SCHEMA_VERSION,
        "sdk_version": sdk_version,
        "materialized_at": datetime.now(UTC).isoformat(),
        "agent_knowledge_path": (
            str(agent_knowledge_path) if agent_knowledge_path else None
        ),
        "context_json_path": str(manifest_path),
        "platform_openapi_path": str(platform_openapi) if platform_openapi else None,
        "flags": {
            "include_openapi": include_openapi,
            "sync_skills": sync_skills,
        },
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with open(manifest_path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        _ = handle.write("\n")
    return manifest_path


def _reconcile_legacy_platform_downloads(context_dir: Path) -> None:
    """Move or remove legacy flat OpenAPI downloads under context_dir.

    REMOVE_BY_0_7_0: drop once flat ``.endorlabs-context/openapiv2.swagger.json``
    migrations are no longer needed (canonical path is ``platform/openapi/`` only).
    """
    root = Path(context_dir)
    legacy_openapi = root / DEFAULT_OPENAPI_FILENAME
    canonical_openapi = platform_openapi_path(root)
    legacy_openapi_resolved = legacy_openapi.resolve()
    canonical_openapi_resolved = canonical_openapi.resolve()
    if (
        legacy_openapi.is_file()
        and legacy_openapi_resolved != canonical_openapi_resolved
    ):
        if canonical_openapi.is_file():
            legacy_openapi.unlink()
            logger.info("Removed stale legacy OpenAPI download: %s", legacy_openapi)
        else:
            canonical_openapi.parent.mkdir(parents=True, exist_ok=True)
            _ = legacy_openapi.replace(canonical_openapi)
            logger.info("Moved legacy OpenAPI download to %s", canonical_openapi)


def sync_openapi(
    output_path: str | Path | None = None,
    force: bool = False,
    client: APIClient | None = None,
) -> Path:
    """Download OpenAPI specification from Endor Labs API.

    Requires authentication via APIClient - no public URL fallback.

    Args:
        output_path: Path to save the OpenAPI spec file (default:
            ``.endorlabs-context/platform/openapi/openapiv2.swagger.json``).
        force: Force re-download even if file exists.
        client: Optional APIClient instance. If not provided, one is created
            (requires ENDOR_API_CREDENTIALS_KEY/SECRET or ENDOR_TOKEN env vars).

    Returns:
        Path to the downloaded OpenAPI spec file.

    Raises:
        endorlabs.UnauthorizedError: If authentication fails.
        ImportError: If context dependencies are not installed.

    """
    from endorlabs.api_client import APIClient as APIClientClass

    output_file = (
        Path(output_path)
        if output_path is not None
        else platform_openapi_path(DEFAULT_CONTEXT_DIR)
    )
    context_dir = output_file.parent.parent.parent
    if output_file.resolve() == platform_openapi_path(context_dir).resolve():
        _reconcile_legacy_platform_downloads(context_dir)

    # Skip if file exists and not forcing
    if output_file.exists() and not force:
        logger.info(
            "OpenAPI spec already exists: %s (use force=True to re-download)",
            output_path,
        )
        return output_file

    # Create client if not provided
    api_client = client or APIClientClass()

    logger.info("Downloading OpenAPI specification from Endor Labs API...")
    response = api_client.get(
        OPENAPI_PATH,
        headers={"Accept": "application/json"},
    )
    response_data = response.json()

    # Create directory if it doesn't exist
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(response_data, f, indent=2)

    logger.info("OpenAPI spec saved to: %s", output_path)
    return output_file


def init(
    output_dir: str | Path = DEFAULT_CONTEXT_DIR,
    include_openapi: bool = False,
    include_agent_knowledge: bool = True,
    force: bool = False,
    sync_skills: SkillSyncMode = "none",
    client: APIClient | None = None,
) -> InitStatus:
    """Bootstrap Endor Labs context for agentic workflows.

    By default, ``init()`` materializes agent knowledge under ``sdk/``. Pass explicit
    flags to download OpenAPI under ``platform/`` and/or mirror skills into IDE
    discovery directories. Product docs use the Docs MCP server
    (``https://docs.endorlabs.com/mcp``), not a local scrape.

    Args:
        output_dir: Directory to save context files (default: .endorlabs-context).
        include_openapi: Download OpenAPI spec (default: False).
        include_agent_knowledge: Copy agent knowledge to sdk/ (default: True).
        force: Force re-download / refresh even if files exist (default: False).
        sync_skills: Mirror skills into runtime dirs
            (``none``, ``cursor``, ``claude``, or ``both``; default ``none``).
        client: Optional APIClient instance. If not provided, one is created
            when ``include_openapi=True`` (requires ENDOR_API_CREDENTIALS_KEY/
            SECRET or ENDOR_TOKEN env vars).

    Returns:
        InitStatus with paths to copied and downloaded files.

    Raises:
        endorlabs.UnauthorizedError: If OpenAPI authentication fails.

    Example::

        >>> import endorlabs
        >>> status = endorlabs.init()
        >>> print(status.agent_knowledge_path)
        .endorlabs-context/sdk

    """
    import importlib.metadata

    from endorlabs.api_client import APIClient as APIClientClass

    try:
        __version__ = importlib.metadata.version("endorlabs")
    except importlib.metadata.PackageNotFoundError:
        __version__ = "0.0.0.dev0"
    normalized_sync_target = _normalize_skill_sync_mode(sync_skills)
    needs_context_dir = (
        include_agent_knowledge or include_openapi or normalized_sync_target != "none"
    )
    if not needs_context_dir:
        logger.info(
            "No context bootstrap actions requested. Use agent_knowledge_index_path() "
            "for shipped skills without disk writes, or pass include_openapi=True, "
            "include_agent_knowledge=True, and/or sync_skills."
        )
        return InitStatus(
            agent_knowledge_path=None,
            context_json_path=None,
            platform_openapi_path=None,
            downloaded_at=datetime.now(UTC),
            synced_skill_paths={},
        )

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    warn_agent_defer_gitignore_to_user(output_path)

    agent_knowledge_dest: Path | None = None
    if include_agent_knowledge:
        agent_knowledge_dest = materialize_agent_knowledge(output_path, force=force)

    platform_openapi: Path | None = None
    synced_skill_paths: dict[str, Path] = {}

    if include_openapi:
        api_client = client or APIClientClass()
        platform_openapi = sync_openapi(
            output_path=platform_openapi_path(output_path),
            force=force,
            client=api_client,
        )

    if normalized_sync_target != "none":
        skill_source = sdk_dir(output_path) / "skills"
        if not skill_source.is_dir():
            if include_agent_knowledge and agent_knowledge_dest is not None:
                skill_source = agent_knowledge_dest / "skills"
            else:
                from endorlabs.agent_knowledge import agent_knowledge_dir

                skill_source = agent_knowledge_dir() / "skills"
        synced_skill_paths = sync_agent_skills(
            repo_root=output_path.resolve().parent,
            target=normalized_sync_target,
            source_dir=skill_source,
        )

    manifest_path = write_context_json(
        output_dir=output_path,
        sdk_version=__version__,
        agent_knowledge_path=agent_knowledge_dest,
        platform_openapi=platform_openapi,
        include_openapi=include_openapi,
        sync_skills=normalized_sync_target,
    )

    return InitStatus(
        agent_knowledge_path=agent_knowledge_dest,
        context_json_path=manifest_path,
        platform_openapi_path=platform_openapi,
        downloaded_at=datetime.now(UTC),
        synced_skill_paths=synced_skill_paths,
    )
