"""In-memory Pydantic model generation from JSON schema shards."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from datamodel_code_generator import DataModelType, GenerateConfig, InputFileType, generate

from .path_safety import safe_module_segment

logger = logging.getLogger(__name__)

GENERATED_HEADER = """\
# Generated by Endor Labs SDK model sync. Do not edit manually.
# Regenerate with: uv run python devtools/codegen/model_sync.py
"""

CODEGEN_CONFIG = GenerateConfig(
    input_file_type=InputFileType.JsonSchema,
    output_model_type=DataModelType.PydanticV2BaseModel,
    use_schema_description=True,
    use_field_description=True,
    field_constraints=True,
    use_standard_collections=True,
    use_union_operator=True,
    use_subclass_enum=True,
    use_unique_items_as_set=True,
    strict_nullable=True,
    target_python_version="3.11",
    disable_timestamp=True,
)


def load_profiles(profiles_dir: Path) -> dict[str, Any]:
    """Load profile files used for sync policy metadata."""
    profile_files = (
        "aliases.json",
        "base_class_map.json",
        "enum_policy.json",
        "partition_rules.json",
    )
    payload: dict[str, Any] = {}
    for filename in profile_files:
        path = profiles_dir / filename
        payload[filename] = (
            {"missing": True}
            if not path.exists()
            else json.loads(path.read_text(encoding="utf-8"))
        )
    return payload


def generate_modules_in_memory(
    schema_shards: dict[str, dict[str, Any]],
) -> dict[str, str]:
    """Generate model source for each shard entirely in memory.

    Returns a mapping of relative module path (``foo/bar.py``) to source text.
    """
    module_paths = sorted(schema_shards)
    total = len(module_paths)
    logger.info("model-sync: generating %s module shard(s) in memory", total)
    generated: dict[str, str] = {}
    for index, module_path in enumerate(module_paths, start=1):
        safe_path = safe_module_segment(module_path)
        payload = json.dumps(schema_shards[module_path], sort_keys=True)
        body = generate(payload, config=CODEGEN_CONFIG)
        if not isinstance(body, str):
            raise TypeError(
                f"Expected str from datamodel_code_generator for {safe_path!r}, "
                f"got {type(body).__name__}"
            )
        generated[f"{safe_path}.py"] = GENERATED_HEADER + body
        if index == 1 or index % 10 == 0 or index == total:
            logger.info(
                "model-sync: generated %s/%s module shard(s) (current: %s)",
                index,
                total,
                module_path,
            )
    return generated
