"""Finding resource module for Endor Labs API.

This module provides CRUD operations for Finding resources following the established
patterns from the Project resource implementation.

API OPERATIONS SUPPORTED:
- GET: List findings, Get finding by UUID
- PATCH: Update finding tags and metadata

API LIMITATIONS:
- CREATE: Not supported by API (findings are generated by security scans)
- DELETE: Not supported by API (findings are immutable for audit purposes)

Note: Findings are automatically generated by Endor Labs security scans and cannot
be manually created or deleted. Only metadata updates (tags, dismissal status) allowed.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, override

from pydantic import BaseModel, ConfigDict, Field, field_validator

from ..models.base import (
    BaseMeta,
    BaseResource,
    BaseSpec,
    FlexibleEnum,
)
from ..utils.logging_config import get_resource_logger

logger = get_resource_logger(__name__)


class FindingCategory(FlexibleEnum):
    """Finding category enumeration."""

    UNSPECIFIED = "FINDING_CATEGORY_UNSPECIFIED"
    VULNERABILITY = "FINDING_CATEGORY_VULNERABILITY"
    SUPPLY_CHAIN = "FINDING_CATEGORY_SUPPLY_CHAIN"
    LICENSE_RISK = "FINDING_CATEGORY_LICENSE_RISK"
    SCPM = "FINDING_CATEGORY_SCPM"
    SECURITY = "FINDING_CATEGORY_SECURITY"
    OPERATIONAL = "FINDING_CATEGORY_OPERATIONAL"
    SECRETS = "FINDING_CATEGORY_SECRETS"
    MALWARE = "FINDING_CATEGORY_MALWARE"
    CICD = "FINDING_CATEGORY_CICD"
    TOOLS = "FINDING_CATEGORY_TOOLS"
    GHACTIONS = "FINDING_CATEGORY_GHACTIONS"
    CONTAINER = "FINDING_CATEGORY_CONTAINER"
    SAST = "FINDING_CATEGORY_SAST"
    AI_MODELS = "FINDING_CATEGORY_AI_MODELS"
    SECURITY_REVIEW = "FINDING_CATEGORY_SECURITY_REVIEW"
    SCA = "FINDING_CATEGORY_SCA"


class FindingLevel(FlexibleEnum):
    """Finding severity level enumeration."""

    UNSPECIFIED = "FINDING_LEVEL_UNSPECIFIED"
    CRITICAL = "FINDING_LEVEL_CRITICAL"
    HIGH = "FINDING_LEVEL_HIGH"
    MEDIUM = "FINDING_LEVEL_MEDIUM"
    LOW = "FINDING_LEVEL_LOW"


class FindingStatus(FlexibleEnum):
    """Finding status enumeration."""

    UNSPECIFIED = "FINDING_STATUS_UNSPECIFIED"
    OPEN = "FINDING_STATUS_OPEN"
    RESOLVED = "FINDING_STATUS_RESOLVED"
    IGNORED = "FINDING_STATUS_IGNORED"
    FALSE_POSITIVE = "FINDING_STATUS_FALSE_POSITIVE"


class AnalysisMethod(FlexibleEnum):
    """Analysis method enumeration."""

    UNSPECIFIED = "SYSTEM_EVALUATION_METHOD_UNSPECIFIED"
    DEFINITION_VULNERABILITIES = "SYSTEM_EVALUATION_METHOD_DEFINITION_VULNERABILITIES"
    DEFINITION_POLICIES = "SYSTEM_EVALUATION_METHOD_DEFINITION_POLICIES"
    SAST = "SYSTEM_EVALUATION_METHOD_SAST"
    SCA = "SYSTEM_EVALUATION_METHOD_SCA"
    SECRETS = "SYSTEM_EVALUATION_METHOD_SECRETS"
    CONTAINER = "SYSTEM_EVALUATION_METHOD_CONTAINER"
    INFRASTRUCTURE = "SYSTEM_EVALUATION_METHOD_INFRASTRUCTURE"


class CallGraphAnalysisType(FlexibleEnum):
    """Call graph analysis type enumeration."""

    UNSPECIFIED = "CALL_GRAPH_ANALYSIS_TYPE_UNSPECIFIED"
    FULL = "CALL_GRAPH_ANALYSIS_TYPE_FULL"
    PRECOMPUTED = "CALL_GRAPH_ANALYSIS_TYPE_PRECOMPUTED"


class Ecosystem(FlexibleEnum):
    """Package ecosystem enumeration."""

    UNSPECIFIED = "ECOSYSTEM_UNSPECIFIED"
    AI_MODEL = "ECOSYSTEM_AI_MODEL"
    APK = "ECOSYSTEM_APK"
    C = "ECOSYSTEM_C"
    CARGO = "ECOSYSTEM_CARGO"
    COCOAPOD = "ECOSYSTEM_COCOAPOD"
    CONTAINER = "ECOSYSTEM_CONTAINER"
    DEBIAN = "ECOSYSTEM_DEBIAN"
    GEM = "ECOSYSTEM_GEM"
    GIT = "ECOSYSTEM_GIT"
    GITHUB_ACTION = "ECOSYSTEM_GITHUB_ACTION"
    GO = "ECOSYSTEM_GO"
    HUGGING_FACE = "ECOSYSTEM_HUGGING_FACE"
    MAVEN = "ECOSYSTEM_MAVEN"
    NPM = "ECOSYSTEM_NPM"
    NUGET = "ECOSYSTEM_NUGET"
    PACKAGIST = "ECOSYSTEM_PACKAGIST"
    PYPI = "ECOSYSTEM_PYPI"
    RPM = "ECOSYSTEM_RPM"
    SBOM = "ECOSYSTEM_SBOM"
    SWIFT = "ECOSYSTEM_SWIFT"


class CvssVersion(FlexibleEnum):
    """CVSS version enumeration."""

    UNSPECIFIED = "CVSS_VERSION_UNSPECIFIED"
    V2 = "CVSS_VERSION_V2"
    V3 = "CVSS_VERSION_V3"
    V4 = "CVSS_VERSION_V4"


class CvssSeverityLevel(FlexibleEnum):
    """CVSS severity level enumeration."""

    UNSPECIFIED = "CVSS_SEVERITY_LEVEL_UNSPECIFIED"
    NONE = "CVSS_SEVERITY_LEVEL_NONE"
    LOW = "CVSS_SEVERITY_LEVEL_LOW"
    MEDIUM = "CVSS_SEVERITY_LEVEL_MEDIUM"
    HIGH = "CVSS_SEVERITY_LEVEL_HIGH"
    CRITICAL = "CVSS_SEVERITY_LEVEL_CRITICAL"


class FindingTags(FlexibleEnum):
    """Finding tags enumeration."""

    UNSPECIFIED = "FINDING_TAGS_UNSPECIFIED"
    AI = "FINDING_TAGS_AI"
    CI_BLOCKER = "FINDING_TAGS_CI_BLOCKER"
    CI_WARNING = "FINDING_TAGS_CI_WARNING"
    DIRECT = "FINDING_TAGS_DIRECT"
    DISPUTED = "FINDING_TAGS_DISPUTED"
    EXCEPTION = "FINDING_TAGS_EXCEPTION"
    EXPLOITED = "FINDING_TAGS_EXPLOITED"
    FALSE_POSITIVE = "FINDING_TAGS_FALSE_POSITIVE"
    FIXABLE = "FINDING_TAGS_FIXABLE"  # Deprecated
    FIX_AVAILABLE = "FINDING_TAGS_FIX_AVAILABLE"
    IGNORED = "FINDING_TAGS_IGNORED"
    INVALID_SECRET = "FINDING_TAGS_INVALID_SECRET"
    MALWARE = "FINDING_TAGS_MALWARE"
    NAMESPACE_INTERNAL = "FINDING_TAGS_NAMESPACE_INTERNAL"
    NORMAL = "FINDING_TAGS_NORMAL"
    NOTIFICATION = "FINDING_TAGS_NOTIFICATION"
    PATH_EXTERNAL = "FINDING_TAGS_PATH_EXTERNAL"
    PHANTOM = "FINDING_TAGS_PHANTOM"
    POLICY = "FINDING_TAGS_POLICY"  # Deprecated
    POTENTIALLY_REACHABLE_DEPENDENCY = "FINDING_TAGS_POTENTIALLY_REACHABLE_DEPENDENCY"
    POTENTIALLY_REACHABLE_FUNCTION = "FINDING_TAGS_POTENTIALLY_REACHABLE_FUNCTION"
    PRODUCTION = "FINDING_TAGS_PRODUCTION"  # Deprecated
    PROJECT_INTERNAL = "FINDING_TAGS_PROJECT_INTERNAL"
    REACHABLE_DEPENDENCY = "FINDING_TAGS_REACHABLE_DEPENDENCY"
    REACHABLE_FUNCTION = "FINDING_TAGS_REACHABLE_FUNCTION"
    SELF = "FINDING_TAGS_SELF"
    SNOOZED = "FINDING_TAGS_SNOOZED"
    TEST = "FINDING_TAGS_TEST"
    TRANSITIVE = "FINDING_TAGS_TRANSITIVE"
    TRUE_POSITIVE = "FINDING_TAGS_TRUE_POSITIVE"
    UNDER_REVIEW = "FINDING_TAGS_UNDER_REVIEW"
    UNFIXABLE = "FINDING_TAGS_UNFIXABLE"
    UNREACHABLE_DEPENDENCY = "FINDING_TAGS_UNREACHABLE_DEPENDENCY"
    UNREACHABLE_FUNCTION = "FINDING_TAGS_UNREACHABLE_FUNCTION"
    VALID_SECRET = "FINDING_TAGS_VALID_SECRET"
    WITHDRAWN = "FINDING_TAGS_WITHDRAWN"


class RangeType(FlexibleEnum):
    """Range type enumeration."""

    UNSPECIFIED = "RANGE_TYPE_UNSPECIFIED"
    ECOSYSTEM = "RANGE_TYPE_ECOSYSTEM"
    GIT = "RANGE_TYPE_GIT"
    SEMVER = "RANGE_TYPE_SEMVER"


class FindingRemediation(FlexibleEnum):
    """Finding remediation action enumeration."""

    UNSPECIFIED = "FINDING_REMEDIATION_UNSPECIFIED"
    UPGRADE = "FINDING_REMEDIATION_UPGRADE"
    DOWNGRADE = "FINDING_REMEDIATION_DOWNGRADE"
    REPLACE = "FINDING_REMEDIATION_REPLACE"
    REMOVE = "FINDING_REMEDIATION_REMOVE"
    VENDOR = "FINDING_REMEDIATION_VENDOR"
    IMPROVE = "FINDING_REMEDIATION_IMPROVE"
    REIMPLEMENT = "FINDING_REMEDIATION_REIMPLEMENT"
    REVIEW = "FINDING_REMEDIATION_REVIEW"
    NOTIFICATION = "FINDING_REMEDIATION_NOTIFICATION"
    PIN = "FINDING_REMEDIATION_PIN"


class FindingMeta(BaseMeta):
    """Finding metadata extending BaseMeta."""

    # Finding-specific fields (universal fields inherited from BaseMeta)
    pass  # No additional fields needed, all were universal


class FindingMetaUpdate(BaseModel):
    """Metadata for updating a Finding (only mutable fields)."""

    description: str | None = Field(None, description="Updated description")
    tags: list[str] | None = Field(None, description="Updated tags")
    annotations: dict[str, Any] | None = Field(None, description="Updated annotations")


class Actions(BaseModel):
    """Actions metadata added by admission or notification policy scanner."""

    policy_uuids: list[str] | None = Field(
        None, description="List of action policies triggered by this finding"
    )


class FixingPatch(BaseModel):
    """Patch that can fix the finding."""

    endor_patch_available: bool | None = Field(
        None, description="Whether an Endor patch is available"
    )


class SourceCodeVersion(BaseModel):
    """Source code version information."""

    sha: str | None = Field(
        None,
        description=(
            "SHA of the source control version. "
            "Because the SHA might not be possible to resolve, this field is optional."
        ),
    )
    ref: str | None = Field(
        None,
        description=(
            "Resolved ref of the source control version. "
            "Can be a tag, a branch or a SHA."
        ),
    )
    metadata: dict[str, str] | None = Field(
        None, description="Version metadata as key-value pairs"
    )


class FindingMetadata(BaseModel):
    """Finding metadata details.

    This model extends the basic finding metadata with all fields from the OpenAPI spec.
    Many fields are optional and only present for specific finding types.
    """

    title: str | None = None
    description: str | None = None
    file_path: str | None = None
    line_number: int | None = None
    code_snippet: str | None = None
    category: FindingCategory | None = None

    # Extended fields from OpenAPI spec v1FindingMetadata
    root_package_score_card: dict[str, Any] | None = Field(
        None, description="The package scorecard for findings about low scores"
    )
    dependency_score_card: dict[str, Any] | None = Field(
        None, description="The dependency scorecard for findings about low scores"
    )
    root_package_score_factor_list: dict[str, Any] | None = Field(
        None,
        description=(
            "A list of (relevant) score factors, for the root package, "
            "for findings about low scores"
        ),
    )
    dependency_score_factor_list: dict[str, Any] | None = Field(
        None,
        description=(
            "A list of (relevant) score factors, for the dependency, "
            "for findings about low scores"
        ),
    )
    vulnerability: dict[str, Any] | None = Field(
        None, description="Vulnerability data for vulnerability related findings"
    )
    root_package_resolved_dependencies: dict[str, Any] | None = Field(
        None, description="The resolved dependencies of the root package"
    )
    source_policy_info: dict[str, Any] | None = Field(
        None, description="Details about the policy that created the finding"
    )
    ci_blocking_policy_info: dict[str, Any] | None = Field(
        None,
        description=("This field is always empty. See spec.actions instead."),
    )
    root_package_version_metadata: dict[str, Any] | None = Field(
        None, description="Package metadata for the root package"
    )
    dependency_package_version_metadata: dict[str, Any] | None = Field(
        None, description="Package metadata for the dependency"
    )
    typosquatted_dependency_version_metadata: dict[str, Any] | None = Field(
        None,
        description=(
            "Package metadata for the typosquatted package, "
            "for findings about typosquatting"
        ),
    )
    container_data: dict[str, Any] | None = Field(
        None, description="Container image data of finding"
    )
    custom: dict[str, Any] | None = Field(None, description="Custom finding metadata")
    security_review_data: dict[str, Any] | None = Field(
        None, description="Security review data for security review findings"
    )
    malware: dict[str, Any] | None = Field(
        None, description="Malware data for malware related findings"
    )
    cvss_version: CvssVersion | None = Field(
        None, description="CVSS version of the vulnerability"
    )


class FindingSpec(BaseSpec):
    """Finding specification extending BaseSpec.

    Field Mutability Guide:
    ======================

    FIELD MUTABILITY (per OpenAPI spec):
    =====================================
    Note: v1FindingSpec has NO fields marked as readOnly: true in the API spec.
    This means all FindingSpec fields are technically mutable via the Update endpoint.

    However, many fields are analysis-determined and updated by the scan service.
    Common fields updated by users:
    - dismiss: Dismissal status
    - remediation: Remediation guidance
    - summary: Finding summary
    - finding_tags: Finding-specific tags
    - extra_key: User-defined extra information
    """

    project_uuid: str | None = Field(
        None,
        description="UUID of the project this finding belongs to",  # IMMUTABLE
    )
    last_processed: datetime | None = Field(
        None,
        description="Last processed timestamp",  # IMMUTABLE: System-managed
    )
    level: FindingLevel | None = Field(
        None, description="Severity level of the finding"
    )  # IMMUTABLE: Analysis-determined
    dismiss: bool | None = Field(
        None,
        description="Whether the finding is dismissed",  # MUTABLE: User can update
    )
    remediation: str | None = Field(
        None, description="Remediation guidance"
    )  # MUTABLE: User can update
    finding_metadata: FindingMetadata | None = Field(
        None,
        description=(
            "Complex nested structure with finding-specific metadata"
        ),  # IMMUTABLE: System-generated
    )
    summary: str | None = Field(
        None, description="Finding summary"
    )  # MUTABLE: User can update
    finding_tags: list[str] | None = Field(
        None,
        description="Tags associated with the finding",  # MUTABLE: User can update
    )
    target_uuid: str | None = Field(
        None, description="Target resource UUID"
    )  # IMMUTABLE: Set at creation
    extra_key: str | None = Field(
        None, description="Extra key information"
    )  # MUTABLE: User can update
    method: AnalysisMethod | None = Field(
        None, description="Analysis method used"
    )  # IMMUTABLE: Analysis-determined

    @field_validator("level", mode="before")
    @classmethod
    def validate_level(cls, v: Any) -> Any:
        """Handle unknown level values gracefully."""
        if isinstance(v, str):
            try:
                return FindingLevel(v)
            except ValueError:
                logger.warning(f"Unknown FindingLevel value: {v}. Using as-is.")
                return v
        return v

    @field_validator("method", mode="before")
    @classmethod
    def validate_method(cls, v: Any) -> Any:
        """Handle unknown method values gracefully."""
        if isinstance(v, str):
            try:
                return AnalysisMethod(v)
            except ValueError:
                logger.warning(f"Unknown AnalysisMethod value: {v}. Using as-is.")
                return v
        return v

    @field_validator("ecosystem", mode="before")
    @classmethod
    def validate_ecosystem(cls, v: Any) -> Any:
        """Handle unknown ecosystem values gracefully."""
        if isinstance(v, str):
            try:
                return Ecosystem(v)
            except ValueError:
                logger.warning(f"Unknown Ecosystem value: {v}. Using as-is.")
                return v
        return v

    @field_validator("finding_tags")
    @classmethod
    def validate_finding_tags(cls, v: list[str] | None) -> list[str] | None:
        """Validate finding tags are not empty strings."""
        if v:
            return [tag.strip() for tag in v if tag.strip()]
        return v

    @field_validator("remediation")
    @classmethod
    def validate_remediation(cls, v: str | None) -> str | None:
        """Validate remediation is not just whitespace."""
        if v and not v.strip():
            raise ValueError("remediation cannot be empty or whitespace")
        return v.strip() if v else v

    @field_validator("remediation_action", mode="before")
    @classmethod
    def validate_remediation_action(cls, v: Any) -> Any:
        """Handle unknown remediation action values gracefully."""
        if isinstance(v, str):
            try:
                return FindingRemediation(v)
            except ValueError:
                logger.warning(f"Unknown FindingRemediation value: {v}. Using as-is.")
                return v
        return v

    @field_validator("finding_categories", mode="before")
    @classmethod
    def validate_finding_categories(cls, v: Any) -> Any:
        """Handle finding categories validation."""
        if isinstance(v, list):
            validated_categories = []
            for category in v:
                if isinstance(category, str):
                    try:
                        validated_categories.append(FindingCategory(category))
                    except ValueError:
                        logger.warning(
                            f"Unknown FindingCategory value: {category}. Using as-is."
                        )
                        validated_categories.append(category)
                else:
                    validated_categories.append(category)
            return validated_categories
        return v

    @field_validator("call_graph_analysis_type", mode="before")
    @classmethod
    def validate_call_graph_analysis_type(cls, v: Any) -> Any:
        """Handle unknown call graph analysis type values gracefully."""
        if isinstance(v, str):
            try:
                return CallGraphAnalysisType(v)
            except ValueError:
                logger.warning(
                    f"Unknown CallGraphAnalysisType value: {v}. Using as-is."
                )
                return v
        return v

    target_dependency_package_name: str | None = Field(
        None,
        description="Fully qualified name of the dependency, e.g. eco://package@version",
    )  # IMMUTABLE: Analysis-determined
    target_dependency_name: str | None = Field(
        None,
        description="Dependency package name, if applicable. This is just the name.",
    )  # IMMUTABLE: Analysis-determined
    target_dependency_version: str | None = Field(
        None,
        description="Dependency version, if applicable. This is just the version.",
    )  # IMMUTABLE: Analysis-determined
    explanation: str | None = Field(
        None, description="Information about why this finding is considered noteworthy"
    )  # IMMUTABLE: Analysis-determined
    remediation_action: FindingRemediation | None = Field(
        None, description="Suggested action to resolve the finding"
    )  # IMMUTABLE: Analysis-determined
    source_code_version: SourceCodeVersion | None = Field(
        None,
        description="Ref of the source code repository for root package version",
    )  # IMMUTABLE: Analysis-determined
    reachable_paths: list[dict[str, Any]] | None = Field(
        None,
        description="Function paths to vulnerable method. Only for vulnerabilities.",
    )  # IMMUTABLE: Analysis-determined
    ecosystem: Ecosystem | None = Field(
        None, description="Ecosystem where the finding was detected"
    )  # IMMUTABLE: Analysis-determined
    finding_categories: list[FindingCategory] | None = Field(
        None,
        description="List of categories that capture the use case the finding fits in.",
    )  # IMMUTABLE: Analysis-determined
    relationship: str | None = Field(
        None, description="Relationship information"
    )  # IMMUTABLE: Analysis-determined
    latest_version: str | None = Field(
        None, description="Latest version of the dependency"
    )  # IMMUTABLE: Analysis-determined
    dependency_file_paths: list[str] | None = Field(
        None, description="Paths to dependency files"
    )  # IMMUTABLE: Analysis-determined
    approximation: bool | None = Field(
        None, description="Whether this is an approximation"
    )  # IMMUTABLE: Analysis-determined
    proposed_version: str | None = Field(
        None, description="Proposed version for remediation"
    )  # IMMUTABLE: Analysis-determined
    exceptions: list[str] | dict[str, Any] | None = Field(
        None, description="Exception information"
    )  # IMMUTABLE: Analysis-determined
    actions: Actions | None = Field(
        None, description="Tags and other fields set by action policies"
    )  # IMMUTABLE: Analysis-determined
    fixing_upgrades: list[str | dict[str, Any]] | dict[str, Any] | None = Field(
        None,
        description=(
            "Fixing upgrade information. Can be: "
            "list of strings, list of dicts, or dict with upgrade_list key"
        ),
    )  # IMMUTABLE: Analysis-determined
    fixing_patch: FixingPatch | None = Field(
        None, description="Patch that can fix the finding"
    )  # IMMUTABLE: Analysis-determined

    @field_validator("finding_metadata", mode="before")
    @classmethod
    def validate_finding_metadata(cls, v: Any) -> Any:
        """Handle finding_metadata as dict or FindingMetadata model."""
        if v is None:
            return None
        if isinstance(v, FindingMetadata):
            return v
        if isinstance(v, dict):
            return FindingMetadata(**v)
        return v

    @field_validator("actions", mode="before")
    @classmethod
    def validate_actions(cls, v: Any) -> Any:
        """Handle actions as dict, list, or Actions model."""
        if v is None:
            return None
        if isinstance(v, Actions):
            return v
        if isinstance(v, dict):
            return Actions(**v)
        # If it's a list (legacy format), return None as Actions expects dict
        if isinstance(v, list):
            return None
        return v

    @field_validator("fixing_patch", mode="before")
    @classmethod
    def validate_fixing_patch(cls, v: Any) -> Any:
        """Handle fixing_patch as dict, list, or FixingPatch model."""
        if v is None:
            return None
        if isinstance(v, FixingPatch):
            return v
        if isinstance(v, dict):
            return FixingPatch(**v)
        # If it's a list (legacy format), return None as FixingPatch expects dict
        if isinstance(v, list):
            return None
        return v

    @field_validator("source_code_version", mode="before")
    @classmethod
    def validate_source_code_version(cls, v: Any) -> Any:
        """Handle source_code_version as dict or SourceCodeVersion model."""
        if v is None:
            return None
        if isinstance(v, SourceCodeVersion):
            return v
        if isinstance(v, dict):
            return SourceCodeVersion(**v)
        return v

    @field_validator("location_urls", mode="before")
    @classmethod
    def validate_location_urls(cls, v: Any) -> Any:
        """Handle location_urls as dict, list, or Dict[str, str]."""
        if v is None:
            return None
        if isinstance(v, dict):
            # Ensure all values are strings
            return {k: str(v) for k, v in v.items()}
        if isinstance(v, list):
            # Legacy format - convert to empty dict
            return {}
        return v

    @field_validator("fixing_upgrades", mode="before")
    @classmethod
    def validate_fixing_upgrades(cls, v: Any) -> Any:
        """Normalize fixing_upgrades from dict with upgrade_list to list."""
        if isinstance(v, dict) and "upgrade_list" in v:
            return v["upgrade_list"]
        # If it's already a list (of strings or dicts), return as-is
        return v

    code_owners: list[str] | dict[str, Any] | None = Field(
        None,
        description="Code owners information (list or dict with owners/labels)",
    )  # IMMUTABLE: Analysis-determined
    location_urls: dict[str, str] | None = Field(
        None,
        description=(
            "The URLs that correspond to the paths contained in dependency_file_paths. "
            "Keys are file paths, values are URLs."
        ),
    )  # IMMUTABLE: Analysis-determined
    call_graph_analysis_type: CallGraphAnalysisType | None = Field(
        None, description="Call graph analysis type"
    )  # IMMUTABLE: Analysis-determined

    @override
    @field_validator("*", mode="before")
    @classmethod
    def detect_schema_drift(cls, v: Any, info: Any) -> Any:
        """Override BaseSpec drift detection to skip typed nested model fields."""
        # Skip drift detection for typed nested models
        # (they handle their own validation)
        typed_model_fields = {
            "finding_metadata",  # FindingMetadata
            "actions",  # Actions
            "fixing_patch",  # FixingPatch
            "source_code_version",  # SourceCodeVersion
            "location_urls",  # Dict[str, str] - typed
        }
        if (
            info.field_name
            and isinstance(v, dict)
            and info.field_name not in typed_model_fields
        ):
            # Call parent validator for non-typed-model fields
            return super().detect_schema_drift(v, info)
        return v


class Context(BaseModel):
    """Context information for findings."""

    id: str | None = None
    type: str | None = None
    scan_uuid: str | None = None
    scan_type: str | None = None
    scan_time: datetime | None = None
    will_be_deleted_at: str | None = None
    tags: list[str] | None = None


class TenantMeta(BaseModel):
    """Tenant metadata."""

    namespace: str


class Finding(BaseResource):
    """An Endor Labs finding entity extending BaseResource.

    Finding-specific fields (universal fields inherited from BaseResource).

    OPERATION SUPPORT:
    ==================
    ✅ GET: List findings, Get by UUID
    ✅ PATCH: Update tags and metadata
    ❌ CREATE: Not supported (findings generated by scans)
    ❌ DELETE: Not supported (findings are immutable)

    FIELD MUTABILITY:
    =================
    IMMUTABLE FIELDS (read-only, system-generated):
    - uuid: Unique identifier
    - meta.name: Finding name (set by scan)
    - spec.level: Severity level (set by scan)
    - spec.category: Finding category (set by scan)
    - spec.project_uuid: Associated project (set at creation)
    - spec.finding_metadata: Scan-discovered metadata
    - tenant_meta.namespace: Namespace assignment

    MUTABLE FIELDS (can be updated via PATCH):
    - meta.tags: General resource tags
    - spec.finding_tags: Finding-specific tags
    - spec.dismiss: Dismissal status
    - spec.remediation: Remediation guidance
    - context.tags: Contextual tags
    """

    # Finding-specific fields (universal fields inherited from BaseResource)
    spec: FindingSpec = Field(..., description="Finding specification")  # type: ignore
    # Required per v1Finding; optional when list response omits it
    context: Context | None = Field(  # pyright: ignore[reportIncompatibleVariableOverride]
        None, description="Context information for the finding", alias="context"
    )

    model_config = ConfigDict(extra="ignore")

    def __init__(self, **data: Any) -> None:
        # Convert spec to FindingSpec if it's a dict
        if "spec" in data and isinstance(data["spec"], dict):
            data["spec"] = FindingSpec(**data["spec"])
        super().__init__(**data)

    @override
    @field_validator("*", mode="before")
    @classmethod
    def detect_schema_drift(cls, v: Any, info: Any) -> Any:
        """Detect and log schema drift for unknown fields."""
        if info.field_name == "spec" and isinstance(v, dict):
            # Log unknown fields for schema drift detection in spec
            known_fields = {
                "project_uuid",
                "last_processed",
                "level",
                "dismiss",
                "remediation",
                "finding_metadata",
                "summary",
                "finding_tags",
                "target_uuid",
                "extra_key",
                "method",
                "target_dependency_package_name",
                "target_dependency_name",
                "target_dependency_version",
                "explanation",
                "remediation_action",
                "source_code_version",
                "reachable_paths",
                "ecosystem",
                "finding_categories",
                "relationship",
                "latest_version",
                "dependency_file_paths",
                "approximation",
                "proposed_version",
                "exceptions",
                "actions",
                "fixing_upgrades",
                "fixing_patch",
                "code_owners",
                "location_urls",
                "call_graph_analysis_type",
            }
            unknown_fields = set(v.keys()) - known_fields
            if unknown_fields:
                logger.warning(
                    f"Schema drift detected in {info.field_name}: "
                    f"unknown fields {unknown_fields}"
                )
        return v

    @override
    @classmethod
    def get_mutable_fields_cls(cls) -> list[str]:
        """Get list of mutable fields for Finding."""
        return [
            "meta.tags",
            "spec.finding_tags",
            "spec.dismiss",
            "spec.remediation",
            "context.tags",
        ]

    @override
    @classmethod
    def get_immutable_fields_cls(cls) -> list[str]:
        """Get list of immutable fields for Finding."""
        return [
            "uuid",
            "meta.name",
            "meta.create_time",
            "meta.created_by",
            "meta.update_time",
            "meta.updated_by",
            "spec.level",
            "spec.project_uuid",
            "spec.finding_metadata",
            "tenant_meta.namespace",
        ]


class CreateFindingPayload(BaseModel):
    """Payload for creating a new finding."""

    meta: FindingMeta
    spec: FindingSpec
    context: Context


def build_create_payload(**kwargs: Any) -> CreateFindingPayload:
    """Build CreateFindingPayload from kwargs (decoupled facade create)."""
    return CreateFindingPayload(**kwargs)


class UpdateFindingPayload(BaseModel):
    """Payload for updating an Endor Labs finding.

    MUTABLE FIELDS (can be updated via PATCH):
    - meta.tags: General resource tags
    - spec.finding_tags: Finding-specific tags
    - spec.dismiss: Dismissal status
    - spec.remediation: Remediation guidance
    - context.tags: Contextual tags

    IMMUTABLE FIELDS (read-only, managed by API):
    - uuid: Unique identifier
    - meta.name: Finding name
    - spec.level: Severity level (set by scan)
    - spec.category: Finding category (set by scan)
    - spec.project_uuid: Associated project (set at creation)
    - spec.finding_metadata: Scan-discovered metadata
    - tenant_meta.namespace: Namespace assignment

    Example:
        >>> payload = UpdateFindingPayload(
        ...     spec=FindingSpec(
        ...         dismiss=True,
        ...         finding_tags=["reviewed", "false-positive"]
        ...     )
        ... )
        >>> finding = update_finding(
        ...     client, namespace, uuid, payload, "spec.dismiss,spec.finding_tags"
        ... )

    """

    meta: FindingMetaUpdate | None = Field(None, description="Updated finding metadata")
    spec: FindingSpec | None = Field(None, description="Updated finding specification")
    context: Context | None = Field(None, description="Updated finding context")
