"""Generate Client stub (.pyi) from RESOURCE_REGISTRY and CUSTOM_FACADE_REGISTRY.

Single source of truth: the registry. Run from repo root with:
  uv run python scripts/generate_client_stub.py
Writes src/endorlabs/client_surface.pyi so Pyright types client.project, etc.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add src so we can import endorlabs.registry
repo_root = Path(__file__).resolve().parent.parent
src = repo_root / "src"
if str(src) not in sys.path:
    sys.path.insert(0, str(src))

from endorlabs.registry import CUSTOM_FACADE_REGISTRY, RESOURCE_REGISTRY


def main() -> None:
    out = src / "endorlabs" / "client_surface.pyi"
    lines: list[str] = [
        "# Generated by scripts/generate_client_stub.py — do not edit by hand.",
        "# Source of truth: endorlabs.registry.RESOURCE_REGISTRY and CUSTOM_FACADE_REGISTRY.",
        "",
        "from typing import Any",
        "",
        "from .api_client import APIClient",
        "from .facade import (",
        "    OssResourceFacade,",
        "    ResourceFacade,",
        "    ScanLogsFacade,",
        "    SystemResourceFacade,",
        ")",
        "",
    ]

    # Collect model imports: module -> [class names]; use relative .resources.*
    model_imports: dict[str, list[str]] = {}
    for entry in RESOURCE_REGISTRY:
        mod = entry.model_class.__module__
        name = entry.model_class.__name__
        # Use relative import for endorlabs.resources.*
        if mod.startswith("endorlabs."):
            mod = "." + mod[len("endorlabs.") :]
        if mod not in model_imports:
            model_imports[mod] = []
        if name not in model_imports[mod]:
            model_imports[mod].append(name)

    # Emit model imports (sorted for stable output)
    for mod in sorted(model_imports.keys()):
        names = sorted(model_imports[mod])
        lines.append(f"from {mod} import {', '.join(names)}")
    lines.append("")
    lines.append("")
    lines.append("class Client:")
    lines.append('    """Client with default namespace and resource facades."""')
    lines.append("")
    for entry in RESOURCE_REGISTRY:
        attr = entry.attr_name
        model_name = entry.model_class.__name__
        if entry.scope == "system":
            lines.append(f"    {attr}: SystemResourceFacade[{model_name}]")
        elif entry.scope == "oss":
            lines.append(f"    {attr}: OssResourceFacade[{model_name}]")
        else:
            lines.append(f"    {attr}: ResourceFacade[{model_name}]")
    for entry in CUSTOM_FACADE_REGISTRY:
        attr = entry.attr_name
        if attr == "scan_logs":
            lines.append(f"    {attr}: ScanLogsFacade")
        else:
            lines.append(f"    {attr}: Any  # Custom facade; add type when known")
    lines.append("")
    lines.append("    def __init__(")
    lines.append("        self,")
    lines.append("        api_client: APIClient | None = ...,")
    lines.append("        tenant: str | None = ...,")
    lines.append("        **client_kwargs: Any,")
    lines.append("    ) -> None: ...")
    lines.append("")
    lines.append("    def wait_until(")
    lines.append("        self,")
    lines.append("        predicate: Any,")  # Callable[[], bool]
    lines.append("        timeout: float = ...,")
    lines.append("        poll_interval_max: float = ...,")
    lines.append("    ) -> bool: ...")
    lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
