"""Provenance and manifest utilities for sync artifacts."""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def file_sha256(path: Path) -> str:
    """Compute file sha256 hash."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def get_endorctl_version() -> str:
    """Return current endorctl version string, or unknown."""
    executable = shutil.which("endorctl")
    if executable is None:
        return "unknown"
    try:
        result = subprocess.run(  # noqa: S603
            [executable, "--version"],
            capture_output=True,
            text=True,
            check=False,
        )
    except Exception:
        return "unknown"
    output = (result.stdout or result.stderr).strip()
    return output.splitlines()[0] if output else "unknown"


def build_provenance(spec_path: Path, toolchain: dict[str, Any]) -> dict[str, Any]:
    """Build sync provenance metadata payload."""
    return {
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "spec_path": spec_path.as_posix(),
        "spec_sha256": file_sha256(spec_path),
        "endorctl_version": get_endorctl_version(),
        "toolchain": toolchain,
    }


def write_json(path: Path, payload: dict[str, Any]) -> None:
    """Write deterministic JSON payload."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_artifacts_manifest(
    root: Path,
    excluded_paths: set[str] | None = None,
) -> dict[str, Any]:
    """Create deterministic manifest for all files under root."""
    excluded = excluded_paths or set()
    files: list[dict[str, Any]] = []
    for file_path in sorted(path for path in root.rglob("*") if path.is_file()):
        rel = file_path.relative_to(root).as_posix()
        if rel in excluded:
            continue
        files.append(
            {
                "path": rel,
                "sha256": file_sha256(file_path),
                "size_bytes": file_path.stat().st_size,
            }
        )
    manifest_bytes = json.dumps(files, sort_keys=True).encode("utf-8")
    overall = hashlib.sha256(manifest_bytes).hexdigest()
    return {"file_count": len(files), "overall_sha256": overall, "files": files}


def watermark_header(provenance: dict[str, Any]) -> str:
    """Build standard generated watermark header."""
    endorctl_version = provenance.get("endorctl_version", "unknown")
    spec_sha = provenance.get("spec_sha256", "unknown")
    return (
        f"# generated by model-sync\n"
        f"# endorctl_version: {endorctl_version}\n"
        f"# spec_sha256: {spec_sha}\n"
    )
