"""LangGraph StateGraph workflow for Endor Labs agent.

Provides create_endor_graph(client, llm) which returns a compiled
LangGraph workflow with Endor Labs tools bound.

The graph implements a Plan-Execute-Reflect pattern for multi-step reasoning:
1. Planner: Generates a step-by-step plan from the user request
2. Agent: Executes tool calls with plan context
3. Accumulate: Extracts and stores structured data from tool results
4. Reflect: Evaluates progress and decides whether to continue or synthesize
5. Synthesize: Composes final answer from collected data
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Annotated, Any, Literal

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from typing_extensions import TypedDict

from .prompts import (
    PLANNER_PROMPT,
    REFLECTION_PROMPT,
    SYNTHESIS_PROMPT,
    SYSTEM_PROMPT,
)
from .tools import create_tools

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel
    from langgraph.graph.state import CompiledStateGraph

    from endorlabs import Client


class AgentState(TypedDict, total=False):
    """State schema for the Endor Labs agent graph.

    Attributes:
        messages: List of conversation messages with automatic message merging.
        plan: Step-by-step plan generated by the planner node.
        current_step: Index of the current step being executed in the plan.
        collected_data: Structured data accumulated from tool results
            for cross-reference.
        scratchpad: LLM's intermediate reasoning notes between tool invocations.
    """

    messages: Annotated[list, add_messages]
    plan: list[str]
    current_step: int
    collected_data: dict[str, list[dict]]
    scratchpad: str


def _get_user_request(state: AgentState) -> str:
    """Extract the original user request from messages."""
    for msg in state.get("messages", []):
        if isinstance(msg, HumanMessage):
            return str(msg.content)
        if isinstance(msg, tuple) and msg[0] == "user":
            return str(msg[1])
    return ""


def _format_collected_data(collected_data: dict[str, list[dict]] | None) -> str:
    """Format collected data for prompt injection."""
    if not collected_data:
        return "No data collected yet."
    formatted_parts = []
    for tool_name, results in collected_data.items():
        formatted_parts.append(f"From {tool_name}:")
        for i, result in enumerate(results, 1):
            # Truncate large results for prompt context
            result_str = json.dumps(result, indent=2, default=str)
            if len(result_str) > 2000:
                result_str = result_str[:2000] + "\n... (truncated)"
            formatted_parts.append(f"  Result {i}: {result_str}")
    return "\n".join(formatted_parts)


def _format_plan(plan: list[str] | None) -> str:
    """Format plan steps for display."""
    if not plan:
        return "No plan generated."
    return "\n".join(f"{i}. {step}" for i, step in enumerate(plan, 1))


def create_endor_graph(
    client: Client,
    llm: BaseChatModel,
    *,
    extra_tools: list[Any] | None = None,
    system_prompt: str | None = None,
) -> CompiledStateGraph:
    """Create a LangGraph workflow with Endor Labs tools.

    The graph implements a Plan-Execute-Reflect pattern for multi-step reasoning:
    1. Planner node analyzes the request and generates a step-by-step plan
    2. Agent node executes tool calls with plan context
    3. Accumulate node extracts structured data from tool results
    4. Reflect node evaluates progress and decides to continue or synthesize
    5. Synthesize node composes final answer from collected data

    Args:
        client: An authenticated Endor Labs Client instance.
        llm: A LangChain chat model (e.g., ChatOpenAI, ChatAnthropic).
        extra_tools: Additional LangChain tools to merge with the
            registry-generated tools.  Passed to both the LLM and the
            ``ToolNode``.
        system_prompt: Override the default system prompt injected into
            the agent's context on every turn.

    Returns:
        A compiled LangGraph StateGraph ready for invocation.

    Example:
        >>> from langchain_openai import ChatOpenAI
        >>> from endorlabs import Client
        >>> from endorlabs.agent.langgraph_agent import create_endor_graph
        >>>
        >>> client = Client(tenant="my.namespace")
        >>> llm = ChatOpenAI(model="gpt-4o")
        >>> graph = create_endor_graph(client, llm)
        >>>
        >>> result = graph.invoke({
        ...     "messages": [("user", "List all projects")]
        ... })
        >>> print(result["messages"][-1].content)
    """
    # Create tools bound to the client, merge extras
    tools = create_tools(client)
    if extra_tools:
        tools = tools + list(extra_tools)

    # Resolve system prompt
    base_system_prompt = system_prompt or SYSTEM_PROMPT

    # Bind tools to the LLM
    llm_with_tools = llm.bind_tools(tools)

    def planner(state: AgentState) -> dict[str, Any]:
        """Generate a step-by-step plan from the user request."""
        user_request = _get_user_request(state)

        plan_prompt = PLANNER_PROMPT.format(user_request=user_request)
        response = llm.invoke([HumanMessage(content=plan_prompt)])

        # Parse plan steps from response
        plan_text = str(response.content)
        plan_steps = []
        for line in plan_text.strip().split("\n"):
            line = line.strip()
            # Match numbered steps like "1. Do something" or "1) Do something"
            if line and (line[0].isdigit() or line.startswith("-")):
                # Remove numbering/bullets
                step = line.lstrip("0123456789.-) ").strip()
                if step:
                    plan_steps.append(step)

        # If no structured plan found, use the whole response
        if not plan_steps:
            plan_steps = [plan_text.strip()]

        return {
            "plan": plan_steps,
            "current_step": 0,
            "collected_data": {},
            "scratchpad": f"Plan generated with {len(plan_steps)} steps.",
        }

    def call_model(state: AgentState) -> dict[str, Any]:
        """Call the LLM with plan context and tools."""
        plan = state.get("plan", [])
        current_step = state.get("current_step", 0)
        collected_data = state.get("collected_data", {})

        # Build context message with plan and progress
        context_parts = [base_system_prompt]
        if plan:
            context_parts.append(f"\nCurrent plan:\n{_format_plan(plan)}")
            if current_step < len(plan):
                step_msg = (
                    f"\nCurrently executing step"
                    f" {current_step + 1}: {plan[current_step]}"
                )
                context_parts.append(step_msg)
        if collected_data:
            data_summary = _format_collected_data(collected_data)
            context_parts.append(f"\nData collected so far:\n{data_summary}")

        context_message = SystemMessage(content="\n".join(context_parts))

        # Get messages without any existing system messages
        messages = [context_message]
        for msg in state.get("messages", []):
            if not isinstance(msg, SystemMessage):
                messages.append(msg)

        response = llm_with_tools.invoke(messages)
        return {"messages": [response]}

    def accumulate_data(state: AgentState) -> dict[str, Any]:
        """Extract and store structured data from tool results."""
        messages = state.get("messages", [])
        collected_data = dict(state.get("collected_data", {}))

        # Find recent tool messages
        for msg in reversed(messages):
            if isinstance(msg, ToolMessage):
                tool_name = getattr(msg, "name", "unknown_tool")
                try:
                    # Try to parse JSON from tool result
                    content = msg.content
                    data = json.loads(content) if isinstance(content, str) else content

                    # Store in collected_data keyed by tool name
                    if tool_name not in collected_data:
                        collected_data[tool_name] = []
                    collected_data[tool_name].append(data)
                except (json.JSONDecodeError, TypeError):
                    # Store raw content if not JSON
                    if tool_name not in collected_data:
                        collected_data[tool_name] = []
                    collected_data[tool_name].append({"raw": str(msg.content)})
                # Only process the most recent batch of tool messages
                break

        return {"collected_data": collected_data}

    def reflect(state: AgentState) -> dict[str, Any]:
        """Evaluate progress and update scratchpad."""
        user_request = _get_user_request(state)
        plan = state.get("plan", [])
        current_step = state.get("current_step", 0)
        collected_data = state.get("collected_data", {})
        scratchpad = state.get("scratchpad", "")

        reflection_prompt = REFLECTION_PROMPT.format(
            user_request=user_request,
            plan=_format_plan(plan),
            current_step=current_step + 1,
            collected_data=_format_collected_data(collected_data),
            scratchpad=scratchpad,
        )

        response = llm.invoke([HumanMessage(content=reflection_prompt)])
        reflection = str(response.content)

        # Update scratchpad with reflection
        new_scratchpad = (
            f"{scratchpad}\n\nStep {current_step + 1} reflection: {reflection}"
        )

        return {
            "scratchpad": new_scratchpad.strip(),
            "current_step": current_step + 1,
        }

    def synthesize(state: AgentState) -> dict[str, Any]:
        """Compose final answer from collected data."""
        user_request = _get_user_request(state)
        plan = state.get("plan", [])
        collected_data = state.get("collected_data", {})
        scratchpad = state.get("scratchpad", "")

        synthesis_prompt = SYNTHESIS_PROMPT.format(
            user_request=user_request,
            plan=_format_plan(plan),
            collected_data=_format_collected_data(collected_data),
            scratchpad=scratchpad,
        )

        response = llm.invoke([HumanMessage(content=synthesis_prompt)])

        # Add synthesized response as final AI message
        return {"messages": [AIMessage(content=str(response.content))]}

    def should_continue_to_tools(state: AgentState) -> Literal["tools", "synthesize"]:
        """Determine whether to continue to tools or synthesize."""
        last_message = state.get("messages", [])[-1] if state.get("messages") else None

        # If the LLM made tool calls, route to tools
        if isinstance(last_message, AIMessage) and last_message.tool_calls:
            return "tools"
        # Otherwise, go to synthesize
        return "synthesize"

    def should_continue_or_synthesize(
        state: AgentState,
    ) -> Literal["agent", "synthesize"]:
        """Determine whether to continue executing or synthesize based on reflection."""
        scratchpad = state.get("scratchpad", "")
        plan = state.get("plan", [])
        current_step = state.get("current_step", 0)

        # Check if reflection indicates we should synthesize
        if "SYNTHESIZE" in scratchpad.upper():
            return "synthesize"

        # Check if we've completed all plan steps
        if current_step >= len(plan):
            return "synthesize"

        # Check for ADJUST - treat as continue but with modified approach
        # (the reflection text will guide the agent)

        # Default: continue to agent
        return "agent"

    # Build the graph with Plan-Execute-Reflect pattern
    graph = StateGraph(AgentState)

    # Add nodes
    graph.add_node("planner", planner)
    graph.add_node("agent", call_model)
    graph.add_node("tools", ToolNode(tools))
    graph.add_node("accumulate", accumulate_data)
    graph.add_node("reflect", reflect)
    graph.add_node("synthesize", synthesize)

    # Add edges
    graph.add_edge(START, "planner")
    graph.add_edge("planner", "agent")
    graph.add_conditional_edges(
        "agent",
        should_continue_to_tools,
        {"tools": "tools", "synthesize": "synthesize"},
    )
    graph.add_edge("tools", "accumulate")
    graph.add_edge("accumulate", "reflect")
    graph.add_conditional_edges(
        "reflect",
        should_continue_or_synthesize,
        {"agent": "agent", "synthesize": "synthesize"},
    )
    graph.add_edge("synthesize", END)

    return graph.compile()
