"""Test cases for Metric resource operations.

Tests GET and LIST operations for Metric resources.
Metrics are typically auto-generated by analytics and are read-only.
"""

import pytest

import endorlabs
from endorlabs.core.types import ListParameters
from tests.conftest import (
    TEST_MAX_PAGES,
    TEST_PAGE_SIZE,
)


@pytest.mark.integration
class TestMetric:
    """Test cases for Metric resource operations."""

    @pytest.fixture(autouse=True)
    def setup_fast(self, api_client, namespace, root_namespace) -> None:
        """Fast setup: client and namespace from conftest."""
        self.client = api_client
        self.namespace = namespace
        self.root_namespace = root_namespace
        self.parent_namespace = root_namespace
        self.endor_client = endorlabs.Client(tenant=namespace, api_client=api_client)
        self.endor_root_client = endorlabs.Client(
            tenant=root_namespace, api_client=api_client
        )

    @pytest.fixture
    def sample_metric(self):
        """Fetch minimal sample data (1 item) for UUID operations.

        Function-scoped but only fetches when explicitly requested by tests.
        Lists in namespace to find all namespaces, matching the
        pattern used in test_metric_list.
        """
        # Fetch 1 item with traverse to find metrics across namespaces
        results = self.endor_root_client.Metric.list(
            list_params=ListParameters(page_size=TEST_PAGE_SIZE),
            max_pages=TEST_MAX_PAGES,
        )
        if not results:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")
        return results[0]  # Return single item, not list

    def test_metric_list(self) -> None:
        """LIST in namespace."""
        from endorlabs.core.exceptions import ServerError

        try:
            result = self.endor_client.Metric.list(
                max_pages=TEST_MAX_PAGES,
            )
        except ServerError:
            pytest.skip("Backend returned ServerError (list); skip")
        assert isinstance(result, list)

    def test_metric_get(self) -> None:
        """GET first item from LIST in namespace."""
        from endorlabs.core.exceptions import ServerError

        try:
            items = self.endor_client.Metric.list(
                max_pages=TEST_MAX_PAGES,
            )
        except ServerError:
            pytest.skip("Backend returned ServerError (list); skip")
        if not items:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")
        item = items[0]
        got = self.endor_client.Metric.get(item)
        assert got is not None
        assert got.uuid == item.uuid

    def test_metric_filter_by_project(self, sample_metric) -> None:
        """Test filtering metrics by project UUID."""
        print("\n=== TESTING FILTER METRICS BY PROJECT ===")

        # Get first metric to extract project UUID
        first_metric = sample_metric
        if not first_metric.spec or not first_metric.spec.project_uuid:
            pytest.skip("Metric has no project_uuid")

        project_uuid = first_metric.spec.project_uuid

        # Scope filter to the sampled resource namespace to avoid broad traversal.
        list_namespace = (
            first_metric.tenant_meta.namespace
            if first_metric.tenant_meta
            and getattr(first_metric.tenant_meta, "namespace", None)
            else self.root_namespace
        )
        list_params = ListParameters(
            filter=f'spec.project_uuid=="{project_uuid}"',
            page_size=TEST_PAGE_SIZE,
        )

        list_client = endorlabs.Client(tenant=list_namespace, api_client=self.client)
        filtered_results = list_client.Metric.list(
            list_params=list_params,
            max_pages=TEST_MAX_PAGES,
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        if len(filtered_results) == 0:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")

        # Verify all results belong to the project
        for result in filtered_results:
            assert result.spec.project_uuid == project_uuid, (
                "All filtered results should belong to the project"
            )

        print(f"Found {len(filtered_results)} metrics for project {project_uuid}")

    def test_metric_filter_by_analytic(self, sample_metric) -> None:
        """Test filtering metrics by analytic name."""
        print("\n=== TESTING FILTER METRICS BY ANALYTIC ===")

        # Get first metric to extract analytic name
        first_metric = sample_metric
        if not first_metric.spec or not first_metric.spec.analytic:
            pytest.skip("Metric has no analytic")

        analytic_name = first_metric.spec.analytic

        # Scope filter to the sampled resource namespace to avoid broad traversal.
        list_namespace = (
            first_metric.tenant_meta.namespace
            if first_metric.tenant_meta
            and getattr(first_metric.tenant_meta, "namespace", None)
            else self.root_namespace
        )
        list_params = ListParameters(
            filter=f'spec.analytic=="{analytic_name}"',
            page_size=TEST_PAGE_SIZE,
        )

        list_client = endorlabs.Client(tenant=list_namespace, api_client=self.client)
        filtered_results = list_client.Metric.list(
            list_params=list_params,
            max_pages=TEST_MAX_PAGES,
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        if len(filtered_results) == 0:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")

        # Verify all results have the same analytic
        for result in filtered_results:
            assert result.spec.analytic == analytic_name, (
                "All filtered results should have the same analytic"
            )

        print(f"Found {len(filtered_results)} metrics for analytic {analytic_name}")

    def test_metric_error_handling(self) -> None:
        """Test error handling for invalid UUID."""
        # Test with invalid UUID format - should raise ValidationError
        # (server returns HTTP 400 with gRPC code 3 INVALID_ARGUMENT)
        from endorlabs.core.exceptions import ValidationError

        with pytest.raises(ValidationError) as exc_info:
            self.endor_root_client.Metric.get("invalid-uuid")
        assert exc_info.value.resource_uuid == "invalid-uuid"
        assert exc_info.value.operation == "get"
        assert exc_info.value.status_code == 400
