"""Test cases for Metric resource operations.

Tests GET and LIST operations for Metric resources.
Metrics are typically auto-generated by analytics and are read-only.
"""

import pytest

from endorlabs.resources import metric
from endorlabs.types import ListParameters
from tests.conftest import (
    TEST_MAX_PAGES,
    TEST_MAX_PAGES_TRAVERSE,
    TEST_PAGE_SIZE,
    TEST_TRAVERSE_PAGE_SIZE,
)


@pytest.mark.integration
class TestMetric:
    """Test cases for Metric resource operations."""

    @pytest.fixture(autouse=True)
    def setup_fast(self, api_client, namespace, root_namespace) -> None:
        """Fast setup: client and namespace from conftest."""
        self.client = api_client
        self.namespace = namespace
        self.root_namespace = root_namespace
        self.parent_namespace = root_namespace

    @pytest.fixture
    def sample_metric(self):
        """Fetch minimal sample data (1 item) for UUID operations.

        Function-scoped but only fetches when explicitly requested by tests.
        Uses traverse=True to search across all namespaces, matching the
        pattern used in test_metric_list.
        """
        # Fetch 1 item with traverse to find metrics across namespaces
        results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params=ListParameters(traverse=True, page_size=TEST_PAGE_SIZE),
            max_pages=TEST_MAX_PAGES,
        )
        if not results:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")
        return results[0]  # Return single item, not list

    def test_metric_list(self) -> None:
        """LIST from tenant root with traverse."""
        import endorlabs
        from endorlabs.exceptions import ServerError

        client = endorlabs.Client(
            tenant=self.root_namespace,
            api_client=self.client,
        )
        try:
            result = client.metric.list(
                traverse=True,
                max_pages=TEST_MAX_PAGES_TRAVERSE,
            )
        except ServerError:
            pytest.skip("Backend returned ServerError (list); skip")
        assert isinstance(result, list)

    def test_metric_get(self) -> None:
        """GET first item from LIST (root + traverse)."""
        import endorlabs
        from endorlabs.exceptions import ServerError

        client = endorlabs.Client(
            tenant=self.root_namespace,
            api_client=self.client,
        )
        try:
            items = client.metric.list(
                traverse=True,
                max_pages=TEST_MAX_PAGES_TRAVERSE,
            )
        except ServerError:
            pytest.skip("Backend returned ServerError (list); skip")
        if not items:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")
        item = items[0]
        ns = (
            item.tenant_meta.namespace
            if item.tenant_meta and getattr(item.tenant_meta, "namespace", None)
            else self.root_namespace
        )
        got = client.metric.get(item.uuid, namespace=ns)
        assert got is not None
        assert got.uuid == item.uuid

    def test_metric_filter_by_project(self, sample_metric) -> None:
        """Test filtering metrics by project UUID."""
        print("\n=== TESTING FILTER METRICS BY PROJECT ===")

        # Get first metric to extract project UUID
        first_metric = sample_metric
        if not first_metric.spec or not first_metric.spec.project_uuid:
            pytest.skip("Metric has no project_uuid")

        project_uuid = first_metric.spec.project_uuid

        # Filter metrics by project
        list_params = ListParameters(
            filter=f'spec.project_uuid=="{project_uuid}"',
            traverse=True,
            page_size=TEST_TRAVERSE_PAGE_SIZE,
        )

        filtered_results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params,
            max_pages=TEST_MAX_PAGES_TRAVERSE,
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        if len(filtered_results) == 0:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")

        # Verify all results belong to the project
        for result in filtered_results:
            assert result.spec.project_uuid == project_uuid, (
                "All filtered results should belong to the project"
            )

        print(f"Found {len(filtered_results)} metrics for project {project_uuid}")

    def test_metric_filter_by_analytic(self, sample_metric) -> None:
        """Test filtering metrics by analytic name."""
        print("\n=== TESTING FILTER METRICS BY ANALYTIC ===")

        # Get first metric to extract analytic name
        first_metric = sample_metric
        if not first_metric.spec or not first_metric.spec.analytic:
            pytest.skip("Metric has no analytic")

        analytic_name = first_metric.spec.analytic

        # Filter metrics by analytic
        list_params = ListParameters(
            filter=f'spec.analytic=="{analytic_name}"',
            traverse=True,
            page_size=TEST_TRAVERSE_PAGE_SIZE,
        )

        filtered_results = metric.list_metrics(
            self.client,
            self.parent_namespace,
            list_params,
            max_pages=TEST_MAX_PAGES_TRAVERSE,
        )

        assert isinstance(filtered_results, list), (
            "Should return a list of filtered metrics"
        )
        if len(filtered_results) == 0:
            pytest.skip("No resources in scope (empty; may be filter/auth/scope)")

        # Verify all results have the same analytic
        for result in filtered_results:
            assert result.spec.analytic == analytic_name, (
                "All filtered results should have the same analytic"
            )

        print(f"Found {len(filtered_results)} metrics for analytic {analytic_name}")

    def test_metric_error_handling(self) -> None:
        """Test error handling for invalid UUID."""
        # Test with invalid UUID format - should raise ValidationError
        # (server returns HTTP 400 with gRPC code 3 INVALID_ARGUMENT)
        from endorlabs.exceptions import ValidationError

        with pytest.raises(ValidationError) as exc_info:
            metric.get_metric(self.client, self.parent_namespace, "invalid-uuid")
        assert exc_info.value.resource_uuid == "invalid-uuid"
        assert exc_info.value.operation == "get"
        assert exc_info.value.status_code == 400
